import{readFileSync,writeFileSync,mkdirSync}from"node:fs";import{dirname,join}from"node:path";import{fileURLToPath}from"node:url";import{createMmgParameters,MmgManeuveringModel,MmgPlanarSimulator}from"../../../packages/core/src/mmg.js";import{loadCase,validateCase}from"./operating-points.mjs";import{resolveResistance,solvePropellerEquilibrium}from"./resistance.mjs";
const root=dirname(fileURLToPath(import.meta.url)),baseModel=JSON.parse(readFileSync(join(root,"kvlcc2-l7.json"),"utf8")),finite=(x)=>typeof x==="number"&&Number.isFinite(x),dt=0.02,equilibriumTolerance=1e-10;
const value=(parameter)=>parameter?.value;
const resolvedProvenance=(configuration)=>JSON.parse(JSON.stringify(baseModel),(key,item)=>item?.provenance?{...item,provenance:{...item.provenance,status:item.provenance.status??"published",applicable_configuration:item.provenance.applicable_configuration??configuration}}:item);
const exactCrossing=(previous,current,target,key)=>{const fraction=(target-Math.abs(previous.psi))/(Math.abs(current.psi)-Math.abs(previous.psi));return previous[key]+fraction*(current[key]-previous[key]);};

function equilibriumFor(config,params){const model=new MmgManeuveringModel(params),speed=value(config.operating_point.speed_mps),rate=value(config.operating_point.propeller_rps),resistanceSpec=value(config.operating_point.resistance_model),effectivePropellerThrust=(rps,u)=>model.computeComponents({u,v:0,r:0},{propeller_rps:rps}).propeller[0];let propeller_rps,resistance,residual,components;
  if(rate==="solve_equilibrium"){const solution=solvePropellerEquilibrium({model,params,speed_mps:speed,resistance_model:{...resistanceSpec,provenance:config.operating_point.resistance_model}});({propeller_rps,components}=solution);resistance=solution.resistance;residual=solution.residual_n;
  }else{propeller_rps=rate;resistance=resolveResistance({...resistanceSpec,provenance:config.operating_point.resistance_model},speed,{...params,effectivePropellerThrust});components=model.computeComponents({u:speed,v:0,r:0},{propeller_rps});residual=components.propeller[0]-resistance.resistance_n;}
  const scale=Math.max(Math.abs(components.propeller[0]),Math.abs(resistance.resistance_n),1),normalized=Math.abs(residual)/scale;
  return{ship_speed_mps:speed,shaft_rate_rps:propeller_rps,shaft_rate_rpm:60*propeller_rps,advance_coefficient:components.diagnostics.advance_ratio,thrust_coefficient:components.diagnostics.KT,propeller_thrust_n:components.propeller[0]/(1-params.interaction.t_P),effective_propeller_thrust_n:components.propeller[0],hull_resistance_n:resistance.resistance_n,thrust_deduction:params.interaction.t_P,effective_wake_fraction:components.diagnostics.wP,net_surge_force_residual_n:residual,normalized_surge_force_residual:normalized,resistance_details:resistance.details,passed:normalized<equilibriumTolerance,tolerance:equilibriumTolerance};
}

function runTurning(params,setup,sign){const sim=new MmgPlanarSimulator(params,{dt,rudderRateRadS:setup.rudder_rate}),s={x:0,y:0,psi:0,u:setup.speed,v:0,r:0,delta:0},trace=[],target=sign*35*Math.PI/180;let previous={...s},advance,transfer,tactical,execute90,execute180,maxTransfer=0,steady=[];for(let step=0;step<30000;step++){previous={...s};sim.step(s,{rudder_rad:target,propeller_rps:setup.rps,straight_resistance_n:setup.resistance,resistance_reference_speed_mps:setup.speed});const time=(step+1)*dt,b=sim.model.lastBreakdown;maxTransfer=Math.max(maxTransfer,Math.abs(s.y));if(step%5===0)trace.push({step:step+1,t_s:time,...s,nP:setup.rps,hull:b.hull,propeller:b.propeller,rudder:b.rudder});if(advance===undefined&&Math.abs(s.psi)>=Math.PI/2){advance=exactCrossing(previous,s,Math.PI/2,"x");transfer=Math.abs(exactCrossing(previous,s,Math.PI/2,"y"));execute90=time-dt+dt*(Math.PI/2-Math.abs(previous.psi))/(Math.abs(s.psi)-Math.abs(previous.psi));}if(Math.abs(s.psi)>1.5*Math.PI)steady.push({...s});if(tactical===undefined&&Math.abs(s.psi)>=Math.PI){tactical=Math.abs(exactCrossing(previous,s,Math.PI,"y"));execute180=time-dt+dt*(Math.PI-Math.abs(previous.psi))/(Math.abs(s.psi)-Math.abs(previous.psi));}if(Math.abs(s.psi)>=2*Math.PI)break;if(!Object.values(s).every(finite))throw new Error("Non-finite turning state.");}const tail=steady.slice(-Math.min(steady.length,250)),mean=(key)=>tail.reduce((sum,row)=>sum+row[key],0)/Math.max(tail.length,1),steadySpeed=Math.hypot(mean("u"),mean("v")),steadyYaw=Math.abs(mean("r"));return{metrics:{advance_m:advance,advance_lpp:advance/params.L,transfer_m:transfer,transfer_lpp:transfer/params.L,tactical_diameter_m:tactical,tactical_diameter_lpp:tactical/params.L,steady_turning_diameter_m:steadyYaw?2*steadySpeed/steadyYaw:null,steady_turning_diameter_lpp:steadyYaw?2*steadySpeed/steadyYaw/params.L:null,steady_yaw_rate_rad_s:steadyYaw,steady_speed_mps:steadySpeed,speed_loss_percent:100*(setup.speed-steadySpeed)/setup.speed,time_to_90_s:execute90,time_to_180_s:execute180,duration_s:trace.at(-1)?.t_s??0,max_transfer_m:maxTransfer},trace};}

function runZigzag(params,setup,sign,angleDeg){const sim=new MmgPlanarSimulator(params,{dt,rudderRateRadS:setup.rudder_rate}),s={x:0,y:0,psi:0,u:setup.speed,v:0,r:0,delta:0},trace=[],angle=angleDeg*Math.PI/180;let target=sign*angle,phase=0,extreme=0,first,second,firstExecute,secondExecute,minSpeed=setup.speed;for(let step=0;step<30000;step++){sim.step(s,{rudder_rad:target,propeller_rps:setup.rps,straight_resistance_n:setup.resistance,resistance_reference_speed_mps:setup.speed});const time=(step+1)*dt,b=sim.model.lastBreakdown;minSpeed=Math.min(minSpeed,Math.hypot(s.u,s.v));if(step%5===0)trace.push({step:step+1,t_s:time,...s,nP:setup.rps,hull:b.hull,propeller:b.propeller,rudder:b.rudder});if(phase===0&&sign*s.psi>=angle){phase=1;target=-sign*angle;extreme=s.psi;firstExecute=time;}else if(phase===1){if(sign*s.psi>sign*extreme)extreme=s.psi;if(sign*s.r<=0){first=Math.abs(extreme)*180/Math.PI-angleDeg;phase=2;extreme=s.psi;}}else if(phase===2&&-sign*s.psi>=angle){phase=3;target=sign*angle;extreme=s.psi;secondExecute=time;}else if(phase===3){if(-sign*s.psi>-sign*extreme)extreme=s.psi;if(-sign*s.r<=0){second=Math.abs(extreme)*180/Math.PI-angleDeg;break;}}if(!Object.values(s).every(finite))throw new Error("Non-finite zig-zag state.");}return{metrics:{first_overshoot_deg:first,second_overshoot_deg:second,time_to_first_execute_s:firstExecute,time_to_second_execute_s:secondExecute,duration_s:trace.at(-1)?.t_s??0,minimum_speed_mps:minSpeed,speed_loss_percent:100*(setup.speed-minSpeed)/setup.speed},trace};}

function targetComparisons(targets,runs,params){if(!targets)return[];const lookup={"turn-port-35-advance":runs.turn_port_35.metrics.advance_lpp,"turn-port-35-tactical-diameter":runs.turn_port_35.metrics.tactical_diameter_lpp,"turn-starboard-35-advance":runs.turn_starboard_35.metrics.advance_lpp,"turn-starboard-35-tactical-diameter":runs.turn_starboard_35.metrics.tactical_diameter_lpp,"zigzag-port-10-first-overshoot":runs.zigzag_port_10.metrics.first_overshoot_deg,"zigzag-port-10-second-overshoot":runs.zigzag_port_10.metrics.second_overshoot_deg,"zigzag-port-20-first-overshoot":runs.zigzag_port_20.metrics.first_overshoot_deg,"zigzag-starboard-10-first-overshoot":runs.zigzag_starboard_10.metrics.first_overshoot_deg,"zigzag-starboard-10-second-overshoot":runs.zigzag_starboard_10.metrics.second_overshoot_deg,"zigzag-starboard-20-first-overshoot":runs.zigzag_starboard_20.metrics.first_overshoot_deg};return targets.metrics.map((target)=>{const observed=lookup[target.id],signed=observed-target.value;return{...target,observed,observed_dimensional:target.unit==="Lpp"?observed*params.L:observed,dimensional_unit:target.unit==="Lpp"?"m":"deg",signed_error:signed,relative_error:signed/target.value};});}

export function runCase(id,{includeTraces=true}={}){const config=validateCase(loadCase(id)),params=createMmgParameters(baseModel),equilibrium=equilibriumFor(config,params);if(!equilibrium.passed)throw new Error(`${id}: straight-ahead equilibrium residual ${equilibrium.normalized_surge_force_residual} exceeds ${equilibrium.tolerance}; maneuvers refused.`);const maneuverIds=value(config.operating_point.maneuvers),setup={speed:equilibrium.ship_speed_mps,rps:equilibrium.shaft_rate_rps,resistance:equilibrium.hull_resistance_n,rudder_rate:value(config.operating_point.rudder_rate_rad_s)},runs={};for(const maneuver of maneuverIds){if(maneuver.startsWith("turn_"))runs[maneuver]=runTurning(params,setup,maneuver.includes("port")?1:-1);else{const angle=maneuver.endsWith("20")?20:10;runs[maneuver]=runZigzag(params,setup,maneuver.includes("port")?1:-1,angle);}}const targetPath=value(config.operating_point.targets),targets=targetPath?JSON.parse(readFileSync(join(root,targetPath),"utf8")):null,artifact={schema_version:1,artifact_kind:"kvlcc2-operating-point-campaign",validation_label:config.validation_label,configuration_id:id,claim_limit:id==="marin_l7_experiment"?"Comparison with published MARIN scalar indices at the documented 620 rpm operating point; not validation of Vehicle B USV coefficients.":"Coefficient/equilibrium diagnostic only; not an exact reproduction of the authors' L7 simulation.",resolved_configuration:{case:config,model:resolvedProvenance(config.applicable_configuration),solver:{method:"rk4",dt_s:dt,equilibrium_tolerance:equilibriumTolerance}},equilibrium,maneuvers:runs,comparisons:targetComparisons(targets,runs,params)};if(!includeTraces)for(const run of Object.values(artifact.maneuvers))delete run.trace;return artifact;}

export function runSensitivity(){const config=validateCase(loadCase("marin_l7_experiment")),params=createMmgParameters(baseModel),trim=equilibriumFor(config,params),speed=trim.ship_speed_mps,rudder_rate=value(config.operating_point.rudder_rate_rad_s),rates=[9.9,10.233,10.3333333,11,11.8338],resistanceFactors=[0.9,1,1.1],model=new MmgManeuveringModel(params),rows=[];for(const rps of rates)for(const resistance_factor of resistanceFactors){const resistance=trim.hull_resistance_n*resistance_factor,components=model.computeComponents({u:speed,v:0,r:0},{propeller_rps:rps}),residual=components.propeller[0]-resistance,setup={speed,rps,resistance,rudder_rate},port=runTurning(params,setup,1),starboard=runTurning(params,setup,-1),z10p=runZigzag(params,setup,1,10),z10s=runZigzag(params,setup,-1,10);rows.push({propeller_rps:rps,resistance_factor,resistance_n:resistance,initial_equilibrium:{advance_coefficient:components.diagnostics.advance_ratio,thrust_coefficient:components.diagnostics.KT,effective_thrust_n:components.propeller[0],residual_n:residual,normalized_residual:Math.abs(residual)/Math.max(resistance,1)},outputs:{port_advance_lpp:port.metrics.advance_lpp,port_tactical_diameter_lpp:port.metrics.tactical_diameter_lpp,starboard_advance_lpp:starboard.metrics.advance_lpp,starboard_tactical_diameter_lpp:starboard.metrics.tactical_diameter_lpp,port_first_overshoot_deg:z10p.metrics.first_overshoot_deg,port_second_overshoot_deg:z10p.metrics.second_overshoot_deg,starboard_first_overshoot_deg:z10s.metrics.first_overshoot_deg,starboard_second_overshoot_deg:z10s.metrics.second_overshoot_deg,port_turn_duration_s:port.metrics.duration_s,starboard_turn_duration_s:starboard.metrics.duration_s,port_turn_speed_loss_percent:port.metrics.speed_loss_percent,starboard_turn_speed_loss_percent:starboard.metrics.speed_loss_percent}});}return{schema_version:1,artifact_kind:"kvlcc2-operating-point-sensitivity",validation_label:"sensitivity_analysis",claim_limit:"Uncertainty analysis only. No row is selected or represented as the historical Yasukawa operating point.",resolved_configuration:{case:config,model:resolvedProvenance(config.applicable_configuration),solver:{method:"rk4",dt_s:dt},baseline_trim:trim},baseline_resistance_provenance:config.operating_point.resistance_model,shaft_rates_rps:rates,resistance_factors:resistanceFactors,rows};}

export function writeArtifact(artifact,path){mkdirSync(dirname(path),{recursive:true});writeFileSync(path,`${JSON.stringify(artifact,null,2)}\n`);}
if(process.argv[1]===fileURLToPath(import.meta.url)){const id=process.argv[2]??"marin_l7_experiment",output=process.argv[3];try{const artifact=runCase(id);if(output)writeArtifact(artifact,output);console.log(JSON.stringify({...artifact,maneuvers:Object.fromEntries(Object.entries(artifact.maneuvers).map(([key,run])=>[key,{metrics:run.metrics,samples:run.trace?.length}]))},null,2));}catch(error){console.error(error.message);process.exitCode=1;}}
