import {readFile,writeFile} from "node:fs/promises";
import {gazeboOdomToTask} from "../rl-campaign/ports/task-trace-bridge.ts";
const ROOT="artifacts/gazebo/vehicle-b/rudder-sweep",ANGLES=[-.35,-.25,-.15,-.08,0,.08,.15,.25,.35],id=(a:number)=>`${a<0?"m":"p"}${Math.abs(a).toFixed(2).replace(".","p")}`;
const mean=(a:number[])=>a.reduce((s,x)=>s+x,0)/a.length;
const rows=[];
for(const angle of ANGLES){
 const node=JSON.parse(await readFile(`${ROOT}/node/${id(angle)}.json`,"utf8")),gazebo=JSON.parse(await readFile(`${ROOT}/gazebo/${id(angle)}.json`,"utf8"));
 const n=node.rows.slice(-100),raw=gazebo.rows.slice(-100),g=raw.map((x:any)=>gazeboOdomToTask(x.time_s,x.enu));
 rows.push({rudder_rad:angle,rudder_deg:angle*180/Math.PI,node:{mean_applied_rudder_rad:mean(n.map((x:any)=>x.applied_rudder_rad)),mean_speed_mps:mean(n.map((x:any)=>Math.abs(x.surge_speed_mps))),mean_yaw_rate_ned_rad_s:mean(n.map((x:any)=>x.yaw_rate_ned_rad_s)),mean_rudder_yaw_moment_nm:mean(n.map((x:any)=>x.rudder_yaw_moment_nm))},gazebo:{mean_speed_mps:mean(raw.map((x:any)=>Math.hypot(x.enu.vx,x.enu.vy))),mean_yaw_rate_ned_rad_s:mean(g.map((x:any)=>x.r_rad_s))}});
}
const active=rows.filter(x=>Math.abs(x.rudder_rad)>0);
function fit(x:number[],y:number[],quantity:string){const gain=x.reduce((s,v,i)=>s+v*y[i],0)/x.reduce((s,v)=>s+v*v,0),residual=y.map((v,i)=>v-gain*x[i]),rmse=Math.sqrt(mean(residual.map(v=>v*v))),responseRms=Math.sqrt(mean(y.map(v=>v*v))),relativeRmse=rmse/responseRms;return{quantity,model:"gazebo = gain * node",gain,rmse,response_rms:responseRms,relative_rmse:relativeRmse,consistent_scalar_multiple:relativeRmse<=.05,classification_threshold:"relative RMSE <= 0.05"};}
const yawFit=fit(active.map(r=>r.node.mean_yaw_rate_ned_rad_s),active.map(r=>r.gazebo.mean_yaw_rate_ned_rad_s),"yaw_rate_rad_s"),curvatureFit=fit(active.map(r=>r.node.mean_yaw_rate_ned_rad_s/r.node.mean_speed_mps),active.map(r=>r.gazebo.mean_yaw_rate_ned_rad_s/r.gazebo.mean_speed_mps),"yaw_rate_per_speed_rad_m");
const artifact={schema_version:1,artifact_kind:"vehicle-b-rudder-response-diagnostic",status:"diagnostic-only",method:{input:"same applied thrust and rudder histories",summary_window_s:5,reported_response:"mean yaw rate and speed-normalized yaw curvature; Node-only rudder yaw moment included",fixed_speed_caveat:"Open-loop propeller input is fixed, not surge speed. The observed mean speed magnitude is reported at every angle. Curvature r/U is included as a speed-normalized secondary diagnostic, but is not identical to a controlled fixed-speed force test."},curve_fits:{yaw_rate:yawFit,speed_normalized_curvature:curvatureFit},rows,interpretation:yawFit.consistent_scalar_multiple&&curvatureFit.consistent_scalar_multiple?"Both response curves are consistent with a scalar gain mismatch at these probes.":"A scalar gain does not explain both the yaw-rate and speed-normalized curvature curves; angle-dependent structure, stall/saturation, or coupled hull-speed response remains.",claim_limit:"Diagnostic comparison only; no parameter was tuned and the preregistered Vehicle B gate is unchanged."};
await writeFile(`${ROOT}/report.json`,JSON.stringify(artifact,null,2)+"\n");console.log(JSON.stringify(artifact,null,2));
