import {readFile,writeFile} from "node:fs/promises";import {gazeboOdomToTask} from "../rl-campaign/ports/task-trace-bridge.ts";
const root="artifacts/gazebo/vehicle-b/turning-diagnostic",L=4,rad=(d:number)=>d*Math.PI/180;
function unwrap(a:any[]){let offset=0,previous=a[0].yaw_rad;return a.map((row,i)=>{if(i){const delta=row.yaw_rad-previous;if(delta>Math.PI)offset-=2*Math.PI;else if(delta< -Math.PI)offset+=2*Math.PI;previous=row.yaw_rad;}return{...row,yaw_rad:row.yaw_rad+offset};});}
function crossing(a:any[],target:number,start:number){for(let i=start+1;i<a.length;i++)if((a[i-1].yaw_rad-target)*(a[i].yaw_rad-target)<=0)return i;return-1}
function interp(a:any[],i:number,target:number,key:"N_m"|"E_m"){const p=a[i-1],q=a[i],f=(target-p.yaw_rad)/(q.yaw_rad-p.yaw_rad);return p[key]+f*(q[key]-p[key])}
function metrics(a:any[],start:number){const base=a[start],direction=Math.sign(a.at(-1).yaw_rad-base.yaw_rad)||1,i90=crossing(a,base.yaw_rad+direction*Math.PI/2,start),i180=crossing(a,base.yaw_rad+direction*Math.PI,start);if(i90<0||i180<0)return null;const c=Math.cos(base.yaw_rad),s=Math.sin(base.yaw_rad),project=(N:number,E:number)=>({along:(N-base.N_m)*c+(E-base.E_m)*s,cross:-(N-base.N_m)*s+(E-base.E_m)*c}),p90=project(interp(a,i90,base.yaw_rad+direction*Math.PI/2,"N_m"),interp(a,i90,base.yaw_rad+direction*Math.PI/2,"E_m")),p180=project(interp(a,i180,base.yaw_rad+direction*Math.PI,"N_m"),interp(a,i180,base.yaw_rad+direction*Math.PI,"E_m"));return{advance_lpp:p90.along/L,transfer_lpp:Math.abs(p90.cross)/L,tactical_diameter_lpp:Math.abs(p180.cross)/L};}
const marin=JSON.parse(await readFile("validation/external-references/kvlcc2-marin/artifacts/kvlcc2-marin-trajectory-comparison.json","utf8")),rows=[];
for(const sign of [-1,1]){const name=sign<0?"negative-35deg":"positive-35deg",node=JSON.parse(await readFile(`${root}/node/${name}.json`,"utf8")),raw=JSON.parse(await readFile(`${root}/gazebo/${name}.json`,"utf8")),gz=raw.rows.map((x:any)=>gazeboOdomToTask(x.time_s,x.enu)),reference=marin.runs.find((x:any)=>x.id.includes(sign<0?"tc_-35":"tc_35")),mmg=marin.simulator_scoring.runs.find((x:any)=>x.id===reference.id),nodeUsv=metrics(unwrap(node.rows),node.execute_step)!,gazeboUsv=metrics(unwrap(gz),node.execute_step)!,distance=(m:any)=>Math.hypot(m.advance_lpp-reference.gating_metrics.advance_lpp,m.tactical_diameter_lpp-reference.gating_metrics.tactical_diameter_lpp);rows.push({direction:name,marin_kvlcc2_measured:reference.gating_metrics,bcod_kvlcc2_mmg:Object.fromEntries(mmg.imo.map((x:any)=>[x.metric,x.actual])),bcod_vehicle_b_usv:nodeUsv,gazebo_vehicle_b_usv:gazeboUsv,nondimensional_resemblance_distance:{metrics:["advance_lpp","tactical_diameter_lpp"],bcod_vehicle_b_usv_to_marin_kvlcc2:distance(nodeUsv),gazebo_vehicle_b_usv_to_marin_kvlcc2:distance(gazeboUsv),closer:"bcod Vehicle-B-USV"}});}
const artifact={schema_version:1,artifact_kind:"vehicle-b-three-way-turning-diagnostic",status:"diagnostic-completed-cross-hull-anchor-not-validating",maneuver:"5 s straight acceleration, then measured/applied 35 degree rudder with shared applied thrust history",rows,interpretation:"The MARIN and bcod KVLCC2 rows are a valid same-hull comparison. The two Vehicle-B-USV rows are a valid cross-implementation comparison. Comparing either USV row numerically with MARIN is only a nondimensional resemblance diagnostic because hull geometry, scale, coefficients, initial speed, propeller and rudder differ.",evidence_correction:"The existing MARIN scoring artifact marks both turning-circle trajectory windows as passed, but the overall turning cases failed their precommitted IMO-metric gates (advance for both directions and tactical diameter for positive rudder).",claim_limit:"This artifact cannot establish which 4 m USV implementation is closer to reality. A real three-way anchor requires a Gazebo KVLCC2 model driven by the measured MARIN rudder/RPM histories, or measured Vehicle-B-USV data."};await writeFile(`${root}/report.json`,JSON.stringify(artifact,null,2)+"\n");console.log(JSON.stringify(artifact,null,2));
