import {createHash} from "node:crypto";
import {mkdir,readFile,writeFile} from "node:fs/promises";
import {replayManeuver} from "../goldenLogCompare.js";
const ROOT="artifacts/gazebo/vehicle-a",SOURCE="artifacts/gazebo/live-cross-check",IDS=["constant-thrust","turning-circle","yaw-turn","zig-zag","coast-down","current-drift"];
const sha=async(p:string)=>createHash("sha256").update(await readFile(p)).digest("hex");
const parse=async(p:string)=>{const [h,...lines]=(await readFile(p,"utf8")).trim().split(/\r?\n/),keys=h.split(",");return lines.map(line=>Object.fromEntries(line.split(",").map((x,i)=>[keys[i],i===keys.length-1?x:Number(x)])));};
const pct=(a:number[],p:number)=>[...a].sort((x,y)=>x-y)[Math.min(a.length-1,Math.ceil(p*a.length)-1)],stats=(a:number[])=>({mean:a.reduce((s,x)=>s+x,0)/a.length,p95:pct(a,.95),max:Math.max(...a),final:a.at(-1)}),wrap=(x:number)=>Math.abs(Math.atan2(Math.sin(x),Math.cos(x))),scenarios=[];
for(const id of IDS){
  const manifest=JSON.parse(await readFile(`gazebo/generated/manifests/otter_${id}.json`,"utf8")),gz=(await parse(`${SOURCE}/${id}.csv`)).slice(0,manifest.steps),wrench=(await parse(`${SOURCE}/${id}-wrenches.csv`)).slice(0,manifest.steps),node=replayManeuver(id,undefined,{env:manifest.env}).slice(0,manifest.steps);
  if(node.length!==gz.length||gz.length!==wrench.length)throw Error(`${id}: row mismatch ${node.length}/${gz.length}/${wrench.length}`);
  const commands=wrench.map((x:any)=>({time_s:x.t,body_wrench_n_nm:{surge_n:x.body_surge,sway_n:x.body_sway,yaw_nm:x.body_yaw}}));
  const bcod=node.map((x:any,i:number)=>({time_s:x.t,north_m:x.N,east_m:x.E,heading_rad:x.yaw,surge_mps:x.u,sway_mps:x.v,yaw_rate_rad_s:x.r,command:commands[i],delivered_body_wrench:commands[i].body_wrench_n_nm})),gazebo=gz.map((x:any,i:number)=>({time_s:x.t,north_m:x.N,east_m:x.E,heading_rad:x.yaw,surge_mps:x.u,sway_mps:x.v,yaw_rate_rad_s:x.r,command:commands[i],delivered_body_wrench:commands[i].body_wrench_n_nm}));
  const errors=bcod.map((x:any,i:number)=>({time_s:x.time_s,horizontal_position_error_m:Math.hypot(x.north_m-gazebo[i].north_m,x.east_m-gazebo[i].east_m),heading_error_rad:wrap(x.heading_rad-gazebo[i].heading_rad)})),pos=errors.map((x:any)=>x.horizontal_position_error_m),heading=errors.map((x:any)=>x.heading_error_rad),inc=pos.map((x:number,i:number)=>i?x-pos[i-1]:0),jumpIndex=inc.indexOf(Math.max(...inc)),median=pct(inc.map(Math.abs),.5),jump=inc[jumpIndex];
  scenarios.push({id,dt_s:manifest.dt,actuation:{mode:manifest.gazebo.actuationMode,requested_schedule:commands,delivery_note:"Gazebo ApplyLinkWrench applies the logged body wrench directly; Vehicle A's parity fixture does not expose physical port/starboard pod delivery."},bcod_sim:bcod,gazebo_harmonic:gazebo,error_time_series:errors,summary:{horizontal_position_error_m:stats(pos),heading_error_rad:stats(heading),divergence_pattern:jump>Math.max(.05,10*median)?{kind:"sharp-jump",time_s:errors[jumpIndex].time_s,increment_m:jump}:{kind:"steady-growth",largest_increment_time_s:errors[jumpIndex].time_s,largest_increment_m:jump}}});
}
const artifact={schema_version:1,artifact_kind:"vehicle-a-open-loop-fixed-input-trajectory-comparison",vehicle:"vehicle-a-otter",timing:{physics_timestep_s:.05,full_resolution:true},scenarios,provenance:{maneuvers:{path:"gazebo/parityManeuvers.js",sha256:await sha("gazebo/parityManeuvers.js")},node_replay:{path:"validation/goldenLogCompare.js",sha256:await sha("validation/goldenLogCompare.js")},gazebo_capture:{path:"gazebo/captureGazeboLog.js",sha256:await sha("gazebo/captureGazeboLog.js")},model:{path:"gazebo/generated/models/otter/model.sdf",sha256:await sha("gazebo/generated/models/otter/model.sdf")}},claim_limit:"Implementation comparison using the stabilized primitive-buoyancy Vehicle A fixture and direct body-wrench actuation; not physical pod-actuator or coupled6 hydrostatics validation."};await mkdir(ROOT,{recursive:true});await writeFile(`${ROOT}/open-loop-trajectory-comparison.json`,JSON.stringify(artifact,null,2)+"\n");console.log(JSON.stringify(Object.fromEntries(scenarios.map((x:any)=>[x.id,x.summary])),null,2));
