import {createHash} from "node:crypto";
import {mkdir,readFile,writeFile} from "node:fs/promises";
import {resolveExperiment} from "../../packages/experiment-schema/src/index.ts";
import {HeadlessMarineSimulation} from "../../packages/core/src/simulation.ts";
import {LegacyProductionEngine} from "../../backends/node/src/legacy-production-engine.ts";

const DT=.05,STEPS=1200,THRUST_N=.03*1340.506075016061,PORT_Y_M=-.81,STARBOARD_Y_M=.81;
const sourcePath="artifacts/gazebo/vehicle-c/open-loop-trajectory-comparison-thrust-corrected.json";
const source=JSON.parse(await readFile(sourcePath,"utf8"));
const retained=source.scenarios.find((x:any)=>x.id==="rotation-in-place");
if(!retained)throw Error("rotation-in-place source is missing");
const cfg=resolveExperiment({schema_version:1,experiment:{name:"vehicle-c-rotation-long-horizon",seed:7319,timestep_s:DT,duration_s:STEPS*DT},backend:{type:"node"},vehicle:{preset:"vehicle-c-azimuth",plant:"coupled6"},environment:{current_mps:[0,0,0],wind_mps:[0,0,0]},initial_state:{position_ned_m:[10000,10000,0],attitude_rad:[0,0,0]},mission:{type:"rl-common-waypoint-v1",waypoints:[{north_m:19000,east_m:19000}]}} as any);
const sim=new HeadlessMarineSimulation(new LegacyProductionEngine());sim.reset(cfg);const trace=[];
for(let step=0;step<STEPS;step++){sim.step({actuators:{effectors:{"azimuth-port":{thrust:THRUST_N,azimuth:0},"azimuth-starboard":{thrust:-THRUST_N,azimuth:0}}}});const truth:any=sim.getGroundTruth();trace.push({time_s:(step+1)*DT,north_m:truth.position_ned_m[0]-10000,east_m:truth.position_ned_m[1]-10000,heading_rad:truth.attitude_rad[2],surge_mps:truth.velocity_body_mps[0],sway_mps:truth.velocity_body_mps[1],yaw_rate_rad_s:truth.angular_rate_body_rad_s[2]});}sim.dispose();
const extrema=(key:"north_m"|"east_m")=>({min:Math.min(...trace.map((x:any)=>x[key])),max:Math.max(...trace.map((x:any)=>x[key])),final:trace.at(-1)![key]});
const tail=trace.slice(-200),speed=(x:any)=>Math.hypot(x.surge_mps,x.sway_mps),mean=(a:number[])=>a.reduce((s,x)=>s+x,0)/a.length;
const gz=retained.gazebo_harmonic,bcod6=retained.bcod_sim;
const report={schema_version:1,artifact_kind:"vehicle-c-rotation-in-place-diagnostic",command:{port_thrust_n:THRUST_N,starboard_thrust_n:-THRUST_N,port_azimuth_rad:0,starboard_azimuth_rad:0,net_commanded_force_body_n:[0,0,0],net_commanded_yaw_torque_nm:-PORT_Y_M*THRUST_N-STARBOARD_Y_M*(-THRUST_N),pod_y_offsets_body_frd_m:[PORT_Y_M,STARBOARD_Y_M]},retained_six_second_comparison:{bcod_final_m:{north:bcod6.at(-1).north_m,east:bcod6.at(-1).east_m},gazebo_final_m:{north:gz.at(-1).north_m,east:gz.at(-1).east_m},shared_directional_component:"Both traces initially and finally move toward negative north; east components have opposite signs.",gazebo_translation_is_zero:false},bcod_long_horizon:{duration_s:STEPS*DT,samples:trace.length,north_m:extrema("north_m"),east_m:extrema("east_m"),final_horizontal_offset_m:Math.hypot(trace.at(-1)!.north_m,trace.at(-1)!.east_m),mean_horizontal_speed_last_10_s_mps:mean(tail.map(speed)),mean_yaw_rate_last_10_s_rad_s:mean(tail.map((x:any)=>x.yaw_rate_rad_s)),trace},mechanism_assessment:{classification:"real cross-model dynamics difference; root cause not isolated",not_command_cancellation_error:true,evidence:"BCOD receives equal-and-opposite delivered thrust at zero azimuth, so commanded net force cancels exactly. BCOD retains full coupled6 added-mass/Coriolis dynamics; the Gazebo comparison omits those couplings and also has milliradian pod-angle residuals.",relationship_to_known_straight_line_issue:"not the same operating signature, but a shared actuator-pairing root cause has not been ruled out"},provenance:{source:{path:sourcePath,sha256:createHash("sha256").update(await readFile(sourcePath)).digest("hex")},generator:"validation/gazebo-vehicles/diagnose_vehicle_c_rotation.ts"}};
await mkdir("artifacts/gazebo/vehicle-c",{recursive:true});await writeFile("artifacts/gazebo/vehicle-c/rotation-in-place-diagnostic.json",JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({command:report.command,retained:report.retained_six_second_comparison,long_horizon:{...report.bcod_long_horizon,trace:undefined},assessment:report.mechanism_assessment},null,2));
