import {mkdir,readFile,writeFile} from "node:fs/promises";
import {resolveExperiment} from "../../packages/experiment-schema/src/index.ts";
import {HeadlessMarineSimulation} from "../../packages/core/src/simulation.ts";
import {LegacyProductionEngine} from "../../backends/node/src/legacy-production-engine.ts";
const DT=.05,STEPS=600,EXECUTE=100,ORIGIN=[10000,10000] as const,root="artifacts/gazebo/vehicle-b/turning-diagnostic";
await mkdir(`${root}/node`,{recursive:true});await mkdir(`${root}/schedules`,{recursive:true});
for(const sign of [-1,1]){const name=sign<0?"negative-35deg":"positive-35deg",target=sign*35*Math.PI/180,config=resolveExperiment({schema_version:1,experiment:{name:`vehicle-b-${name}`,seed:7319,timestep_s:DT,duration_s:STEPS*DT},backend:{type:"node"},vehicle:{preset:"vehicle-b-rudder",plant:"coupled6"},environment:{current_mps:[0,0,0],wind_mps:[0,0,0]},initial_state:{position_ned_m:[...ORIGIN,0],attitude_rad:[0,0,0]},mission:{type:"rl-common-waypoint-v1",waypoints:[{north_m:19000,east_m:19000}]}} as any),sim=new HeadlessMarineSimulation(new LegacyProductionEngine());sim.reset(config);const rows=[],samples=[];
 for(let step=0;step<STEPS;step++){const command={propeller_rps:15,rudder_rad:step<EXECUTE?0:target},result:any=sim.step({actuators:command}),truth:any=sim.getGroundTruth(),d=result.info.vehicle_diagnostics;if(result.terminated||(result.truncated&&step<STEPS-1))throw new Error(`${name} stopped at ${step}: ${String(result.info.stop_reason)}`);rows.push({step,time_s:step*DT,N_m:truth.position_ned_m[0]-ORIGIN[0],E_m:truth.position_ned_m[1]-ORIGIN[1],yaw_rad:truth.attitude_rad[2],u_mps:truth.velocity_body_mps[0],r_rad_s:truth.angular_rate_body_rad_s[2],applied_rudder_rad:d.applied_command.rudder_rad,applied_thrust_n:d.force_components.propeller[0]});samples.push({step,time_s:step*DT,thrust_n:d.force_components.propeller[0],steer_rad:d.applied_command.rudder_rad});}sim.dispose();await writeFile(`${root}/node/${name}.json`,JSON.stringify({schema_version:1,execute_step:EXECUTE,rows},null,2)+"\n");await writeFile(`${root}/schedules/${name}.json`,JSON.stringify({schema_version:1,vehicle:"vehicle-b-rudder",case:name,seed:7319,dt_s:DT,samples},null,2)+"\n");}

