import {mkdir,writeFile} from "node:fs/promises";import {resolveExperiment} from "../../packages/experiment-schema/src/index.ts";import {HeadlessMarineSimulation} from "../../packages/core/src/simulation.ts";import {LegacyProductionEngine} from "../../backends/node/src/legacy-production-engine.ts";
const DT=.05,CAP=.03*1340.506075016061,Y=.81,ROOT="artifacts/gazebo/vehicle-c-generic",pod=(thrust:number)=>({thrust,azimuth:0}),fromWrench=(surge:number,yaw:number)=>({port:pod((surge+yaw/Y)/2),starboard:pod((surge-yaw/Y)/2)});
const designs:any={
 "turning-circle":{duration_s:30,current:[0,0,0],command:()=>fromWrench(59.0,17.0),rationale:"Vehicle A turning-circle wrench scaled to keep the higher-loaded pod below the validated 3% ceiling."},
 "yaw-turn":{duration_s:20,current:[0,0,0],command:()=>fromWrench(55,1),rationale:"Vehicle A maneuver kind retained; the resulting 28.12/26.88 N pod pair is inside the 3% envelope."},
 "zig-zag":{duration_s:30,current:[0,0,0],command:(s:number)=>fromWrench(60,(Math.floor(s/100)%2? -1:1)*15.12),rationale:"Five-second alternating yaw-moment holds at 39.33/20.67 N pod loading."},
 "coast-down":{duration_s:30,current:[0,0,0],command:(s:number)=>fromWrench(s<300?60:0,0),rationale:"Fifteen-second 30 N-per-pod acceleration followed by fifteen seconds at zero thrust."}
};
await mkdir(`${ROOT}/node-reference`,{recursive:true});await mkdir(`${ROOT}/schedules`,{recursive:true});
for(const [name,d] of Object.entries<any>(designs)){const steps=Math.round(d.duration_s/DT),cfg=resolveExperiment({schema_version:1,experiment:{name:`vehicle-c-generic-${name}`,seed:7319,timestep_s:DT,duration_s:d.duration_s},backend:{type:"node"},vehicle:{preset:"vehicle-c-azimuth",plant:"coupled6"},environment:{current_mps:d.current,wind_mps:[0,0,0]},initial_state:{position_ned_m:[10000,10000,0],attitude_rad:[0,0,0]},mission:{type:"rl-common-waypoint-v1",waypoints:[{north_m:19000,east_m:19000}]}} as any),sim=new HeadlessMarineSimulation(new LegacyProductionEngine());sim.reset(cfg);const rows=[],samples=[];
 for(let step=0;step<steps;step++){const desired=d.command(step);if(Math.max(Math.abs(desired.port.thrust),Math.abs(desired.starboard.thrust))>CAP+1e-9)throw Error(`${name}: 3% cap exceeded`);const result:any=sim.step({actuators:{effectors:{"azimuth-port":desired.port,"azimuth-starboard":desired.starboard}}}),truth:any=sim.getGroundTruth(),diag=result.info.vehicle_diagnostics,port=diag.effectors.find((x:any)=>x.id==="azimuth-port"),starboard=diag.effectors.find((x:any)=>x.id==="azimuth-starboard");const sample={step,time_s:step*DT,port_commanded_thrust_n:desired.port.thrust,port_commanded_azimuth_rad:0,port_thrust_n:port.thrust,port_azimuth_rad:port.azimuth,starboard_commanded_thrust_n:desired.starboard.thrust,starboard_commanded_azimuth_rad:0,starboard_thrust_n:starboard.thrust,starboard_azimuth_rad:starboard.azimuth};samples.push(sample);rows.push({step,time_s:(step+1)*DT,state:{N_m:truth.position_ned_m[0]-10000,E_m:truth.position_ned_m[1]-10000,yaw_rad:truth.attitude_rad[2],u_mps:truth.velocity_body_mps[0],v_mps:truth.velocity_body_mps[1],r_rad_s:truth.angular_rate_body_rad_s[2]},commanded:desired,applied:{port:{thrust_n:port.thrust,azimuth_rad:port.azimuth},starboard:{thrust_n:starboard.thrust,azimuth_rad:starboard.azimuth}}});}sim.dispose();
 const metadata={maneuver:name,validated_cap_fraction:.03,cap_n_per_pod:CAP,max_command_n_per_pod:Math.max(...samples.flatMap((x:any)=>[Math.abs(x.port_commanded_thrust_n),Math.abs(x.starboard_commanded_thrust_n)])),duration_s:d.duration_s,rationale:d.rationale,current_ned_mps:d.current,matched_input_method:"Replay bcod-sim delivered thrust and azimuth schedule into Gazebo"};await writeFile(`${ROOT}/node-reference/${name}.json`,JSON.stringify({schema_version:1,metadata,rows},null,2)+"\n");await writeFile(`${ROOT}/schedules/${name}.json`,JSON.stringify({schema_version:1,dt_s:DT,current_enu_mps:{x:d.current[1],y:d.current[0],z:0},metadata,samples},null,2)+"\n");console.log(name,metadata.max_command_n_per_pod,rows.at(-1).state);}
