import {createHash} from "node:crypto";
import {mkdir,readFile,unlink,writeFile} from "node:fs/promises";
import {spawnSync} from "node:child_process";
import {resolveExperiment} from "../../packages/experiment-schema/src/index.ts";
import {HeadlessMarineSimulation} from "../../packages/core/src/simulation.ts";
import {LegacyProductionEngine} from "../../backends/node/src/legacy-production-engine.ts";
import {DT,HOLD,MAX_STEPS,PHYSICS_MISMATCH,SEED,TERMINAL_RADIUS,controllerMetadata,geometry,makeControl,scenario} from "./vehicle_c_closed_loop_shared.ts";

const ROOT="artifacts/gazebo/vehicle-c",GAZEBO_TMP=`${ROOT}/closed-loop-gazebo-30013-thrust-corrected.json`,OUTPUT=`${ROOT}/closed-loop-comparison-30013-thrust-corrected.json`,ORIGINAL=`${ROOT}/closed-loop-comparison-30013.json`,sc=scenario(),final=sc.route_ned_m.at(-1)!;
const sha=async(path:string)=>createHash("sha256").update(await readFile(path)).digest("hex");
const strip=(x:any)=>({time_s:x.time_s,north_m:x.north_m,east_m:x.east_m,heading_rad:x.heading_rad,distance_to_goal_m:x.distance_to_goal_m,surge_mps:x.surge_mps,yaw_rate_rad_s:x.yaw_rate_rad_s,waypoint_index:x.waypoint_index,port_thrust_n:x.port_thrust_n,port_azimuth_rad:x.port_azimuth_rad,starboard_thrust_n:x.starboard_thrust_n,starboard_azimuth_rad:x.starboard_azimuth_rad,saturation_scale:x.saturation_scale,degradation:x.degradation});
async function bcod(){
  const cfg=resolveExperiment({schema_version:1,experiment:{name:"vehicle-c-closed-loop-30013",seed:SEED,timestep_s:DT,duration_s:MAX_STEPS*DT},backend:{type:"node"},vehicle:{preset:"vehicle-c-azimuth",plant:"coupled6"},environment:{current_mps:sc.current_ned_mps,wind_mps:sc.wind_ned_mps},initial_state:{position_ned_m:[...sc.start_ned_m,0],attitude_rad:[0,0,sc.initial_heading_rad]},mission:{type:"rl-common-waypoint-v1",waypoints:[{north_m:19000,east_m:19000}]},sensors:[]} as any),sim=new HeadlessMarineSimulation(new LegacyProductionEngine()),control=makeControl(),run={waypoint:0,scenario:sc};sim.reset(cfg);let last:any=null,closest=Infinity,success=false;const rows:any[]=[];
  for(let step=0;step<MAX_STEPS&&!success;step++){const before:any=sim.getGroundTruth(),g=geometry(run,before);if(step%HOLD===0||!last)last=control.command(before,{north_m:g.b[0],east_m:g.b[1],heading_rad:g.heading,waypoint_index:run.waypoint},sc.current_ned_mps);const result:any=sim.step({actuators:{desiredWrench:last.controller.desired_wrench}}),truth:any=sim.getGroundTruth(),d=result.info.vehicle_diagnostics,a=d.allocation_diagnostics,active=geometry(run,truth);control.controller.noteAllocationSaturated(a.saturation_scale<1-1e-12);if(run.waypoint<sc.route_ned_m.length-1&&(active.distance<=6||active.passed))run.waypoint++;const distance=Math.hypot(final[0]-truth.position_ned_m[0],final[1]-truth.position_ned_m[1]);if(run.waypoint===sc.route_ned_m.length-1){closest=Math.min(closest,distance);success=closest<=TERMINAL_RADIUS;}const port=d.applied_command["azimuth-port"],starboard=d.applied_command["azimuth-starboard"];rows.push({time_s:truth.time_s,north_m:truth.position_ned_m[0],east_m:truth.position_ned_m[1],heading_rad:truth.attitude_rad[2],distance_to_goal_m:distance,surge_mps:truth.velocity_body_mps[0],yaw_rate_rad_s:truth.angular_rate_body_rad_s[2],waypoint_index:run.waypoint,port_thrust_n:port.thrust,port_azimuth_rad:port.azimuth,starboard_thrust_n:starboard.thrust,starboard_azimuth_rad:starboard.azimuth,saturation_scale:a.saturation_scale,degradation:a.degradation});if(result.terminated||result.truncated)break;}
  sim.dispose();return{rows,outcome:{success,closest_approach_m:Number.isFinite(closest)?closest:null,steps:rows.length}};
}
function stats(values:number[]){const sorted=[...values].sort((a,b)=>a-b),mean=values.reduce((s,x)=>s+x,0)/values.length;return{mean,p95:sorted[Math.min(sorted.length-1,Math.ceil(.95*sorted.length)-1)],max:sorted.at(-1)};}
const node=await bcod();await mkdir(ROOT,{recursive:true});if(!process.argv.includes("--bcod-only")){const py=spawnSync("python3",["validation/gazebo-vehicles/run_gazebo_vehicle_c_closed_loop.py","--world","gazebo/worlds/vehicle-c-azimuth-check.sdf","--output",GAZEBO_TMP],{stdio:"inherit"});if(py.status!==0)throw Error(`Gazebo runner failed with status ${py.status}`);}const gazebo=process.argv.includes("--bcod-only")?{rows:[],outcome:null}:JSON.parse(await readFile(GAZEBO_TMP,"utf8"));
const count=Math.min(node.rows.length,gazebo.rows.length),horizontal=[],yaw=[];for(let i=0;i<count;i++){horizontal.push(Math.hypot(node.rows[i].north_m-gazebo.rows[i].north_m,node.rows[i].east_m-gazebo.rows[i].east_m));yaw.push(Math.abs(Math.atan2(Math.sin(node.rows[i].heading_rad-gazebo.rows[i].heading_rad),Math.cos(node.rows[i].heading_rad-gazebo.rows[i].heading_rad))));}
const original=JSON.parse(await readFile(ORIGINAL,"utf8"));const artifact={schema_version:1,artifact_kind:"vehicle-c-gazebo-closed-loop-comparison",scenario:{seed:SEED,route_ned_m:sc.route_ned_m,initial_position_ned_m:sc.start_ned_m,initial_heading_rad:sc.initial_heading_rad,current_ned_mps:sc.current_ned_mps,wind_ned_mps:sc.wind_ned_mps,terminal_radius_m:TERMINAL_RADIUS},timing:{physics_timestep_s:DT,controller_interval_s:.1,logged_every_physics_step:true},controller:controllerMetadata,physics_mismatch_caveat:PHYSICS_MISMATCH,provenance:{controller:{path:"backends/node/src/vehicle-c-sliding-mode-controller.ts",sha256:await sha("backends/node/src/vehicle-c-sliding-mode-controller.ts")},sdf:{path:"gazebo/models/vehicle-c-azimuth/model.sdf",sha256:await sha("gazebo/models/vehicle-c-azimuth/model.sdf")},parameter_map:{path:"validation/gazebo-vehicles/vehicle-c-parameter-map.json",sha256:await sha("validation/gazebo-vehicles/vehicle-c-parameter-map.json")}},field_notes:{coordinates:"Both arrays are task-frame NED coordinates with the identical seed-30013 origin; Gazebo ENU/body-FLU odometry is converted by gazeboOdomToTask before logging.",allocator:"saturation_scale in both arrays describes the TypeScript minimum-norm command allocation. Gazebo exposes no equivalent degradation field, so its per-step degradation is explicitly null; bcod-sim reports its native allocation degradation.",gazebo_actuator_limit:"Corrected SDF limits are -670.2530375080305 N reverse and 1340.506075016061 N forward per pod, matching vehicle-c-production.ts and vehicle-c-parameter-map.json."},bcod_sim:{outcome:node.outcome,trajectory:node.rows.map(strip)},gazebo_harmonic:{outcome:gazebo.outcome,trajectory:gazebo.rows.map(strip)},comparison:count?{matched_steps:count,horizontal_divergence_m:stats(horizontal),yaw_divergence_rad:stats(yaw),endpoint_transition_note:"Inspect the full-resolution sibling arrays around waypoint_index changes; summary statistics do not replace the raw trace.",allocator_saturation_fraction:{bcod_sim:node.rows.filter((x:any)=>x.saturation_scale<1-1e-12).length/node.rows.length,gazebo_harmonic:gazebo.rows.filter((x:any)=>x.saturation_scale<1-1e-12).length/gazebo.rows.length}}:null,original_thrust_mismatched_baseline:{artifact:ORIGINAL,gazebo_outcome:original.gazebo_harmonic.outcome,comparison:original.comparison}};await writeFile(OUTPUT,JSON.stringify(artifact,null,2)+"\n");if(!process.argv.includes("--bcod-only"))await unlink(GAZEBO_TMP);console.log(JSON.stringify({output:OUTPUT,bcod_sim:node.outcome,gazebo_harmonic:gazebo.outcome,comparison:artifact.comparison,original:artifact.original_thrust_mismatched_baseline},null,2));
