import {createInterface} from "node:readline";
import {DT,HOLD,MAX_STEPS,TERMINAL_RADIUS,geometry,makeControl,scenario} from "./vehicle_c_closed_loop_shared.ts";
import {gazeboOdomToTask} from "../rl-campaign/ports/task-trace-bridge.ts";

const sc=scenario(),run={waypoint:0,scenario:sc},control=makeControl();let last:any=null,step=0,closest=Infinity,done=false,success=false;
function stateFrom(enu?:any){if(!enu)return{position_ned_m:[...sc.start_ned_m,0],attitude_rad:[0,0,sc.initial_heading_rad],velocity_body_mps:[0,0,0],angular_rate_body_rad_s:[0,0,0]};const x=gazeboOdomToTask(step*DT,enu);return{position_ned_m:[sc.start_ned_m[0]+x.N_m,sc.start_ned_m[1]+x.E_m,0],attitude_rad:[0,0,x.yaw_rad],velocity_body_mps:[x.u_mps,x.v_mps,0],angular_rate_body_rad_s:[0,0,x.r_rad_s]};}
function respond(enu?:any){const state=stateFrom(enu),g=geometry(run,state);if(step>0&&run.waypoint<sc.route_ned_m.length-1&&(g.distance<=6||g.passed))run.waypoint++;const active=geometry(run,state),final=sc.route_ned_m.at(-1)!;if(run.waypoint===sc.route_ned_m.length-1){closest=Math.min(closest,Math.hypot(final[0]-state.position_ned_m[0],final[1]-state.position_ned_m[1]));if(closest<=TERMINAL_RADIUS){done=true;success=true;}}
  if(!done&&step<MAX_STEPS&&(step%HOLD===0||!last)){last=control.command(state,{north_m:active.b[0],east_m:active.b[1],heading_rad:active.heading,waypoint_index:run.waypoint},sc.current_ned_mps);control.controller.noteAllocationSaturated(last.allocation.saturation_scale<1-1e-12);}
  const row={step,time_s:step*DT,north_m:state.position_ned_m[0],east_m:state.position_ned_m[1],heading_rad:state.attitude_rad[2],distance_to_goal_m:Math.hypot(final[0]-state.position_ned_m[0],final[1]-state.position_ned_m[1]),surge_mps:state.velocity_body_mps[0],yaw_rate_rad_s:state.angular_rate_body_rad_s[2],waypoint_index:run.waypoint,port_thrust_n:last?.port.thrust??0,port_azimuth_rad:last?.port.azimuth??0,starboard_thrust_n:last?.starboard.thrust??0,starboard_azimuth_rad:last?.starboard.azimuth??0,saturation_scale:last?.allocation.saturation_scale??1,degradation:null,done:done||step>=MAX_STEPS,success,closest_approach_m:Number.isFinite(closest)?closest:null};step++;return row;}
const rl=createInterface({input:process.stdin,crlfDelay:Infinity});rl.on("line",line=>{try{const message=JSON.parse(line);process.stdout.write(JSON.stringify(respond(message.enu))+"\n");}catch(error){process.stdout.write(JSON.stringify({error:String(error)})+"\n");}});
