#!/usr/bin/env node
import {createHash} from "node:crypto";
import {mkdir,readFile,readdir,stat,writeFile} from "node:fs/promises";
import path from "node:path";
import {pathToFileURL} from "node:url";
const root=path.resolve("validation/datasets/raw/wpcc-v4"),out=path.resolve("validation/external-references/wpcc/artifacts/wpcc-trajectory-comparison.json"),inventoryPath=path.resolve("validation/datasets/inventories/wpcc-v4.json");
const sha=(value)=>createHash("sha256").update(value).digest("hex");
const csv=(text)=>{const lines=text.trim().split(/\r?\n/),headers=lines.shift().split(",");return lines.map(line=>Object.fromEntries(line.split(",").map((value,index)=>[headers[index],value])));};
const yaml=(text)=>Object.fromEntries(text.trim().split(/\r?\n/).map(line=>{const i=line.indexOf(":");return[line.slice(0,i),Number(line.slice(i+1).trim())];}));
const finite=(value)=>Number.isFinite(Number(value));
export function validateConvention(nomenclature,ship){
  const byItem=Object.fromEntries(nomenclature.map(row=>[row.Item,row]));
  const required={x0:/origo \(lpp\/2\)/i,y0:/origo \(midship\)/i,z0:/origo \(WL\)/i};
  for(const [name,pattern] of Object.entries(required))if(!pattern.test(byItem[name]?.Description??""))throw new Error(`wPCC v4 reference point unconfirmed: ${name} does not identify the midship/waterline origin`);
  for(const axis of ["x","y","z"])for(const index of [1,2,3]){const key=`accelerometer${index}_${axis}`;if(key in ship&&!finite(ship[key]))throw new Error(`Invalid accelerometer position ${key}`);}
  if(!finite(ship.L)||!finite(ship.x_G)||ship.x_G===0)throw new Error("ship_data.yml cannot distinguish the measurement origin from CG");
  return{confirmed:true,motion_reference_point:"[Lpp/2, 0, WL]",axes:{x:"forward",y:"starboard",z:"into-water"},cg_offset_m:[ship.x_G,0,0]};
}
function unwrap(values){const out=[values[0]];for(let i=1;i<values.length;i++){let d=values[i]-values[i-1];while(d>Math.PI)d-=2*Math.PI;while(d<-Math.PI)d+=2*Math.PI;out.push(out[i-1]+d);}return out;}
function overshoots(samples,angleDeg){
  const psi=unwrap(samples.map(row=>Number(row.psi))),delta=samples.map(row=>Number(row.delta)),base=psi[0],angle=angleDeg*Math.PI/180;
  const firstCommand=delta.find(value=>Math.abs(value)>1e-5)??0,sign=Math.sign(firstCommand)||1;
  const crossing=(start,target)=>{for(let i=start+1;i<psi.length;i++)if((psi[i-1]-target)*(psi[i]-target)<=0)return i;return-1;};
  const firstCross=crossing(0,base+sign*angle);if(firstCross<0)return{first_overshoot_deg:null,second_overshoot_deg:null,reason:"first heading execute not reached"};
  const oppositeCross=crossing(firstCross,base-sign*angle);const firstWindow=psi.slice(firstCross,oppositeCross<0?psi.length:oppositeCross),firstExtreme=sign>0?Math.max(...firstWindow):Math.min(...firstWindow);
  if(oppositeCross<0)return{first_overshoot_deg:Math.max(0,(Math.abs(firstExtreme-base)-angle)*180/Math.PI),second_overshoot_deg:null,reason:"second heading execute not reached"};
  const thirdCross=crossing(oppositeCross,base+sign*angle),secondWindow=psi.slice(oppositeCross,thirdCross<0?psi.length:thirdCross),secondExtreme=sign>0?Math.min(...secondWindow):Math.max(...secondWindow);
  return{first_overshoot_deg:Math.max(0,(Math.abs(firstExtreme-base)-angle)*180/Math.PI),second_overshoot_deg:Math.max(0,(Math.abs(secondExtreme-base)-angle)*180/Math.PI),reason:null};
}
export async function run(){
  const shipText=await readFile(path.join(root,"ship_data.yml"),"utf8").catch(()=>{throw new Error("wPCC v4 cache absent: run node validation/external-references/wpcc/fetch.mjs or extract the supplied archive");});
  const ship=yaml(shipText),nomenclature=csv(await readFile(path.join(root,"nomenclature.csv"),"utf8")),convention=validateConvention(nomenclature,ship),meta=csv(await readFile(path.join(root,"runs_meta_data.csv"),"utf8"));
  const files=(await readdir(path.join(root,"model tests"))).filter(name=>name.endsWith(".csv")).sort(),runs=[];
  for(const name of files){const id=path.basename(name,".csv"),bytes=await readFile(path.join(root,"model tests",name)),rows=csv(bytes.toString()),info=meta.find(row=>Object.values(row)[0]===id);if(!info)throw new Error(`Missing run metadata for ${id}`);const headers=Object.keys(rows[0]);for(const channel of ["time","x0","y0","psi","Hull/Acc/X1","Hull/Acc/Y1","Hull/Acc/Y2","Hull/Acc/Z1","Hull/Acc/Z2","Hull/Acc/Z3","Prop/PS/Rpm","Prop/SB/Rpm","delta"])if(!headers.includes(channel))throw new Error(`${id}: required measured/control channel missing: ${channel}`);
    const isManeuver=info.test_type==="zigzag",powered=rows.some(row=>Math.abs(Number(row["Prop/PS/Rpm"]))>0.1&&Math.abs(Number(row["Prop/SB/Rpm"]))>0.1),hasSailActuation=headers.some(header=>/^Fan\//i.test(header)),accepted=isManeuver&&powered&&!hasSailActuation;
    runs.push({id,source_file:`model tests/${name}`,source_checksum_sha256:sha(bytes),samples:rows.length,duration_s:Number(rows.at(-1).time)-Number(rows[0].time),test_type:info.test_type||"reference-speed",comment:info.comment,propulsion_mode:powered&&!hasSailActuation?"motoring":"excluded-unresolved-or-sail-assisted",mode_evidence:{both_propellers_powered:powered,sail_actuator_channels_present:hasSailActuation,wind_course_channels_present:headers.some(header=>/^Wind\//i.test(header)),note:"Wind/Course metadata alone is not a sail-force actuator; Fan/* channels are treated as sail/wind-assist actuation evidence."},gate_included:accepted,exclusion_reason:accepted?null:(!isManeuver?"reference-speed calibration run; not a maneuver comparison":hasSailActuation?"fan/wind-assist actuator channel present":"powered motoring mode not confirmed"),measured_channels:{position:["x0","y0"],orientation:["roll","pitch","psi"],accelerometers:headers.filter(header=>header.startsWith("Hull/Acc/"))},velocity_channels:{present:headers.filter(header=>["u","v","r"].includes(header)),role:"diagnostic-only",provenance:"EKF-derived/model-conditioned; never gating"},imo_metrics:isManeuver?{advance_m:null,transfer_m:null,tactical_diameter_m:null,unavailable_reason:"Dataset contains zig-zag runs only; turning-circle metrics cannot be extracted.",...overshoots(rows,Number(info.angle1))}:null});
  }
  const lock=await readFile("validation/datasets/locks/wpcc-v4.sha256","utf8"),inventory=[];for(const line of lock.trim().split("\n")){const [,digest,relative]=/^([a-f0-9]{64})  (.+)$/.exec(line)??[];if(!digest)throw new Error(`Invalid lock line: ${line}`);const size=(await stat(path.join(root,relative))).size;inventory.push({path:relative,sha256:digest,size_bytes:size});}
  const particulars={Lpp_m:ship.L,beam_m:ship.B,draft_m:ship.T,mass_kg:ship.m,displacement_m3:ship.volume,block_coefficient:ship.CB,yaw_inertia_kg_m2:ship.I_z,propeller_count:ship.n_prop,propeller_diameter_m:ship.D,rudder_area_each_m2:ship.A_R,cg_x_from_midship_m:ship.x_G,accelerometers:[1,2,3].map(index=>({id:index,position_from_midship_wl_m:[ship[`accelerometer${index}_x`],ship[`accelerometer${index}_y`],ship[`accelerometer${index}_z`]]}))};
  const artifact={schema_version:1,artifact_kind:"wpcc-trajectory-comparison",status:"architecture-variant-reference",dataset:{doi:"10.17632/j5zdrhr9bf.4",version:4,license:"CC-BY-4.0",lock_checksum_sha256:sha(lock)},convention,source_vessel:{id:"wPCC",architecture:"twin-screw twin-rudder",principal_particulars:particulars,provenance:"ship_data.yml; checksum locked; never transferred into Vehicle B USV parameters"},channel_policy:{gating:"measured position, heading, and accelerometers",diagnostic_only:"EKF-derived/model-conditioned velocity channels",velocity_channels_gate:false},mode_inventory:{accepted_run_ids:runs.filter(r=>r.gate_included).map(r=>r.id),excluded:runs.filter(r=>!r.gate_included).map(({id,exclusion_reason})=>({id,reason:exclusion_reason}))},runs,evidence_tiers:["kvlcc2-mmg-reference-reproduction","kvlcc2-experimental-maneuver-indices","kvlcc2-marin-trajectory-comparison","wpcc-trajectory-comparison"],parameterization:{required:"wPCC-specific twin-screw model",transfer_to_vehicle_b_usv_permitted:false},claim_limit:"Raw measured free-running trajectory evidence for propeller/rudder maneuvering-model structure in a twin-screw architecture variant. It does not validate Vehicle B's single-screw configuration or USV-scale coefficients.",comparison_state:"reference-ingested; simulator-side wPCC twin-screw parameterization required before numerical gating"};
  await mkdir(path.dirname(out),{recursive:true});await writeFile(out,`${JSON.stringify(artifact,null,2)}\n`);await writeFile(inventoryPath,`${JSON.stringify({schemaVersion:1,datasetId:"wpcc-v4",archive_sha256:"826d3be77b909535dde530c1b37db8e5cdca694b88cde4e6f893debd92d4b781",files:inventory},null,2)}\n`);console.log(`wPCC v4: ${runs.length} runs inventoried, ${artifact.mode_inventory.accepted_run_ids.length} motoring maneuvers accepted`);
}
if(import.meta.url===pathToFileURL(process.argv[1]).href)run().catch(error=>{console.error(error.message);process.exitCode=1;});
