import {createHash} from "node:crypto";
import {mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {dirname,resolve} from "node:path";
import {fileURLToPath} from "node:url";
import {VehicleParameters} from "../../core/vehicleParameters.js";
import {CoupledSixPlant} from "../../core/coupledSixPlant.js";
import {RigidBodyState} from "../../core/rigidBodyState.js";
import {VEHICLES} from "../../packages/vehicle-sdk/src/index.ts";
import {runAero4RiverProtocol,type Coupled6ReferenceRunner} from "../reference/protocols.ts";
import {validateTrajectory,type ReferenceTrajectory,type TrajectorySample} from "../reference/trajectory.ts";

const load=(path:string)=>JSON.parse(readFileSync(path,"utf8"));
const sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
const symmetrize=(matrix:number[][])=>matrix.map((row,i)=>row.map((value,j)=>(value+matrix[j][i])/2));
class AppliedWrench {lastFullWrench=[0,0,0,0,0,0];computeWrench(ctx:any){this.lastFullWrench=[...(ctx.command.appliedWrench??[0,0,0,0,0,0])];return[this.lastFullWrench[0],this.lastFullWrench[1],this.lastFullWrench[5]];}}

function buildVehicleCPlant(){const definition=VEHICLES["vehicle-c-azimuth"],bytes=readFileSync("artifacts/capytaine/vehicle-c-resolved.json"),resolved=JSON.parse(bytes.toString()),runtime=resolved.runtime_parameters,parameters=new VehicleParameters({id:definition.id,vehicleClass:"surface_coupled6",geometry:{...runtime.geometry,height:definition.geometry.draft.value*2},massProps:{...runtime.massProps,cg:{x:0,y:0,z:0}},addedMass:{matrix6:symmetrize(runtime.addedMass.matrix6)},damping:{...runtime.damping},restoring:{waterDensity:1025,gravity:9.80665,waterplaneArea:definition.geometry.length.value*definition.geometry.width.value,displacementVolume:definition.mass.value/1025,metacentricHeightRoll:definition.hydrostatics!.gm_transverse.value,metacentricHeightPitch:definition.hydrostatics!.gm_longitudinal.value,hydrostaticStiffnessMatrix6:runtime.restoring.hydrostaticStiffnessMatrix6,cob:{x:0,y:0,z:-definition.geometry.draft.value/2}},actuator:{maxThrust:4000,beam:definition.geometry.width.value},validation:{...definition.validation,production_path:"vehicle-c-coupled6-applied-wrench"}});return{definition,resolved,parameters,hydrodynamics_checksum_sha256:sha(bytes)};}

class VehicleCCoupled6Runner implements Coupled6ReferenceRunner{
  readonly plant="coupled6" as const;readonly constrained_dofs=[] as const;readonly recorded:TrajectorySample[]=[];private state:RigidBodyState;private time:number;private readonly dynamics:CoupledSixPlant;private readonly initial:TrajectorySample;
  constructor(initial:TrajectorySample,parameters:VehicleParameters){this.initial=initial;this.state=RigidBodyState.fromEuler({N:initial.north_m,E:initial.east_m,D:0},0,0,initial.yaw_rad);this.state.velocity={u:initial.u_mps,v:initial.v_mps,w:0};this.state.angularRate={p:0,q:0,r:initial.r_rad_s};this.time=initial.time_s;this.dynamics=new CoupledSixPlant(parameters,[new AppliedWrench()],"rk4");}
  resetHydrostaticEquilibrium(){this.state=RigidBodyState.fromEuler({N:this.initial.north_m,E:this.initial.east_m,D:0},0,0,this.initial.yaw_rad);this.state.velocity={u:this.initial.u_mps,v:this.initial.v_mps,w:0};this.state.angularRate={p:0,q:0,r:this.initial.r_rad_s};this.time=this.initial.time_s;this.recorded.length=0;}
  stepAppliedWrench(wrench:[number,number,number,number,number,number],dt:number){if(dt>0){this.dynamics.step(this.state,{waterV:{x:0,y:0,z:0}},{appliedWrench:wrench},dt,this.time);this.time+=dt;}const e=this.state.eulerAngles,sample:TrajectorySample={time_s:this.time,north_m:this.state.position.N,east_m:this.state.position.E,down_m:this.state.position.D,roll_rad:e.roll,pitch_rad:e.pitch,yaw_rad:e.yaw,u_mps:this.state.velocity.u,v_mps:this.state.velocity.v,w_mps:this.state.velocity.w,p_rad_s:this.state.angularRate.p,q_rad_s:this.state.angularRate.q,r_rad_s:this.state.angularRate.r,input_wrench_body_n_nm:[...wrench]};this.recorded.push(sample);return sample;}
}

export function runCampaign(){const plant=buildVehicleCPlant(),tracks=[];for(let index=1;index<=3;index++){const path=`artifacts/aero4river/imported/validation-track-${index}.json`,bytes=readFileSync(path),reference=JSON.parse(bytes.toString()) as ReferenceTrajectory;validateTrajectory(reference);const runner=new VehicleCCoupled6Runner(reference.samples[0],plant.parameters),comparison=runAero4RiverProtocol(reference,runner);tracks.push({id:`validation-track-${index}`,source_trajectory:{path,checksum_sha256:sha(bytes),samples:reference.samples.length,duration_s:reference.samples.at(-1)!.time_s-reference.samples[0].time_s},execution:{plant:runner.plant,constrained_dofs:runner.constrained_dofs,out_of_plane_dofs_free:true,input_hold:"previous-sample zero-order hold",actual_trace_checksum_sha256:sha(JSON.stringify(runner.recorded))},comparison,actual_samples:runner.recorded});}return{schema_version:1,artifact_kind:"aero4river-vehicle-c-coupled6-campaign",status:"campaign-executed-descriptive-not-vehicle-c-validation",is_vehicle_c_behavioral_validation_evidence:false,protocol_scope:"AERO4River planar applied-wrench trajectories replayed through the unconstrained Vehicle C coupled6 plant and projected to surge/sway/yaw.",vehicle:{id:plant.definition.id,validation_status:plant.definition.validation.status,mass_kg:plant.definition.mass.value,propulsion:"dual water azimuth",hydrodynamics_status:plant.resolved.status,hydrodynamics_checksum_sha256:plant.hydrodynamics_checksum_sha256},reference_vessel:{id:"AERO4River",mass_kg:20.8,propulsion:"four aerial azimuth thrusters",dataset_version:"v1"},coordinate_transform:{id:"aero4river-to-bcod-ned-sname-v1",path:"validation/aero4river/aero4river-coordinate-transform-v1.json",checksum_sha256:sha(readFileSync("validation/aero4river/aero4river-coordinate-transform-v1.json"))},acceptance:{kind:"descriptive-no-post-hoc-tolerance",reason:"The reference vessel and Vehicle C parameterizations differ; numerical agreement cannot validate Vehicle C coefficients."},tracks,claim_limit:"Supports execution of reference-neutral applied-wrench comparison through the actual unconstrained coupled6 plant. It does not validate Vehicle C dynamics, dual-water-azimuth propulsion, or full six-axis behavior.",limitations:["AERO4River is a different 20.8 kg air-propelled vessel; its coefficients are not transferred to Vehicle C.","Only planar source channels are measured; out-of-plane states are stability diagnostics without reference targets.","Vehicle C uses bootstrap Capytaine geometry and empirical viscous damping."]};}
if(process.argv[1]===fileURLToPath(import.meta.url)){const output=resolve(process.argv[2]??"artifacts/aero4river/vehicle-c-campaign.json"),artifact=runCampaign();mkdirSync(dirname(output),{recursive:true});writeFileSync(output,`${JSON.stringify(artifact,null,2)}\n`);console.log(JSON.stringify({output,status:artifact.status,tracks:artifact.tracks.map((track)=>({id:track.id,metrics:track.comparison.metrics,constraints:track.comparison.constraints}))},null,2));}
