import {mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {dirname,resolve} from "node:path";
import {fileURLToPath} from "node:url";
import {scenarios,manifest} from "../../benchmarks/usv-bench-36/manifest.ts";
import {VEHICLES} from "../../packages/vehicle-sdk/src/index.ts";
import {resolveExperiment,type ExperimentV1} from "../../packages/experiment-schema/src/index.ts";
import {LegacyProductionEngine} from "../../backends/node/src/legacy-production-engine.ts";

type Policy="pid"|"mpc"|"ppo";
type Actor={layers:Array<{weight:number[][];bias:number[]}>};
const tanh=(x:number)=>Math.tanh(x),clip=(x:number)=>Math.max(-1,Math.min(1,x));
const layer=(input:number[],spec:Actor["layers"][number],activation=true)=>spec.weight.map((row,index)=>{const value=row.reduce((sum,weight,j)=>sum+weight*input[j],spec.bias[index]);return activation?tanh(value):value;});
const ppo=(state:number[],actor:Actor)=>actor.layers.reduce((value,spec,index)=>layer(value,spec,index<actor.layers.length-1),state).map(clip);
function action(policy:Policy,state:number[],actor:Actor){if(policy==="ppo")return ppo(state,actor);const kp=policy==="pid"?.8:10/(10.05),kd=policy==="pid"?.25:.5;return state.slice(0,6).map((value,index)=>clip(-kp*value-kd*state[index+6]));}
const scales:Record<string,[number,number]>={"vehicle-a-otter":[100,50],"vehicle-b-rudder":[2000,1000],"vehicle-c-azimuth":[800,400]};
function config(scenario:(typeof scenarios)[number],vehicle:string):ExperimentV1{const v=VEHICLES[vehicle],level=scenario.severity.score;return{schema_version:1,experiment:{name:`policy-${scenario.id}-${vehicle}`,seed:scenario.seed,timestep_s:.05,duration_s:5},backend:{type:"node"},vehicle:{preset:vehicle,plant:v.plant},environment:{current_mps:[level*.2,scenario.axis==="environment"?level*.15:0,0],wind_mps:[scenario.axis==="environment"?level*3:0,0,0]},sensors:[{plugin:"gps",enabled:true},{plugin:"imu",enabled:true}],mission:{type:scenario.tags[1],waypoints:[{north_m:10+level*10,east_m:scenario.axis==="maneuvering"?level*5:10}]},metrics:["completion","cross_track_rmse","propulsion_energy"]};}
function runOne(policy:Policy,scenario:(typeof scenarios)[number],vehicle:string,actor:Actor){const resolved=resolveExperiment(config(scenario,vehicle)),target=(resolved.mission.waypoints as any[])[0],engine=new LegacyProductionEngine();let observation=engine.reset(resolved),previous=[0,0,0],initial=0,final=0,energy=0,finite=true,steps=0;try{for(let step=0;step<100;step++){const estimated=observation.estimated_state as any,position=estimated.position_ned_m as number[],heading=estimated.heading_rad as number,dt=.05,velocity=step?[...position.slice(0,2).map((value,index)=>(value-previous[index])/dt),0]:[0,0,0],state=[position[0]-target.north_m,position[1]-target.east_m,position[2],0,0,heading,...velocity,0,0,0],command=action(policy,state,actor),[surge,yaw]=scales[vehicle];if(step===0)initial=Math.hypot(state[0],state[1]);const result=engine.step({active_sensors:["gps","imu"],actuators:{surgeForce:command[0]*surge,yawMoment:command[5]*yaw}});observation=result.observation;previous=[...position];const truth:any=engine.getGroundTruth();final=Math.hypot(truth.position_ned_m[0]-target.north_m,truth.position_ned_m[1]-target.east_m);energy=Number(engine.getMetrics().total_energy??0);finite=finite&&[...truth.position_ned_m,...truth.attitude_rad,...truth.velocity_body_mps,...truth.angular_rate_body_rad_s,energy].every(Number.isFinite);steps++;if(result.terminated||result.truncated)break;}}finally{engine.dispose();}return{scenario_id:scenario.id,axis:scenario.axis,tier:scenario.severity.tier,vehicle_id:vehicle,validation_status:VEHICLES[vehicle].validation.status,policy,seed:scenario.seed,steps,finite,initial_distance_m:initial,final_distance_m:final,progress_m:initial-final,mission_reached:final<2,energy};}
export function run(){const actor=JSON.parse(readFileSync("artifacts/baselines/checkpoints/ppo-actor.json","utf8")) as Actor,rows=[];for(const policy of ["pid","mpc","ppo"] as const)for(const scenario of scenarios)for(const vehicle of manifest.vehicles)rows.push(runOne(policy,scenario,vehicle,actor));const aggregate=(["pid","mpc","ppo"] as const).map((policy)=>{const selected=rows.filter((row)=>row.policy===policy);return{policy,configurations:selected.length,finite_rate:selected.filter((row)=>row.finite).length/selected.length,mean_progress_m:selected.reduce((sum,row)=>sum+row.progress_m,0)/selected.length,mission_reach_rate:selected.filter((row)=>row.mission_reached).length/selected.length};});return{schema_version:1,artifact_kind:"usv-bench-36-policy-software-evaluation",status:rows.length===324&&rows.every((row)=>row.finite)?"passed-policy-software-evaluation-not-physical-validation":"failed",base_scenario_count:36,vehicle_configuration_count:108,policy_configuration_count:324,policies:["pid","mpc","ppo"],ppo_training_artifact:"artifacts/baselines/report.json",validation_scope:Object.fromEntries(manifest.vehicles.map((id)=>[id,VEHICLES[id].validation.status])),aggregate,rows,claim_limit:"This compares conventional policies through the production command-to-plant path over short offline benchmark episodes. Vehicle B/C dynamics remain unvalidated, and no algorithmic novelty is claimed."};}
if(process.argv[1]===fileURLToPath(import.meta.url)){const artifact=run(),output=resolve(process.argv[2]??"artifacts/baselines/usv-bench-policy-report.json");mkdirSync(dirname(output),{recursive:true});writeFileSync(output,`${JSON.stringify(artifact,null,2)}\n`);console.log(JSON.stringify({output,status:artifact.status,policy_configurations:artifact.policy_configuration_count,aggregate:artifact.aggregate},null,2));}
