import {mkdir,writeFile} from "node:fs/promises";
import {LightDomain} from "../../packages/sensor-sdk/src/domains/light.ts";
import {RfDomain} from "../../packages/sensor-sdk/src/domains/rf.ts";
import {CameraPlugin,LidarPlugin,RadarPlugin,renderCameraRgba} from "../../packages/sensor-sdk/src/plugins/remaining.ts";
import {SeededRandom} from "../../packages/core/src/random.ts";
import type {GrantedServices,SampleContext} from "../../packages/sensor-sdk/src/runtime.ts";

const SEED=7319,TARGET_RANGE_M=80,TARGET_BEARING_RAD=0;
const RADAR_BEARINGS=Array.from({length:12},(_,i)=>-.6+i*.1);
const RADAR_RANGES=[210,180,150,120,95,82,80,92,118,148,178,208];
const LIDAR_BEARINGS=Array.from({length:16},(_,i)=>-.75+i*.1);
const conditions={
 clear:{visibility_m:20000,fog_extinction_per_m:0,rain_rate_mm_h:0,illumination_lux:10000,cloud_cover_fraction:0,humidity_fraction:.45,sea_state_beaufort:1,significant_wave_height_m:.2,refractivity_n_units:300,rf_noise_floor_dbm:-105,rf_interference_factor:0},
 fog:{visibility_m:250,fog_extinction_per_m:.012,rain_rate_mm_h:0,illumination_lux:2500,cloud_cover_fraction:.8,humidity_fraction:.45,sea_state_beaufort:1,significant_wave_height_m:.2,refractivity_n_units:300,rf_noise_floor_dbm:-105,rf_interference_factor:0},
 rain:{visibility_m:1500,fog_extinction_per_m:0,rain_rate_mm_h:35,illumination_lux:3500,cloud_cover_fraction:.9,humidity_fraction:.9,sea_state_beaufort:6,significant_wave_height_m:3,refractivity_n_units:330,rf_noise_floor_dbm:-100,rf_interference_factor:.1},
};

function environment(c:any){return()=>({wind_ned_mps:[0,0,0],current_ned_mps:[0,0,0],air_temperature_c:15,pressure_pa:101325,humidity_fraction:c.humidity_fraction,rain_rate_mm_h:c.rain_rate_mm_h,visibility_m:c.visibility_m,fog_extinction_per_m:c.fog_extinction_per_m,illumination_lux:c.illumination_lux,atmosphere:{wind_ned_mps:[0,0,0],air_temperature_c:15,pressure_pa:101325,humidity_fraction:c.humidity_fraction,rain_rate_mm_h:c.rain_rate_mm_h,visibility_m:c.visibility_m,fog_extinction_per_m:c.fog_extinction_per_m,illumination_lux:c.illumination_lux,cloud_cover_fraction:c.cloud_cover_fraction,refractivity_n_units:c.refractivity_n_units},water:{current_ned_mps:[0,0,0],temperature_c:12,salinity_psu:35},surface:{sea_state_beaufort:c.sea_state_beaufort,significant_wave_height_m:c.significant_wave_height_m},electromagnetic:{rf_noise_floor_dbm:c.rf_noise_floor_dbm,rf_interference_factor:c.rf_interference_factor},positioning:{}});}
function sceneRange(bearing:number){if(bearing<=RADAR_BEARINGS[0])return RADAR_RANGES[0];if(bearing>=RADAR_BEARINGS.at(-1)!-1e-12)return RADAR_RANGES.at(-1)!;const u=(bearing-RADAR_BEARINGS[0])/.1,i=Math.min(RADAR_RANGES.length-2,Math.floor(u)),f=u-i;return RADAR_RANGES[i]*(1-f)+RADAR_RANGES[i+1]*f;}
function services(input:any,seed:number):GrantedServices{const rng=new SeededRandom(seed);return{environment:environment(input) as any,seededRng:()=>rng.next(),raycast:(_origin,direction)=>{const bearing=Math.atan2(direction[0],direction[2]),elevation=Math.asin(Math.max(-1,Math.min(1,direction[1]))),distance_m=sceneRange(bearing),nx=bearing/.14,ny=elevation/.14,r2=nx*nx+ny*ny;if(r2<1&&distance_m<100)return{distance_m,color_rgb:[.78,.34,.12],normal:[nx,ny,-Math.sqrt(1-r2)]};if(elevation>.025)return null;return{distance_m,color_rgb:elevation<-.06?[.12,.28,.34]:[.42,.55,.60]};}};}
const context:SampleContext={stepIndex:0,simTimeS:0,lifecycleState:"ACTIVE"};
function samplePlugin(Plugin:new()=>CameraPlugin|LidarPlugin|RadarPlugin,input:any,seed:number){const plugin=new Plugin();plugin.init({},services(input,seed));return plugin.sample(context)!.payload as any;}
function radarDiagnostics(input:any,seed:number){const s=services(input,seed),rng=new SeededRandom(seed),rf=RfDomain.queryEnvironment(s,[0,0,0]),params={frequencyHz:77e9},clutter=RfDomain.primitives.clutterDb(rf);const beams=RADAR_BEARINGS.map((bearing_rad,i)=>{const range_m=RADAR_RANGES[i],transmission_loss_db=RfDomain.primitives.transmissionLossDb(range_m,params,rf),snr_db=130-2*transmission_loss_db-rf.noiseFloorDbm-clutter,detection_probability=RfDomain.primitives.detectionProbability(snr_db),random_draw=rng.next();return{beam_index:i,bearing_rad,range_m,transmission_loss_db,snr_db,detection_probability,random_draw,detected:random_draw<detection_probability};});return{environment:rf,clutter_db:clutter,beams};}
function radarSeedAudit(input:any){const histogram:Record<string,number>={};let total=0,min=Infinity,max=-Infinity;for(let seed=1;seed<=1000;seed++){const hits=samplePlugin(RadarPlugin,input,seed).detections.length;histogram[hits]=(histogram[hits]??0)+1;total+=hits;min=Math.min(min,hits);max=Math.max(max,hits);}return{seed_start:1,seed_end:1000,scan_count:1000,histogram,min_hits:min,max_hits:max,mean_hits:total/1000,zero_hit_fraction:(histogram[0]??0)/1000};}

const weather=[];
for(const [condition,input] of Object.entries(conditions)){
 const s=services(input,SEED),light=LightDomain.queryEnvironment(s,[0,0,0]);
 const cameraPayload=samplePlugin(CameraPlugin,input,SEED),cameraDiagnostic=renderCameraRgba(s,80,60),lidarPayload=samplePlugin(LidarPlugin,input,SEED),radarPayload=samplePlugin(RadarPlugin,input,SEED),diag=radarDiagnostics(input,SEED);
 const cameraValues=Array.from({length:cameraPayload.width*cameraPayload.height},(_,i)=>cameraPayload.rgba[i*4]) as number[];
 const cameraParams={wavelengthNm:550,mode:"passive" as const},lidarParams={wavelengthNm:905,mode:"active" as const};
 const lidarPoints=LIDAR_BEARINGS.map((bearing_rad,i)=>({beam_index:i,bearing_rad,range_m:lidarPayload.ranges_m[i],detected:lidarPayload.ranges_m[i]<lidarPayload.max_range_m-1e-9}));
 weather.push({condition,environment:{light,rf:diag.environment},camera:{payload:cameraPayload,diagnostic_payload:cameraDiagnostic,transmission_at_target:LightDomain.primitives.transmission(TARGET_RANGE_M,cameraParams,light),mean_intensity_0_255:cameraValues.reduce((a,b)=>a+b,0)/cameraValues.length,min_intensity_0_255:Math.min(...cameraValues),max_intensity_0_255:Math.max(...cameraValues)},lidar:{payload:lidarPayload,bearings_rad:LIDAR_BEARINGS,points:lidarPoints,detected_count:lidarPoints.filter(x=>x.detected).length,transmission_at_target:LightDomain.primitives.transmission(TARGET_RANGE_M,lidarParams,light),effective_range_scale:LightDomain.primitives.effectiveRangeScale(lidarParams,light)},radar:{payload:radarPayload,beam_count:12,max_range_m:500,detected_count:radarPayload.detections.length,clutter_db:diag.clutter_db,beams:diag.beams}});
}
const rainAudit=radarSeedAudit(conditions.rain);
const artifact={schema_version:3,artifact_kind:"fig3-production-sensor-extraction",seed:SEED,scene:{vehicle_north_m:0,vehicle_east_m:0,sensor_mount_north_m:1.2,sensor_mount_east_m:0,target_range_m:TARGET_RANGE_M,target_bearing_rad:TARGET_BEARING_RAD,radar_beam_bearings_rad:RADAR_BEARINGS,radar_geometric_ranges_m:RADAR_RANGES,fixed_across_cells:true},weather,radar_seed_audit:{condition:"rain",...rainAudit},capability_audit:{camera:{production_output:"8x6 RGBA8 policy observation from 48 raycasts",diagnostic_output:"native 80x60 RGBA8 figure-only capture from 4800 independent raycasts",policy_observation_unchanged:true,noise_model:false},lidar:{production_output:"16 per-ray ranges; fixed bearings recorded by extractor",miss_encoding:"range equals condition-dependent max_range_m",configurable_sampling:false},radar:{production_output:"detections with range_m, bearing_rad, and snr_db from a fixed 12-beam fan",configurable_sampling:false}},provenance:{extractor:"figures/production/extract_fig3_sensing.ts",sensor_plugins:"packages/sensor-sdk/src/plugins/remaining.ts",light_domain:"packages/sensor-sdk/src/domains/light.ts",rf_domain:"packages/sensor-sdk/src/domains/rf.ts",rng:"packages/core/src/random.ts"}};
await mkdir("artifacts/fig3-sensing",{recursive:true});await writeFile("artifacts/fig3-sensing/manifest.json",JSON.stringify(artifact,null,2)+"\n");
console.log(JSON.stringify({weather:weather.map((x:any)=>({condition:x.condition,camera_mean:x.camera.mean_intensity_0_255,camera_transmission:x.camera.transmission_at_target,lidar_hits:x.lidar.detected_count,lidar_max_range_m:x.lidar.payload.max_range_m,radar_hits:x.radar.detected_count,radar_loss_db:x.radar.beams[6].transmission_loss_db,radar_clutter_db:x.radar.clutter_db})),rain_seed_audit:rainAudit},null,2));
