import assert from"node:assert/strict";
import{DEPTH_SOURCE_PRIORITY,GeographyCoverageService,GeographyResolver,LocalGeographicFrame,coveragePreview,resolveGeographicRegion,type BoundingBoxNed,type DepthSourceAdapter,type DepthSourceCoverage,type EncAdapter,type GeographicRegion,type GeographicRegionInput}from"../src/index.ts";
const origin={latitude_deg:37.8,longitude_deg:-122.4,altitude_m:3},frame=new LocalGeographicFrame(origin,27),point={latitude_deg:37.801,longitude_deg:-122.399,altitude_m:7},ned=frame.wgs84ToNed(point),round=frame.nedToWgs84(ned);assert.ok(Math.abs(round.latitude_deg-point.latitude_deg)<1e-9);assert.ok(Math.abs(round.longitude_deg-point.longitude_deg)<1e-9);assert.ok(Math.abs(round.altitude_m!-7)<1e-5);assert.deepEqual(frame.enuToNed(frame.nedToEnu([1,2,3])),[1,2,3]);assert.ok(ned[2]<0,"Altitude above the origin must be negative down in runtime NED.");assert.throws(()=>new LocalGeographicFrame(origin,181),/heading/);
// Raw ENU and hull/Capytaine z-up are boundary conventions: propagation receives only [north,east,down].
assert.deepEqual(new LocalGeographicFrame(origin).enuToNed([2,1,-3]),[1,2,3]);
const inputs:GeographicRegionInput[]=[{kind:"center_extent",center:origin,extent_north_m:100,extent_east_m:100},{kind:"bounding_box",bounds:{south_deg:37.79,west_deg:-122.41,north_deg:37.81,east_deg:-122.39}},{kind:"polygon",vertices:[origin,{latitude_deg:37.801,longitude_deg:-122.4},{latitude_deg:37.8,longitude_deg:-122.399}]},{kind:"waypoints",waypoints:[origin,point],padding_m:20},{kind:"saved",name:"bay"}],saved={bay:{kind:"center_extent",center:origin,extent_north_m:100,extent_east_m:100}};for(const input of inputs){const r=resolveGeographicRegion(input,saved);assert.ok(r.bounds_ned_m.max_ned_m[0]>r.bounds_ned_m.min_ned_m[0]);}
const region=resolveGeographicRegion(inputs[0]),box=(n0:number,e0:number,n1:number,e1:number):BoundingBoxNed=>({min_ned_m:[n0,e0,-100],max_ned_m:[n1,e1,100]}),provenance=(source:string,date:string,res:number)=>({source,product:`${source}-fixture`,retrieval_date:"2026-08-11",survey_date:date,native_resolution_m:res,coverage:"fixture",checksum_sha256:"a".repeat(64),crs:"EPSG:4326",transformations:["WGS84 geodetic to ECEF to local NED"]});let ehydroDate="2026-07-01",fetches=0;
const adapters:DepthSourceAdapter[]=DEPTH_SOURCE_PRIORITY.map((id,index)=>({id,checkCoverage(_r:GeographicRegion):DepthSourceCoverage[]{const resolution=[.5,1,30,3,450][index],bounds=id==="ehydro"?box(-50,-50,0,50):id==="lidar"?box(0,-50,50,50):undefined,date=id==="ehydro"?ehydroDate:"2025-01-01";return[{source:id,covered:true,nativeResolutionM:resolution,surveyDate:date,tileOrDatasetId:`${id}-tile`,...bounds?{boundsM:bounds}:{},provenance:provenance(id,date,resolution)}];},fetchCell(cell){fetches++;const depth=cell.winningSource==="ehydro"?8:cell.winningSource==="lidar"?4:20;return{water_depth_m:depth,elevation_m:-depth,navigable:true,nearest_shore_m:30};}}));
const enc:EncAdapter={checkCoverage:()=>[{cell_id:"coastal",scale:"coastal",scale_denominator:80000,covered:true,retrieval_date:"2026-08-01",checksum_sha256:"b".repeat(64)},{cell_id:"harbor",scale:"harbor",scale_denominator:10000,covered:true,retrieval_date:"2026-08-01",checksum_sha256:"c".repeat(64)}],fetchFeatures:()=>[{id:"rock",kind:"hazard",bounds_m:box(-20,-2,-18,2),roles:["navigation","collision","sensor_simulation"]}]};
const coverage=new GeographyCoverageService(adapters,enc),report=coverage.checkCoverage(region);assert.equal(report.enc?.cell_id,"harbor");assert.ok(report.bySource.some(x=>x.source==="gebco"&&x.covered));assert.ok(report.cascadeResult.cells.some(x=>x.winningSource==="ehydro"));assert.ok(report.cascadeResult.cells.some(x=>x.winningSource==="lidar"));assert.equal(coveragePreview(coverage,{kind:"saved",name:"bay"},saved).region.input_kind,"center_extent");
const resolver=new GeographyResolver(coverage),resolved=resolver.resolve(region);assert.equal(resolved.query_water_depth([-25,0,0]).water_depth_m,8);assert.equal(resolved.query_water_depth([25,0,0]).water_depth_m,4);assert.equal(resolved.query_elevation([25,0,0]).elevation_m,-4);assert.equal(resolved.query_nearest_shore([25,0,0]),30);assert.equal(resolved.query_chart_feature([-19,0,0])[0].id,"rock");assert.equal(resolved.query_navigability([-19,0,0]).navigable,false);assert.equal(resolved.artifact.mismatches.length,1,"ENC/depth disagreement must be reported with both values.");assert.equal(resolved.artifact.mismatches[0].cascade_depth_m,8);assert.ok((resolved.provenance() as any).cells.every((x:any)=>x.provenance));const before=fetches;ehydroDate="2026-08-01";resolver.resolve(region);assert.ok(fetches>before,"A new pinned survey date must use a distinct cache entry.");
const noData=adapters.map(a=>({...a,checkCoverage:()=>[{source:a.id,covered:false,nativeResolutionM:450,surveyDate:null,tileOrDatasetId:"gap"}]})),gap=new GeographyResolver(new GeographyCoverageService(noData,enc)).resolve(region);assert.ok(gap.artifact.unresolved_cell_ids.length>0);assert.equal(gap.sample({position_ned_m:[0,0,0],time_s:0}).water_depth_m,null,"Unresolved cells must never fabricate depth.");
console.log("Geography region, coverage, cascade, ENC, and cache tests passed.");
