export type Position={latitude_deg:number;longitude_deg:number};
export type VerticalDatum="MLLW"|"MSL"|"NAVD88"|"GEBCO";
export type BathymetryPoint=Position&{elevation_m:number;vertical_datum:VerticalDatum;measured:boolean;uncertainty_m?:number;contributor_id?:string};
export type GebcoPoint=Position&{cell_id:string;elevation_m:number;vertical_datum:VerticalDatum;tid_code:number;tid_source:string};
export type CurrentPoint=Position&{time:string;u_east_mps:number;v_north_mps:number;qc_pass:boolean;site:string;zone?:string;grid_id?:string;dop_x?:number;dop_y?:number;gdop?:number;number_of_sites?:number;number_of_radials?:number;rtofs_mask?:"water"|"land"};
export type DatumTransform={from:VerticalDatum;to:VerticalDatum;offset_m:number;method:string;control_point_error_m?:number};
export type CurrentMatchOptions={distance_tolerance_m:number;time_tolerance_s:number;max_gdop?:number;max_dop_x?:number;max_dop_y?:number;min_sites?:number;min_radials?:number};

export function median(values:number[]):number{if(!values.length)throw new Error("median requires at least one value");const x=[...values].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2;}
export function percentile(values:number[],q:number):number{if(!values.length||q<0||q>1)throw new Error("invalid percentile input");const x=[...values].sort((a,b)=>a-b),p=(x.length-1)*q,l=Math.floor(p),f=p-l;return x[l]+(x[Math.min(l+1,x.length-1)]-x[l])*f;}
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;
export function scalarStats(errors:number[]){if(!errors.length)throw new Error("statistics require at least one matched sample");const absolute=errors.map(Math.abs);return{n:errors.length,bias:mean(errors),mae:mean(absolute),rmse:Math.sqrt(mean(errors.map(x=>x*x))),p95_absolute_error:percentile(absolute,.95)};}
export function wrapDegrees(value:number){return((value+180)%360+360)%360-180;}
const speed=(u:number,v:number)=>Math.hypot(u,v);
const direction=(u:number,v:number)=>Math.atan2(u,v)*180/Math.PI;
export function vectorStats(rows:{model_u:number;model_v:number;reference_u:number;reference_v:number}[]){if(!rows.length)throw new Error("vector statistics require at least one match");const u=rows.map(x=>x.model_u-x.reference_u),v=rows.map(x=>x.model_v-x.reference_v),s=rows.map(x=>speed(x.model_u,x.model_v)-speed(x.reference_u,x.reference_v)),directional=rows.filter(x=>speed(x.model_u,x.model_v)>1e-12&&speed(x.reference_u,x.reference_v)>1e-12),angles=directional.map(x=>wrapDegrees(direction(x.model_u,x.model_v)-direction(x.reference_u,x.reference_v))),radians=angles.map(x=>x*Math.PI/180),mu=mean(rows.map(x=>x.model_u)),mv=mean(rows.map(x=>x.model_v)),ru=mean(rows.map(x=>x.reference_u)),rv=mean(rows.map(x=>x.reference_v)),centered=rows.map(x=>({mu:x.model_u-mu,mv:x.model_v-mv,ru:x.reference_u-ru,rv:x.reference_v-rv})),modelEnergy=centered.reduce((a,x)=>a+x.mu*x.mu+x.mv*x.mv,0),referenceEnergy=centered.reduce((a,x)=>a+x.ru*x.ru+x.rv*x.rv,0),real=centered.reduce((a,x)=>a+x.mu*x.ru+x.mv*x.rv,0),imaginary=centered.reduce((a,x)=>a+x.mu*x.rv-x.mv*x.ru,0),denominator=Math.sqrt(modelEnergy*referenceEnergy);return{n:rows.length,u:scalarStats(u),v:scalarStats(v),speed:scalarStats(s),direction:{n:angles.length,mean_error_deg:angles.length?Math.atan2(mean(radians.map(Math.sin)),mean(radians.map(Math.cos)))*180/Math.PI:null,mae_deg:angles.length?mean(angles.map(Math.abs)):null},complex_correlation:denominator?{magnitude:Math.hypot(real,imaginary)/denominator,phase_deg:Math.atan2(imaginary,real)*180/Math.PI,real:real/denominator,imaginary:imaginary/denominator,definition:"mean-centered complex correlation"}:null};}
export function distanceM(a:Position,b:Position){const r=6371008.8,p1=a.latitude_deg*Math.PI/180,p2=b.latitude_deg*Math.PI/180,dp=p2-p1,dl=(b.longitude_deg-a.longitude_deg)*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*r*Math.asin(Math.sqrt(h));}
export function transformElevation(point:BathymetryPoint,datum:VerticalDatum,transforms:DatumTransform[]):BathymetryPoint{if(point.vertical_datum===datum)return{...point};const t=transforms.find(x=>x.from===point.vertical_datum&&x.to===datum);if(!t||!Number.isFinite(t.offset_m)||!t.method.trim())throw new Error(`No auditable vertical datum transform from ${point.vertical_datum} to ${datum}.`);return{...point,elevation_m:point.elevation_m+t.offset_m,vertical_datum:datum};}
export function aggregateBathymetry(gebco:GebcoPoint[],blueTopo:BathymetryPoint[],cellFor:(p:Position)=>string,transforms:DatumTransform[]){const measured=blueTopo.filter(x=>x.measured),groups=Object.groupBy(measured,x=>cellFor(x)),rows=[] as any[],rejections={interpolated:blueTopo.length-measured.length,no_measured_reference:0};for(const g of gebco){const candidates=groups[g.cell_id]??[];if(!candidates.length){rejections.no_measured_reference++;continue;}const normalized=candidates.map(x=>transformElevation(x,g.vertical_datum,transforms)),reference=median(normalized.map(x=>x.elevation_m)),error=g.elevation_m-reference,uncertainties=normalized.map(x=>x.uncertainty_m).filter(Number.isFinite)as number[];rows.push({cell_id:g.cell_id,tid_code:g.tid_code,tid_source:g.tid_source,gebco_elevation_m:g.elevation_m,reference_median_elevation_m:reference,error_m:error,reference_cells:normalized.length,reference_variance_m2:mean(normalized.map(x=>(x.elevation_m-reference)**2)),reference_uncertainty_m:uncertainties.length?median(uncertainties):null,within_reference_uncertainty:uncertainties.length?Math.abs(error)<=median(uncertainties):null,contributors:[...new Set(normalized.map(x=>x.contributor_id).filter(Boolean))].sort()});}return{rows,rejections};}

export function matchCurrents(model:CurrentPoint[],radar:CurrentPoint[],options:CurrentMatchOptions){
  if(!Number.isFinite(options.distance_tolerance_m)||options.distance_tolerance_m<=0||!Number.isFinite(options.time_tolerance_s)||options.time_tolerance_s<0)throw new Error("Current matching tolerances must be finite and non-negative (distance must be positive).");
  const validModel=model.filter(x=>x.qc_pass&&Number.isFinite(x.u_east_mps)&&Number.isFinite(x.v_north_mps)&&Number.isFinite(Date.parse(x.time))&&x.rtofs_mask!=="land"),rejections={radar_qc_failed:0,radar_invalid_vector_or_time:0,radar_dop_missing:0,radar_dop_exceeded:0,radar_gdop_missing:0,radar_gdop_exceeded:0,radar_sites_missing:0,radar_sites_below_minimum:0,radar_radials_missing:0,radar_radials_below_minimum:0,invalid_model:model.length-validModel.length,no_spatiotemporal_match:0};
  const eligible=radar.filter(x=>{if(!x.qc_pass){rejections.radar_qc_failed++;return false;}if(!Number.isFinite(x.u_east_mps)||!Number.isFinite(x.v_north_mps)||!Number.isFinite(Date.parse(x.time))){rejections.radar_invalid_vector_or_time++;return false;}if((options.max_dop_x!==undefined&&x.dop_x===undefined)||(options.max_dop_y!==undefined&&x.dop_y===undefined)){rejections.radar_dop_missing++;return false;}if((options.max_dop_x!==undefined&&x.dop_x!>options.max_dop_x)||(options.max_dop_y!==undefined&&x.dop_y!>options.max_dop_y)){rejections.radar_dop_exceeded++;return false;}if(options.max_gdop!==undefined&&x.gdop===undefined){rejections.radar_gdop_missing++;return false;}if(options.max_gdop!==undefined&&x.gdop!>options.max_gdop){rejections.radar_gdop_exceeded++;return false;}if(options.min_sites!==undefined&&x.number_of_sites===undefined){rejections.radar_sites_missing++;return false;}if(options.min_sites!==undefined&&x.number_of_sites!<options.min_sites){rejections.radar_sites_below_minimum++;return false;}if(options.min_radials!==undefined&&x.number_of_radials===undefined){rejections.radar_radials_missing++;return false;}if(options.min_radials!==undefined&&x.number_of_radials!<options.min_radials){rejections.radar_radials_below_minimum++;return false;}return true;}),insideMask=eligible.filter(x=>x.rtofs_mask==="land"),candidates=eligible.filter(x=>x.rtofs_mask!=="land"),matches=[]as any[];
  for(const r of candidates){let best:{model:CurrentPoint;distance:number;dt:number;score:number;index:number}|undefined;validModel.forEach((m,index)=>{if(r.site!==m.site)return;const distance=distanceM(m,r),dt=Math.abs(Date.parse(m.time)-Date.parse(r.time))/1000;if(distance>options.distance_tolerance_m||dt>options.time_tolerance_s)return;const score=distance/options.distance_tolerance_m+(options.time_tolerance_s?dt/options.time_tolerance_s:dt?Infinity:0);if(!best||score<best.score||(score===best.score&&index<best.index))best={model:m,distance,dt,score,index};});if(!best){rejections.no_spatiotemporal_match++;continue;}const m=best.model;matches.push({site:r.site,zone:r.zone??m.zone??"unclassified",latitude_deg:r.latitude_deg,longitude_deg:r.longitude_deg,time:r.time,model_time:m.time,model_grid_id:m.grid_id??null,distance_m:best.distance,time_delta_s:best.dt,model_u:m.u_east_mps,model_v:m.v_north_mps,reference_u:r.u_east_mps,reference_v:r.v_north_mps,reference_speed_mps:speed(r.u_east_mps,r.v_north_mps)});}
  const denominator=eligible.length,byZone=Object.fromEntries(Object.entries(Object.groupBy(eligible,x=>x.zone??"unclassified")).map(([zone,rows])=>{const total=rows!.length,absent=rows!.filter(x=>x.rtofs_mask==="land").length;return[zone,{eligible_radar_cell_hours:total,rtofs_absent_cell_hours:absent,rtofs_absent_fraction:total?absent/total:null}];}));
  return{matches,inside_mask:insideMask,rejections,coverage:{eligible_radar_cell_hours:denominator,rtofs_water_cell_hours:denominator-insideMask.length,rtofs_absent_cell_hours:insideMask.length,rtofs_absent_fraction:denominator?insideMask.length/denominator:null,by_zone:byZone}};
}
export function groupMetrics<T>(rows:T[],key:(row:T)=>string,metric:(rows:T[])=>unknown){return Object.fromEntries(Object.entries(Object.groupBy(rows,key)).sort(([a],[b])=>a.localeCompare(b)).map(([name,values])=>[name,metric(values!)]));}
