import {createHash} from "node:crypto";import {mkdirSync,writeFileSync} from "node:fs";import {dirname,resolve} from "node:path";import {fileURLToPath} from "node:url";
import {ActuationModel} from "../../packages/core/src/actuators.js";import {VEHICLES} from "../../packages/vehicle-sdk/src/index.ts";
const sha=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
type Placement={id:string;pos:[number,number,number];azimuth:number};
function model(placements:Placement[]){const vehicle=VEHICLES["vehicle-c-azimuth"];return new ActuationModel({geometry:{beam:vehicle.geometry.width.value},massProps:{cg:{x:0,y:0,z:0}},controlledDOF:["surge","sway","yaw"],allocator:{regularization:1e-5,reachabilityTolerance:1e-5},actuator:{behaviorVersion:"integrated-v1",maxThrust:500,motorTimeConstant:.15,beam:vehicle.geometry.width.value},effectors:placements.map((p)=>({id:p.id,type:"AzimuthThruster",pos:p.pos,axis:[Math.cos(p.azimuth),Math.sin(p.azimuth),0],azimuth:{initial:p.azimuth,tau:.1,rateMax:.5,min:-Math.PI,max:Math.PI},maxForwardThrust:500,maxReverseThrust:250,dynamics:{tau:.15,rateMax:800},conversion:{type:"linear"},behaviorVersion:"integrated-v1"}))});}
const desired=[120,35,50];
function execute(id:string,placements:Placement[],failure?:{id:string;mode:"failed-off"|"stuck"}){
  const actuator:any=model(placements);
  actuator.commandWrench({effectors:Object.fromEntries(placements.map((p)=>[p.id,{command:p.id.endsWith("port")?.35:.2,azimuth:p.azimuth}]))},.1);
  if(failure)actuator.commandWrench({failureStates:{[failure.id]:{mode:failure.mode,source:"vehicle-c-allocation-campaign"}},desiredWrench:desired},.1);else actuator.commandWrench({desiredWrench:desired},.1);
  const checkpoint=JSON.parse(JSON.stringify(actuator.saveState())),expected=actuator.commandWrench({desiredWrench:desired},.1),expectedDiagnostics=structuredClone(actuator.lastAllocationDiagnostics);
  actuator.loadState(checkpoint);const replay=actuator.commandWrench({desiredWrench:desired},.1);const diagnostics=structuredClone(actuator.lastAllocationDiagnostics);
  const finite=[...replay,...diagnostics.achieved_wrench,...diagnostics.residual_wrench,...diagnostics.singular_values].every(Number.isFinite),limits=actuator.effectors.every((e:any)=>Math.abs(e.command??0)<=1&&Math.abs(e.thrust??0)<=500+1e-9),angleContinuity=actuator.effectors.every((e:any)=>Number.isFinite(e.azimuth)&&(!e.stuckState||Math.abs(e.azimuth-e.stuckState.azimuth)<=1e-12)),checkpointReplayExact=JSON.stringify(expected)===JSON.stringify(replay)&&JSON.stringify(expectedDiagnostics)===JSON.stringify(diagnostics);
  return{id,placements,failure:failure??null,diagnostics,finite,limits_respected:limits,angle_continuity:angleContinuity,checkpoint_replay_exact:checkpointReplayExact,passed:finite&&limits&&angleContinuity&&checkpointReplayExact};
}
const base=(port:[number,number,number],starboard:[number,number,number],a=0,b=0):Placement[]=>[{id:"azimuth-port",pos:port,azimuth:a},{id:"azimuth-starboard",pos:starboard,azimuth:b}];
export function runCampaign(){const cases=[execute("both-parallel",base([-1,-.65,0],[-1,.65,0])),execute("through-cg",base([0,0,0],[0,0,0])),execute("coincident-lines",base([-1,0,0],[-1,0,0])),execute("near-parallel-near-cg",base([1e-5,-1e-5,0],[1e-5,1e-5,0],0,1e-6)),...Array.from({length:8},(_,i)=>{const epsilon=10**(-i);return execute(`singularity-sweep-${i}`,base([epsilon,-epsilon,0],[epsilon,epsilon,0],0,epsilon));}),execute("failed-off-port",base([-1,-.65,0],[-1,.65,0],-.35,.35),{id:"azimuth-port",mode:"failed-off"}),execute("stuck-port-nonzero",base([-1,-.65,0],[-1,.65,0],-.35,.35),{id:"azimuth-port",mode:"stuck"})];return{schema_version:1,artifact_kind:"vehicle-c-integrated-allocation-conditioning",status:cases.every((c)=>c.passed)?"passed-control-allocation-composability-only":"failed",is_vehicle_c_behavioral_validation:false,claim:"Control allocation and composability demonstrated; Vehicle C behavioral dynamics remain independently unvalidated.",desired_wrench:desired,cases,summary:{case_count:cases.length,rank_deficient:cases.filter((c)=>c.diagnostics.degradation==="rank-deficient").length,infeasible:cases.filter((c)=>c.diagnostics.degradation==="infeasible"||c.diagnostics.reachable===false).length,artifact_checksum_sha256:sha(cases)},limitations:["Bootstrap geometry and actuator parameters are not physical validation evidence.","This campaign validates the integrated command/allocation/actuator path, not hydrodynamic response."]};}
if(process.argv[1]===fileURLToPath(import.meta.url)){const output=resolve(process.argv[2]??"artifacts/vehicle-c/allocation-conditioning.json"),artifact=runCampaign();mkdirSync(dirname(output),{recursive:true});writeFileSync(output,`${JSON.stringify(artifact,null,2)}\n`);console.log(JSON.stringify({output,status:artifact.status,summary:artifact.summary},null,2));if(!artifact.status.startsWith("passed"))process.exitCode=1;}
