import {toGroupedEnvironmentSample,type EnvironmentSample} from "@bcod/environment";
import type {GrantedServices,Vec3} from "../runtime.ts";
import type {DomainModule,NoiseProfile,UnitConventions} from "./types.ts";

export interface AbsolutePositioningParams{baseHorizontalStdM:number;baseVerticalStdM:number}
export interface AbsolutePositioningEnvironment{skyViewFraction:number;visibleSatellites:number;hdop:number;vdop:number;pdop:number;multipathFactor:number;gnssInterferenceFactor:number;clearFraction:number;blockedFraction:number;available:boolean}
const clamp=(value:number,min=0,max=1)=>Math.min(Math.max(value,min),max);
export const absolutePositioningUnits:UnitConventions={distance:"m",frequency:"Hz",pressure:"Pa",level:"dimensionless",temperature:"degC",salinity:"PSU"};
export const AbsolutePositioningDomain:DomainModule<AbsolutePositioningParams,AbsolutePositioningEnvironment,Record<string,never>>={domain:"ABSOLUTE_POSITIONING",version:"1.0.0",units:absolutePositioningUnits,primitives:{},queryEnvironment(services:GrantedServices,at:Vec3){if(!services.environment||!services.skyOcclusion)throw new Error("Absolute positioning requires environment and sky-occlusion services.");const positioning=toGroupedEnvironmentSample(services.environment(at) as EnvironmentSample).positioning,occlusion=services.skyOcclusion.sample(at),clear=clamp(occlusion.clearFraction),sky=clamp(positioning.sky_view_fraction??1)*clear,visible=Math.max(Math.floor((positioning.visible_satellites??12)*clear),0),coverage=Math.max(sky,.05),multipath=clamp((positioning.multipath_factor??0)+(1-(positioning.multipath_factor??0))*occlusion.blockedFraction*.75),hdop=(positioning.hdop??1)/Math.sqrt(coverage),vdop=(positioning.vdop??1.5)/Math.sqrt(coverage),pdop=(positioning.pdop??Math.hypot(hdop,vdop))/Math.sqrt(coverage),interference=clamp(positioning.gnss_interference_factor??0);return{skyViewFraction:sky,visibleSatellites:visible,hdop:Math.min(hdop,50),vdop:Math.min(vdop,50),pdop:Math.min(pdop,50),multipathFactor:multipath,gnssInterferenceFactor:interference,clearFraction:clear,blockedFraction:occlusion.blockedFraction,available:visible>=4&&sky>=.15&&interference<.98};},defaultNoiseProfile(params){if(params.baseHorizontalStdM<0||params.baseVerticalStdM<0)throw new Error("GPS noise parameters must be non-negative.");return{measurementStd:params.baseHorizontalStdM,biasStd:params.baseHorizontalStdM*.25,driftStdPerSqrtS:0,dropoutProbability:0};}};
