import{toGroupedEnvironmentSample,type EnvironmentSample}from"@bcod/environment";import type{GrantedServices,Vec3}from"../runtime.ts";import type{DomainModule,NoiseProfile}from"./types.ts";
const units={distance:"m",frequency:"Hz",pressure:"Pa",level:"SI",temperature:"degC",salinity:"PSU"},noise:NoiseProfile={measurementStd:.01,biasStd:.002,driftStdPerSqrtS:.0001,dropoutProbability:0};
export const InSituAirDomain:DomainModule<Record<string,never>,ReturnType<typeof air>,Record<string,never>>={domain:"IN_SITU_AIR",version:"1.0.0",units,primitives:{},queryEnvironment(s,at){return air(s,at);},defaultNoiseProfile(){return noise;}};
function air(s:GrantedServices,at:Vec3){if(!s.environment)throw new Error("In-situ air requires environment.");const a=toGroupedEnvironmentSample(s.environment(at)as EnvironmentSample).atmosphere;return{windNedMps:a.wind_ned_mps,gustNedMps:a.gust_ned_mps??[0,0,0]as Vec3,temperatureC:a.air_temperature_c,pressurePa:a.pressure_pa,humidityFraction:a.humidity_fraction,turbulenceIntensity:a.turbulence_intensity??0};}
export const InSituWaterDomain:DomainModule<Record<string,never>,ReturnType<typeof water>,Record<string,never>>={domain:"IN_SITU_WATER",version:"1.0.0",units,primitives:{},queryEnvironment(s,at){return water(s,at);},defaultNoiseProfile(){return noise;}};
function water(s:GrantedServices,at:Vec3){if(!s.environment||!s.bathymetry)throw new Error("In-situ water requires environment and bathymetry.");const w=toGroupedEnvironmentSample(s.environment(at)as EnvironmentSample).water,depth=s.bathymetry.sample({position_ned_m:at,time_s:s.time?.()??0});return{currentNedMps:w.current_ned_mps,temperatureC:w.temperature_c??10,salinityPsu:w.salinity_psu??35,conductivitySM:w.conductivity_s_m??0,turbidityNtu:w.turbidity_ntu??0,dissolvedOxygenMgL:w.dissolved_oxygen_mg_l??0,ph:w.ph??7,waterDepthM:depth.water_depth_m,depthStatus:depth.status??"resolved"};}
export const FieldSensingDomain:DomainModule<Record<string,never>,ReturnType<typeof field>,Record<string,never>>={domain:"FIELD_SENSING",version:"1.0.0",units,primitives:{},queryEnvironment(s,at){return field(s,at);},defaultNoiseProfile(){return{...noise,measurementStd:1e-7};}};
function field(s:GrantedServices,at:Vec3){if(!s.environment)throw new Error("Field sensing requires environment.");const e=toGroupedEnvironmentSample(s.environment(at)as EnvironmentSample).electromagnetic,base=e.magnetic_field_ned_t??[2e-5,0,4e-5],anomaly=e.magnetic_anomaly_ned_t??[0,0,0];return{magneticFieldNedT:base.map((v,i)=>v+anomaly[i])as Vec3,declinationRad:e.magnetic_declination_rad??0,inclinationRad:e.magnetic_inclination_rad??0};}
export const PlatformInternalDomain:DomainModule<Record<string,never>,unknown,Record<string,never>>={domain:"PLATFORM_INTERNAL",version:"1.0.0",units,primitives:{},queryEnvironment(s){if(!s.platformState)throw new Error("Platform domain requires platform state.");return s.platformState.sample();},defaultNoiseProfile(){return noise;}};
export const DerivedDomain:DomainModule<Record<string,never>,{inputIds:string[]},Record<string,never>>={domain:"DERIVED",version:"1.0.0",units,primitives:{},queryEnvironment(){return{inputIds:[]};},defaultNoiseProfile(){return noise;}};
