import type {GrantedServices,SampleContext,SensorPlugin,SensorPluginMetadata,SensorPluginStateDTO,SensorSample,Vec3} from "../runtime.ts";

export interface FanRangefinderConfig {ray_count?:number;field_of_view_rad?:number;max_range_m?:number;mount_m?:Vec3}
export interface FanRangefinderOutput {bearings_rad:number[];ranges_m:number[];hit_mask:boolean[];max_range_m:number}
type RayHit={distance_m:number}|null;

const defaults:Required<FanRangefinderConfig>={ray_count:9,field_of_view_rad:Math.PI/2,max_range_m:80,mount_m:[0,0,0]};
export class FanRangefinderPlugin implements SensorPlugin {
  readonly metadata:SensorPluginMetadata={id:"fan-rangefinder",version:"1.0.0",domain:"LIGHT",domainParams:{mode:"active-geometric",geometry:"horizontal-fan"},configSchema:{type:"object",properties:{ray_count:{type:"number",minimum:1},field_of_view_rad:{type:"number",minimum:0},max_range_m:{type:"number",exclusiveMinimum:0},mount_m:{type:"array",minItems:3,maxItems:3}}},outputSchema:{type:"object",properties:{bearings_rad:{type:"array"},ranges_m:{type:"array"},hit_mask:{type:"array"},max_range_m:{type:"number"}}},requiredServices:["raycast"],nominalRateHz:10,nominalLatencyS:0,nominalPowerW:1.5,nominalBandwidthBps:2048,outputPayloadClass:"lidar"};
  #services?:GrantedServices;#config:Required<FanRangefinderConfig>=defaults;#sampleCount=0;
  init(config:unknown,services:GrantedServices):void{const value={...defaults,...structuredClone((config??{}) as FanRangefinderConfig)};if(!services.raycast||!Number.isInteger(value.ray_count)||value.ray_count<1||!Number.isFinite(value.field_of_view_rad)||value.field_of_view_rad<0||value.field_of_view_rad>2*Math.PI||!Number.isFinite(value.max_range_m)||value.max_range_m<=0||!Array.isArray(value.mount_m)||value.mount_m.length!==3||value.mount_m.some(v=>!Number.isFinite(v)))throw new Error("Invalid fan rangefinder configuration or services.");this.#services=services;this.#config=value;this.reset();}
  sample(context:SampleContext):SensorSample<FanRangefinderOutput>|null{if(!this.#services)throw new Error("Fan rangefinder is not initialized.");if(context.lifecycleState!=="ACTIVE"&&context.lifecycleState!=="DEGRADED")return null;const bearings:number[]=[],ranges:number[]=[],hitMask:boolean[]=[];for(let i=0;i<this.#config.ray_count;i++){const fraction=this.#config.ray_count===1?.5:i/(this.#config.ray_count-1),bearing=(fraction-.5)*this.#config.field_of_view_rad,direction:[number,number,number]=[Math.cos(bearing),Math.sin(bearing),0],hit=this.#services.raycast!(this.#config.mount_m,direction,this.#config.max_range_m) as RayHit,distance=hit&&Number.isFinite(hit.distance_m)?Math.max(0,Math.min(this.#config.max_range_m,hit.distance_m)):this.#config.max_range_m;bearings.push(bearing);ranges.push(distance);hitMask.push(Boolean(hit&&hit.distance_m<=this.#config.max_range_m));}this.#sampleCount++;return{stepIndex:context.stepIndex,timestampS:context.simTimeS,valid:true,status:context.lifecycleState,payload:{bearings_rad:bearings,ranges_m:ranges,hit_mask:hitMask,max_range_m:this.#config.max_range_m},powerW:this.metadata.nominalPowerW,bytes:this.#config.ray_count*17+8};}
  reset():void{this.#sampleCount=0;}
  saveState():SensorPluginStateDTO{return{schema_version:1,plugin_id:this.metadata.id,plugin_version:this.metadata.version,state:{sample_count:this.#sampleCount}};}
  validateState(state:SensorPluginStateDTO):void{if(state?.schema_version!==1||state.plugin_id!==this.metadata.id||state.plugin_version!==this.metadata.version||!Number.isInteger(state.state?.sample_count))throw new Error("Invalid fan rangefinder state.");}
  loadState(state:SensorPluginStateDTO):void{this.validateState(state);this.#sampleCount=state.state.sample_count as number;}
  dispose():void{this.#services=undefined;this.#config=defaults;this.reset();}
}
