import {AbsolutePositioningDomain} from "../domains/absolute-positioning.ts";
import {GaussianNoise} from "./noise.ts";
import type {GrantedServices,SampleContext,SensorPlugin,SensorPluginMetadata,SensorPluginStateDTO,SensorSample,Vec3} from "../runtime.ts";

export interface GpsConfig{mount_m?:Vec3;rate_hz?:number;latency_s?:number;base_horizontal_std_m?:number;base_vertical_std_m?:number;velocity_std_mps?:number}
export interface GpsOutput{position_ned_m:Vec3;velocity_ned_mps:Vec3;hdop:number;vdop:number;pdop:number;visible_satellites:number;sky_view_fraction:number;multipath_factor:number}
interface Pending{deliveryTimeS:number;sample:SensorSample<GpsOutput|null>}
interface Truth{position_ned_m:number[];velocity_body_mps?:number[];velocity_ned_mps?:number[]}
const defaults:Required<GpsConfig>={mount_m:[0,0,-.8],rate_hz:2,latency_s:.2,base_horizontal_std_m:.8,base_vertical_std_m:1.5,velocity_std_mps:.08};
export class GpsPlugin implements SensorPlugin{
  readonly metadata:SensorPluginMetadata={id:"gps",version:"1.0.0",domain:"ABSOLUTE_POSITIONING",domainParams:{mode:"GNSS_ABSOLUTE_FIX"},configSchema:{type:"object"},outputSchema:{type:["object","null"]},requiredServices:["seededRng","groundTruth","environment","skyOcclusion"],nominalRateHz:2,nominalLatencyS:.2,nominalPowerW:.25,nominalBandwidthBps:640};
  #config:Required<GpsConfig>=defaults;#services?:GrantedServices;#nextMeasurementTimeS=0;#queue:Pending[]=[];#noise=new GaussianNoise();#sampleCount=0;
  init(config:unknown,services:GrantedServices):void{const value={...defaults,...structuredClone((config??{}) as GpsConfig)};if(!services.seededRng||!services.groundTruth||!services.environment||!services.skyOcclusion||value.rate_hz<=0||value.latency_s<0||value.base_horizontal_std_m<0||value.base_vertical_std_m<0)throw new Error("Invalid GPS configuration or services.");this.#config=value;this.#services=services;this.reset();}
  sample(context:SampleContext):SensorSample<GpsOutput|null>|null{if(!this.#services)throw new Error("GPS is not initialized.");if(context.lifecycleState!=="ACTIVE"&&context.lifecycleState!=="DEGRADED")return null;if(context.simTimeS+1e-12>=this.#nextMeasurementTimeS){this.#queue.push({deliveryTimeS:context.simTimeS+this.#config.latency_s,sample:this.#measure(context)});this.#sampleCount++;this.#nextMeasurementTimeS=(this.#sampleCount)/this.#config.rate_hz;}if(this.#queue.length&&this.#queue[0].deliveryTimeS<=context.simTimeS+1e-12)return this.#queue.shift()!.sample;return null;}
  #measure(context:SampleContext):SensorSample<GpsOutput|null>{const truth=this.#services!.groundTruth!() as Truth,environment=AbsolutePositioningDomain.queryEnvironment(this.#services!,this.#config.mount_m),base={stepIndex:context.stepIndex,timestampS:context.simTimeS,status:environment.available&&environment.skyViewFraction>.5?context.lifecycleState:"DEGRADED" as const,powerW:this.metadata.nominalPowerW,bytes:80},random=this.#services!.seededRng!;if(!environment.available||random()<environment.gnssInterferenceFactor)return{...base,valid:false,payload:null};const horizontal=this.#config.base_horizontal_std_m*environment.hdop*(1+2*environment.multipathFactor),vertical=this.#config.base_vertical_std_m*environment.vdop*(1+2*environment.multipathFactor),position=truth.position_ned_m,velocity=truth.velocity_ned_mps??truth.velocity_body_mps??[0,0,0],n=()=>this.#noise.next(random);return{...base,valid:true,payload:{position_ned_m:[position[0]+n()*horizontal,position[1]+n()*horizontal,position[2]+n()*vertical],velocity_ned_mps:[velocity[0]+n()*this.#config.velocity_std_mps,velocity[1]+n()*this.#config.velocity_std_mps,velocity[2]+n()*this.#config.velocity_std_mps],hdop:environment.hdop,vdop:environment.vdop,pdop:environment.pdop,visible_satellites:environment.visibleSatellites,sky_view_fraction:environment.skyViewFraction,multipath_factor:environment.multipathFactor}};}
  reset():void{this.#nextMeasurementTimeS=0;this.#queue=[];this.#noise.spare=null;this.#sampleCount=0;}
  saveState():SensorPluginStateDTO{return{schema_version:1,plugin_id:this.metadata.id,plugin_version:this.metadata.version,state:{next_measurement_time_s:this.#nextMeasurementTimeS,sample_count:this.#sampleCount,gaussian_spare:this.#noise.spare,latency_queue:structuredClone(this.#queue) as any}};}
  validateState(state:SensorPluginStateDTO):void{const value=state?.state;if(state?.schema_version!==1||state.plugin_id!==this.metadata.id||state.plugin_version!==this.metadata.version||!Number.isFinite(value?.next_measurement_time_s)||!Number.isInteger(value?.sample_count)||!Array.isArray(value?.latency_queue)||(value.gaussian_spare!==null&&!Number.isFinite(value.gaussian_spare)))throw new Error("Invalid GPS checkpoint state.");}
  loadState(state:SensorPluginStateDTO):void{this.validateState(state);this.#nextMeasurementTimeS=state.state.next_measurement_time_s as number;this.#sampleCount=state.state.sample_count as number;this.#noise.spare=state.state.gaussian_spare as number|null;this.#queue=structuredClone(state.state.latency_queue) as unknown as Pending[];}
  dispose():void{this.#services=undefined;this.reset();}
}
