import {RelativePositioningDomain} from "../domains/relative-positioning.ts";
import {GaussianNoise} from "./noise.ts";
import type {GrantedServices,SampleContext,SensorPlugin,SensorPluginMetadata,SensorPluginStateDTO,SensorSample,Vec3} from "../runtime.ts";

export interface ImuConfig{mount_m?:Vec3;rate_hz?:number;latency_s?:number;accel_noise_std_mps2?:number;gyro_noise_std_rad_s?:number;accel_bias_std_mps2?:number;gyro_bias_std_rad_s?:number;accel_drift_std_per_sqrt_s?:number;gyro_drift_std_per_sqrt_s?:number;accel_vibration_sensitivity?:number;gyro_vibration_sensitivity?:number}
export interface ImuOutput{acceleration_body_mps2:Vec3;angular_rate_body_rad_s:Vec3;orientation_rad:Vec3;accel_bias_mps2:Vec3;gyro_bias_rad_s:Vec3;vibration_rms_mps2:number;accel_noise_std_mps2:number;gyro_noise_std_rad_s:number}
interface Pending{deliveryTimeS:number;sample:SensorSample<ImuOutput>}
interface Truth{acceleration_body_mps2?:number[];angular_rate_body_rad_s:number[];attitude_rad:number[]}
const defaults:Required<ImuConfig>={mount_m:[0,0,0],rate_hz:50,latency_s:.01,accel_noise_std_mps2:.015,gyro_noise_std_rad_s:.0008,accel_bias_std_mps2:.02,gyro_bias_std_rad_s:.001,accel_drift_std_per_sqrt_s:.002,gyro_drift_std_per_sqrt_s:.0001,accel_vibration_sensitivity:.08,gyro_vibration_sensitivity:.004};
export class ImuPlugin implements SensorPlugin{
  readonly metadata:SensorPluginMetadata={id:"imu",version:"1.1.0",domain:"RELATIVE_POSITIONING",domainParams:{mode:"STRAPDOWN_INERTIAL"},configSchema:{type:"object"},outputSchema:{type:"object"},requiredServices:["seededRng","groundTruth","platformState"],nominalRateHz:50,nominalLatencyS:.01,nominalPowerW:.1,nominalBandwidthBps:3200};
  #config:Required<ImuConfig>=defaults;#services?:GrantedServices;#nextMeasurementTimeS=0;#lastMeasurementTimeS:number|null=null;#queue:Pending[]=[];#noise=new GaussianNoise();#sampleCount=0;#accelBias:Vec3=[0,0,0];#gyroBias:Vec3=[0,0,0];
  init(config:unknown,services:GrantedServices):void{const value={...defaults,...structuredClone((config??{}) as ImuConfig)};if(!services.seededRng||!services.groundTruth||!services.platformState||value.rate_hz<=0||value.latency_s<0||[value.accel_vibration_sensitivity,value.gyro_vibration_sensitivity].some(x=>!Number.isFinite(x)||x<0))throw new Error("Invalid IMU configuration or services.");this.#config=value;this.#services=services;this.reset();const random=services.seededRng;this.#accelBias=this.#accelBias.map(()=>this.#noise.next(random)*value.accel_bias_std_mps2) as Vec3;this.#gyroBias=this.#gyroBias.map(()=>this.#noise.next(random)*value.gyro_bias_std_rad_s) as Vec3;}
  sample(context:SampleContext):SensorSample<ImuOutput>|null{if(!this.#services)throw new Error("IMU is not initialized.");if(context.lifecycleState!=="ACTIVE"&&context.lifecycleState!=="DEGRADED")return null;if(context.simTimeS+1e-12>=this.#nextMeasurementTimeS){this.#queue.push({deliveryTimeS:context.simTimeS+this.#config.latency_s,sample:this.#measure(context)});this.#sampleCount++;this.#nextMeasurementTimeS=this.#sampleCount/this.#config.rate_hz;}if(this.#queue.length&&this.#queue[0].deliveryTimeS<=context.simTimeS+1e-12)return this.#queue.shift()!.sample;return null;}
  #measure(context:SampleContext):SensorSample<ImuOutput>{const random=this.#services!.seededRng!,truth=this.#services!.groundTruth!() as Truth,environment=RelativePositioningDomain.queryEnvironment(this.#services!,this.#config.mount_m),dt=this.#lastMeasurementTimeS===null?1/this.#config.rate_hz:Math.max(context.simTimeS-this.#lastMeasurementTimeS,0);this.#lastMeasurementTimeS=context.simTimeS;const accelNoiseStd=Math.hypot(this.#config.accel_noise_std_mps2,environment.vibrationRmsMps2*this.#config.accel_vibration_sensitivity),gyroNoiseStd=Math.hypot(this.#config.gyro_noise_std_rad_s,environment.vibrationRmsMps2*this.#config.gyro_vibration_sensitivity),temperatureScale=environment.componentTemperatureC===null?1:1+Math.abs(environment.componentTemperatureC-20)*.005,n=()=>this.#noise.next(random);for(let axis=0;axis<3;axis++){this.#accelBias[axis]+=n()*this.#config.accel_drift_std_per_sqrt_s*Math.sqrt(dt)*temperatureScale;this.#gyroBias[axis]+=n()*this.#config.gyro_drift_std_per_sqrt_s*Math.sqrt(dt)*temperatureScale;}const acceleration=truth.acceleration_body_mps2??[0,0,0],angular=truth.angular_rate_body_rad_s??[0,0,0],attitude=truth.attitude_rad??[0,0,0];return{stepIndex:context.stepIndex,timestampS:context.simTimeS,valid:true,status:context.lifecycleState,powerW:this.metadata.nominalPowerW,bytes:120,payload:{acceleration_body_mps2:acceleration.map((value,index)=>value+this.#accelBias[index]+n()*accelNoiseStd) as Vec3,angular_rate_body_rad_s:angular.map((value,index)=>value+this.#gyroBias[index]+n()*gyroNoiseStd) as Vec3,orientation_rad:[attitude[0],attitude[1],attitude[2]],accel_bias_mps2:[...this.#accelBias],gyro_bias_rad_s:[...this.#gyroBias],vibration_rms_mps2:environment.vibrationRmsMps2,accel_noise_std_mps2:accelNoiseStd,gyro_noise_std_rad_s:gyroNoiseStd}};}
  reset():void{this.#nextMeasurementTimeS=0;this.#lastMeasurementTimeS=null;this.#queue=[];this.#noise.spare=null;this.#sampleCount=0;this.#accelBias=[0,0,0];this.#gyroBias=[0,0,0];}
  saveState():SensorPluginStateDTO{return{schema_version:1,plugin_id:this.metadata.id,plugin_version:this.metadata.version,state:{next_measurement_time_s:this.#nextMeasurementTimeS,last_measurement_time_s:this.#lastMeasurementTimeS,sample_count:this.#sampleCount,gaussian_spare:this.#noise.spare,accel_bias_mps2:[...this.#accelBias],gyro_bias_rad_s:[...this.#gyroBias],latency_queue:structuredClone(this.#queue) as any}};}
  validateState(state:SensorPluginStateDTO):void{const value=state?.state;if(state?.schema_version!==1||state.plugin_id!==this.metadata.id||state.plugin_version!==this.metadata.version||!Number.isFinite(value?.next_measurement_time_s)||!(value.last_measurement_time_s===null||Number.isFinite(value.last_measurement_time_s))||!Number.isInteger(value.sample_count)||!Array.isArray(value.accel_bias_mps2)||!Array.isArray(value.gyro_bias_rad_s)||!Array.isArray(value.latency_queue)||(value.gaussian_spare!==null&&!Number.isFinite(value.gaussian_spare)))throw new Error("Invalid IMU checkpoint state.");}
  loadState(state:SensorPluginStateDTO):void{this.validateState(state);this.#nextMeasurementTimeS=state.state.next_measurement_time_s as number;this.#lastMeasurementTimeS=state.state.last_measurement_time_s as number|null;this.#sampleCount=state.state.sample_count as number;this.#noise.spare=state.state.gaussian_spare as number|null;this.#accelBias=[...(state.state.accel_bias_mps2 as number[])] as Vec3;this.#gyroBias=[...(state.state.gyro_bias_rad_s as number[])] as Vec3;this.#queue=structuredClone(state.state.latency_queue) as unknown as Pending[];}
  dispose():void{this.#services=undefined;this.reset();}
}
