import {readFileSync,writeFileSync} from "node:fs";
import {resolveExperiment} from "../../packages/experiment-schema/src/index.ts";
import {LegacyProductionEngine} from "../../backends/node/src/legacy-production-engine.ts";

const [telemetryPath,outPath]=process.argv.slice(2);
if(!telemetryPath||!outPath)throw Error("usage: reconcile_vrx_bias_check.ts telemetry.csv result.json");
const dt=.05,lines=readFileSync(telemetryPath,"utf8").trim().split("\n"),keys=lines[0].split(","),rows=lines.slice(1).map(line=>Object.fromEntries(line.split(",").map((value,i)=>[keys[i],Number(value)])));
const start=rows.reduce((a,b)=>Math.abs(b.time_s-1.9)<Math.abs(a.time_s-1.9)?b:a),end=rows.reduce((a,b)=>Math.abs(b.time_s-1.95)<Math.abs(a.time_s-1.95)?b:a);
const vrxStart=[start.velocity_body_x,-start.velocity_body_y,-start.angular_velocity_body_z],vrxEnd=[end.velocity_body_x,-end.velocity_body_y,-end.angular_velocity_body_z],finite=(a:number[],b:number[])=>a.map((x,i)=>(b[i]-x)/dt);
const config=resolveExperiment({schema_version:1,experiment:{name:"reconcile-vrx-bias",seed:20000,timestep_s:dt,duration_s:1},backend:{type:"node"},vehicle:{preset:"searobotics-surveyor-m1.8",plant:"planar3"},environment:{wind_mps:[0,0,0],current_mps:[0,0,0]},initial_state:{position_ned_m:[10000,10000,0],attitude_rad:[0,0,0],body_velocity_mps:[vrxStart[0],vrxStart[1],0],angular_rate_body_rad_s:[0,0,vrxStart[2]]},mission:{type:"rl-common-waypoint-v1",waypoints:[{north_m:19000,east_m:19000}]},sensors:[]} as any);
const engine=new LegacyProductionEngine();engine.reset(config);const nodeStart:any=engine.getGroundTruth();engine.step({actuators:{effectors:{port:{command:0},starboard:{command:0}}}});const nodeEnd:any=engine.getGroundTruth();engine.dispose();
const nodeStartNu=[...nodeStart.velocity_body_mps.slice(0,2),nodeStart.angular_rate_body_rad_s[2]],nodeEndNu=[...nodeEnd.velocity_body_mps.slice(0,2),nodeEnd.angular_rate_body_rad_s[2]],nodeReported=[...nodeEnd.acceleration_body_mps2.slice(0,2)];
const vrxFinite=finite(vrxStart,vrxEnd),nodeFinite=finite(nodeStartNu,nodeEndNu),delta=(a:number[],b:number[])=>a.map((x,i)=>x-b[i]),norm=(x:number[])=>Math.sqrt(x.reduce((s,v)=>s+v*v,0)),linear=(x:number[])=>x.slice(0,2);
const report={schema_version:1,status:"RECONCILED_BACK_CALCULATION_SAMPLING_BUG",states_used:{back_calculation_damping:{nu:vrxStart,source:`${telemetryPath} t=1.9 s VRX start state`},back_calculation_node_bias:{nu:vrxStart,source:"same VRX start state passed to the theoretical Node formula"},standing_residual_node_acceleration:{nu:null,start_nu:nodeStartNu,end_nu:nodeEndNu,source:"finite difference of Node's independently evolved start and end velocities over 0.05 s; an interval-average acceleration has no single evaluation nu"}},same_nu:false,matched_initial_state:{vrx:vrxStart,node:nodeStartNu,difference:delta(vrxStart,nodeStartNu)},accelerations:{vrx_interval_finite_difference:vrxFinite,node_interval_finite_difference:nodeFinite,linear_finite_difference_vrx_minus_node:delta(linear(vrxFinite),linear(nodeFinite)),linear_finite_difference_l2:norm(delta(linear(vrxFinite),linear(nodeFinite))),node_post_step_instantaneous_derivative:nodeReported},interval_states:{vrx:{start:vrxStart,end:vrxEnd},node:{start:nodeStartNu,end:nodeEndNu}},explanation:"The standing 0.105 m/s^2 residual is a valid like-for-like comparison of VRX and Node finite differences over their separately evolved 0.05 s intervals. The live-bias back-calculation was not an instantaneous force balance: it multiplied the VRX interval-average acceleration by M, but evaluated damping and Node's theoretical bias only at the interval-start nu. Therefore its apparent bias agreement cannot be reconciled algebraically with the acceleration residual and is invalid evidence about DART's live bias vector.",conclusion:"Withdraw the prior live-bias match. The finite-difference acceleration residual remains, while DART's instantaneous bias output is still unresolved. Do not advance to a constraint/integration hypothesis on the basis of the invalid back-calculation."};
writeFileSync(outPath,JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify(report,null,2));
