import{createHash}from"node:crypto";import{readFile,writeFile}from"node:fs/promises";import{resolve}from"node:path";import{DeterministicVectorMarineSimulation,HeadlessMarineSimulation}from"../../packages/core/src/simulation.ts";import{resolveExperiment}from"../../packages/experiment-schema/src/index.ts";import{SeededRandom}from"../../packages/core/src/random.ts";import{LegacyProductionEngine}from"../../backends/node/src/legacy-production-engine.ts";import{createReproducibilityManifest,hashConfig}from"../../packages/metrics/src/reproducibility-manifest.ts";
const ROOT=resolve("."),protocolPath="artifacts/rl-campaign/p2.5-reference-protocol.json",protocol=JSON.parse(await readFile(protocolPath,"utf8")),sha=(x:string|Uint8Array)=>createHash("sha256").update(x).digest("hex"),protocolSha=sha(await readFile(protocolPath)),policies=["frozen-untrained-policy-v1","PID-v1","MPC-v1"] as const,episodes=50,dt=.05,maxSteps=2400;
type Policy=typeof policies[number];type Run={policy:Policy;seed:number;route:[number,number][];waypoint:number;previousDistance:number;previousAction:[number,number];return:number;steps:number;success:boolean;done:boolean;holdSteps:number;termination:string;terminal_state:unknown;terminal_info:unknown;crossTrackSum:number};
const clamp=(x:number,a:number,b:number)=>Math.min(b,Math.max(a,x)),wrap=(x:number)=>Math.atan2(Math.sin(x),Math.cos(x)),median=(x:number[])=>{const a=[...x].sort((p,q)=>p-q),n=a.length;return n%2?a[(n-1)/2]:(a[n/2-1]+a[n/2])/2;},quantile=(x:number[],q:number)=>{const a=[...x].sort((p,q)=>p-q),p=(a.length-1)*q,i=Math.floor(p),f=p-i;return a[i]+(a[Math.min(i+1,a.length-1)]-a[i])*f;};
const episodeRandom=(seed:number)=>{const r=new SeededRandom(seed),uniform=(a:number,b:number)=>a+(b-a)*r.next(),angle=uniform(-20,20)*Math.PI/180,start:[number,number]=[10_000+uniform(-1,1),10_000+uniform(-1,1)],rot=([n,e]:number[]):[number,number]=>[start[0]+n*Math.cos(angle)-e*Math.sin(angle),start[1]+n*Math.sin(angle)+e*Math.cos(angle)],speed=uniform(0,1),dir=uniform(0,2*Math.PI),wind=uniform(0,8),windDir=uniform(0,2*Math.PI);return{start,heading:uniform(-10,10)*Math.PI/180,route:protocol.route_relative_m.map(rot),current:[speed*Math.cos(dir),speed*Math.sin(dir),0],wind:[wind*Math.cos(windDir),wind*Math.sin(windDir),0]};};
const weightRng=new SeededRandom(protocol.controllers["frozen-untrained-policy-v1"].weight_seed),rand=()=>2*weightRng.next()-1,W1=Array.from({length:16},()=>Array.from({length:9},rand)),b1=Array.from({length:16},rand),W2=Array.from({length:2},()=>Array.from({length:16},rand)),b2=Array.from({length:2},rand);
function policyAction(policy:Policy,truth:any,target:[number,number],previous:[number,number]):[number,number]{const[n,e]=truth.position_ned_m,[u,v]=truth.velocity_body_mps,r=truth.angular_rate_body_rad_s[2],yaw=truth.attitude_rad[2],dn=target[0]-n,de=target[1]-e,range=Math.hypot(dn,de),error=wrap(Math.atan2(de,dn)-yaw);if(policy==="PID-v1")return[clamp(8*range-45*u,-150,150),clamp(80*error-20*r,-100,100)];if(policy==="MPC-v1"){const targetSpeed=Math.min(1.5,.3*range,range<8?range/8*1.5:1.5);return[clamp(100*(targetSpeed-u),-150,150),clamp(100*error-30*r,-100,100)];}const obs=[clamp(range/100,0,1),Math.sin(error),Math.cos(error),u/3,v/3,r,previous[0]/150,previous[1]/100,1],hidden=W1.map((row,i)=>Math.tanh(row.reduce((s,w,j)=>s+w*obs[j],b1[i])));return[150*Math.tanh(W2[0].reduce((s,w,j)=>s+w*hidden[j],b2[0])),100*Math.tanh(W2[1].reduce((s,w,j)=>s+w*hidden[j],b2[1]))];}
function crossTrack(p:[number,number],a:[number,number],b:[number,number]){const dx=b[0]-a[0],dy=b[1]-a[1],den=dx*dx+dy*dy,t=den?clamp(((p[0]-a[0])*dx+(p[1]-a[1])*dy)/den,0,1):0;return Math.hypot(p[0]-(a[0]+t*dx),p[1]-(a[1]+t*dy));}
const specs=[] as Array<{policy:Policy;seed:number;random:ReturnType<typeof episodeRandom>}>;for(const policy of policies)for(let i=0;i<episodes;i++)specs.push({policy,seed:protocol.episode_seeds.first+i,random:episodeRandom(protocol.episode_seeds.first+i)});
const configs=specs.map(({policy,seed,random})=>resolveExperiment({schema_version:1,experiment:{name:`p2.5-${policy}-${seed}`,seed,timestep_s:dt,duration_s:120},backend:{type:"node"},vehicle:{preset:"vehicle-a-otter",plant:"planar3"},environment:{current_mps:random.current as any,wind_mps:random.wind as any},initial_state:{position_ned_m:[...random.start,0],attitude_rad:[0,0,random.heading]},mission:{type:"rl-common-waypoint-v1",waypoints:[{north_m:19000,east_m:19000}]},sensors:[]} as any));
const sim=new DeterministicVectorMarineSimulation(configs.length,()=>new HeadlessMarineSimulation(new LegacyProductionEngine())),obs=sim.reset(configs),runs:Run[]=specs.map(({policy,seed,random})=>({policy,seed,route:random.route,waypoint:0,previousDistance:Math.hypot(random.route[0][0]-random.start[0],random.route[0][1]-random.start[1]),previousAction:[0,0],return:0,steps:0,success:false,done:false,holdSteps:0,termination:"timeout",terminal_state:null,terminal_info:null,crossTrackSum:0}));
for(let step=0;step<maxSteps&&runs.some(x=>!x.done);step++){const actions=runs.map((run,i)=>{if(run.done)return null;const[surge,yaw]=policyAction(run.policy,sim.getGroundTruth(i),run.route[run.waypoint],run.previousAction);return{actuators:{desiredWrench:[surge,0,0,0,0,yaw]}};}),mask=runs.map(x=>!x.done),result=sim.step(actions,mask);for(let i=0;i<runs.length;i++){const run=runs[i];if(run.done)continue;const truth:any=sim.getGroundTruth(i),pos:[number,number]=[truth.position_ned_m[0],truth.position_ned_m[1]],target=run.route[run.waypoint],distance=Math.hypot(target[0]-pos[0],target[1]-pos[1]),action=policyAction(run.policy,truth,target,run.previousAction),progress=run.previousDistance-distance,segmentStart=run.waypoint?run.route[run.waypoint-1]:specs[i].random.start,track=crossTrack(pos,segmentStart,target),delta=(action[0]-run.previousAction[0])/150,deltaYaw=(action[1]-run.previousAction[1])/100;run.return+=2*progress-.02*track-.05*(delta*delta+deltaYaw*deltaYaw);run.crossTrackSum+=track;run.previousDistance=distance;run.previousAction=action;run.steps++;
      if(distance<=2&&run.waypoint<run.route.length-1){run.waypoint++;run.previousDistance=Math.hypot(run.route[run.waypoint][0]-pos[0],run.route[run.waypoint][1]-pos[1]);}
      const speed=Math.hypot(truth.velocity_body_mps[0],truth.velocity_body_mps[1]);if(run.waypoint===run.route.length-1&&distance<=2&&speed<=.5)run.holdSteps++;else run.holdSteps=0;if(run.holdSteps>=40){run.success=true;run.done=true;run.termination="success";run.return+=100;}else if(result.terminated[i]){run.done=true;run.termination=String(result.infos[i].stop_reason??"simulator_termination");run.return-=100;}else if(step===maxSteps-1||result.truncated[i]){run.done=true;run.termination="timeout";run.return-=10;}run.terminal_state=truth;run.terminal_info=result.infos[i];}}
sim.dispose();
const raw=runs.map(x=>({policy:x.policy,seed:x.seed,return:x.return,success:x.success,episode_length:x.steps,termination_reason:x.termination,waypoints_reached:x.waypoint+(x.success?1:0),mean_cross_track_m:x.crossTrackSum/Math.max(x.steps,1),terminal_state:x.terminal_state,terminal_info:x.terminal_info}));
const summarize=(policy:Policy)=>{const rows=raw.filter(x=>x.policy===policy),v=rows.map(x=>x.return),mean=v.reduce((a,b)=>a+b,0)/v.length,sd=Math.sqrt(v.reduce((s,x)=>s+(x-mean)**2,0)/(v.length-1));return{policy,mean,median:median(v),standard_deviation:sd,min:Math.min(...v),max:Math.max(...v),q1:quantile(v,.25),q3:quantile(v,.75),success_rate:rows.filter(x=>x.success).length/rows.length,episode_length:{mean:rows.reduce((s,x)=>s+x.episode_length,0)/rows.length,median:median(rows.map(x=>x.episode_length)),min:Math.min(...rows.map(x=>x.episode_length)),max:Math.max(...rows.map(x=>x.episode_length))}};},summaries=policies.map(summarize),untrained=summaries[0],reference=[summaries[1],summaries[2]].sort((a,b)=>b.median-a.median)[0],gap=reference.median-untrained.median,bootstrapRng=new SeededRandom(protocol.bootstrap.seed),boot=[];
for(let b=0;b<protocol.bootstrap.resamples;b++){const indices=Array.from({length:episodes},()=>Math.floor(bootstrapRng.next()*episodes)),u=indices.map(i=>raw.find(x=>x.policy===untrained.policy&&x.seed===protocol.episode_seeds.first+i)!.return),r=indices.map(i=>raw.find(x=>x.policy===reference.policy&&x.seed===protocol.episode_seeds.first+i)!.return);boot.push(median(r)-median(u));}
const ci:[number,number]=[quantile(boot,.025),quantile(boot,.975)],gatePassed=gap>0&&ci[0]>0,absoluteThreshold=untrained.median+.5*gap,reproducibility=await createReproducibilityManifest({root:ROOT,seed:protocol.episode_seeds.first,config:protocol,configSha256:hashConfig(protocol),producer:"benchmark",execution:{host_class:"local",host_id:"local-apple-silicon",device:"cpu",arch:process.arch,numerics_mode:"float64",blas_backend:"Accelerate",env_count:configs.length}}),report={schema_version:1,artifact_kind:"p2.5-reference-calibration",protocol_sha256:protocolSha,host_class:"local",paper_measurement_eligible:false,summaries,reference_policy:reference.policy,untrained_median:untrained.median,reference_median:reference.median,gap,paired_bootstrap_95_ci:ci,normalized_threshold:.5,derived_absolute_return_threshold:absoluteThreshold,gate_passed:gatePassed,raw,reproducibility};await writeFile("artifacts/rl-campaign/p2.5-reference-calibration.json",`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify({summaries,reference_policy:reference.policy,gap,paired_bootstrap_95_ci:ci,derived_absolute_return_threshold:absoluteThreshold,gate_passed:gatePassed},null,2));if(!gatePassed)process.exitCode=2;
