import {mkdir,readFile,writeFile} from "node:fs/promises";
import {HeadlessMarineSimulation} from "../../packages/core/src/simulation.ts";
import {SeededRandom} from "../../packages/core/src/random.ts";
import {resolveExperiment} from "../../packages/experiment-schema/src/index.ts";
import {LegacyProductionEngine} from "../../backends/node/src/legacy-production-engine.ts";
import {VehicleCCoriolisFeedforward} from "../../backends/node/src/vehicle-c-coriolis-feedforward.ts";
import {losAction,VEHICLE_WRENCH_LIMITS} from "./ports/portable-controllers.ts";

const SEED=30007,OLD_OFFSET=.81,NEW_OFFSET=.99,CONTRACT="artifacts/rl-campaign/surveyor/task-contract-frozen.json",BASELINE="artifacts/rl-campaign/vehicle-c-thrust-increase-four-seed.json",OUT="artifacts/rl-campaign/vehicle-c-pod-spacing-seed-30007.json",task=JSON.parse(await readFile(CONTRACT,"utf8")).tasks.find((x:any)=>x.task_id==="common-waypoint-transit-v1"),baseline=JSON.parse(await readFile(BASELINE,"utf8")).rows.find((x:any)=>x.seed===SEED),dt=task.timing.physics_timestep_s,hold=Math.round(task.timing.control_interval_s/dt),ff=new VehicleCCoriolisFeedforward(1);
const r=new SeededRandom(SEED),u=(a:number,b:number)=>a+(b-a)*r.next(),rr=task.reset_randomization,angle=u(...rr.route_rotation_deg)*Math.PI/180,start:[number,number]=[10000+u(...rr.start_position_offset_m),10000+u(...rr.start_position_offset_m)],rot=([n,e]:number[]):[number,number]=>[start[0]+n*Math.cos(angle)-e*Math.sin(angle),start[1]+n*Math.sin(angle)+e*Math.cos(angle)],cs=u(...rr.current_speed_m_s),cd=u(0,2*Math.PI),ws=u(...rr.wind_speed_m_s),wd=u(0,2*Math.PI),random={start,heading:u(...rr.start_heading_deg)*Math.PI/180,route:rr.route_relative_m.map(rot),current:[cs*Math.cos(cd),cs*Math.sin(cd),0] as [number,number,number],wind:[ws*Math.cos(wd),ws*Math.sin(wd),0]};
const config=resolveExperiment({schema_version:1,experiment:{name:"vehicle-c-pod-spacing-30007",seed:SEED,timestep_s:dt,duration_s:task.timing.episode_length_s},backend:{type:"node"},vehicle:{preset:"vehicle-c-azimuth",plant:"coupled6"},environment:{current_mps:random.current,wind_mps:random.wind},initial_state:{position_ned_m:[...start,0],attitude_rad:[0,0,random.heading]},mission:{type:"rl-common-waypoint-v1",waypoints:[{north_m:19000,east_m:19000}]},sensors:[]}as any),sim=new HeadlessMarineSimulation(new LegacyProductionEngine(undefined,{vehicleC:{podLateralOffsetM:NEW_OFFSET}}));sim.reset(config);
let waypoint=0,lastCommand:any=null,success=false,termination="timeout",closest=Infinity,finalLegAt:number|null=null;const trace:any[]=[];
const geometry=(truth:any)=>{const a=waypoint?random.route[waypoint-1]:start,b=random.route[waypoint],dn=b[0]-a[0],de=b[1]-a[1],length=Math.hypot(dn,de),cn=dn/length,ce=de/length,n=truth.position_ned_m[0],e=truth.position_ned_m[1],along=(n-a[0])*cn+(e-a[1])*ce,cross=-ce*(n-a[0])+cn*(e-a[1]);return{a,b,distance:Math.hypot(b[0]-n,b[1]-e),passed:along>=length&&Math.abs(cross)<=15.361124064575238};};
for(let step=0;step<task.timing.episode_length_steps;step++){
  const before:any=sim.getGroundTruth(),g0=geometry(before);if(step%hold===0){const [surge,yaw]=losAction("LOS-PID-v2",{north_m:before.position_ned_m[0],east_m:before.position_ned_m[1],heading_rad:before.attitude_rad[2],surge_mps:before.velocity_body_mps[0],yaw_rate_rad_s:before.angular_rate_body_rad_s[2]},g0.a,g0.b,VEHICLE_WRENCH_LIMITS["vehicle-c-azimuth"]),applied=ff.apply([surge,0,0,0,0,yaw],before,random.current);lastCommand={actuators:{desiredWrench:applied.desired_wrench}};}
  const result=sim.step(lastCommand),truth:any=sim.getGroundTruth(),g=geometry(truth),diagnostics:any=result.info.vehicle_diagnostics,allocation=diagnostics.allocation_diagnostics;if(waypoint<random.route.length-1&&(g.distance<=6||g.passed)){waypoint++;if(waypoint===random.route.length-1)finalLegAt=(step+1)*dt;}const final=random.route.at(-1)!,distanceFinal=Math.hypot(final[0]-truth.position_ned_m[0],final[1]-truth.position_ned_m[1]);if(waypoint===random.route.length-1)closest=Math.min(closest,distanceFinal);trace.push({step:step+1,t_s:(step+1)*dt,waypoint,distance_to_final_m:distanceFinal,desired_yaw_nm:lastCommand.actuators.desiredWrench[5],delivered_yaw_nm:diagnostics.full_wrench[5],yaw_delivery_gap_nm:lastCommand.actuators.desiredWrench[5]-diagnostics.full_wrench[5],saturation_scale:allocation.saturation_scale,degradation:allocation.degradation,heading_rad:truth.attitude_rad[2],yaw_rate_rad_s:truth.angular_rate_body_rad_s[2]});if(waypoint===random.route.length-1&&g.distance<=task.learnability.absolute_success_rate_threshold.terminal_definition.radius_m){success=true;termination="success";break;}if(result.terminated){termination=String(result.info.stop_reason??"simulator_termination");break;}
}
sim.dispose();const closestRow=trace.filter(x=>x.waypoint===2).sort((a,b)=>a.distance_to_final_m-b.distance_to_final_m)[0]??null,mean=(values:number[])=>values.reduce((a,b)=>a+b,0)/values.length;
const candidate={success,termination_reason:termination,final_leg_activated:finalLegAt!==null,final_leg_activation_s:finalLegAt,closest_final_m:Number.isFinite(closest)?closest:null,degraded_fraction:trace.filter(x=>x.degradation!=="none").length/trace.length,minimum_saturation_scale:Math.min(...trace.map(x=>x.saturation_scale)),closest_instant:closestRow&&{...closestRow,absolute_yaw_delivery_gap_nm:Math.abs(closestRow.yaw_delivery_gap_nm)},mean_absolute_yaw_delivery_gap_nm:mean(trace.map(x=>Math.abs(x.yaw_delivery_gap_nm)))};
const report={schema_version:1,artifact_kind:"vehicle-c-wider-pod-spacing-candidate-diagnostic",status:"COMPLETE_HALT_FOR_REVIEW",seed:SEED,design:{candidate_only:true,old_lateral_offset_m:OLD_OFFSET,new_lateral_offset_m:NEW_OFFSET,old_total_spacing_m:2*OLD_OFFSET,new_total_spacing_m:2*NEW_OFFSET,moment_arm_increase_fraction:NEW_OFFSET/OLD_OFFSET-1,basis:"Maximum centerline offset equal to half of the recorded 1.98 m hull beam.",only_changed_variable:"signed pod lateral position",unchanged:{thrust_forward_n:1000,thrust_reverse_n:500,thrust_lag_s:.35,azimuth_slew_deg_s:30,hull:true,controller:"frozen LOS-PID-v2 with endpoint geometry",coriolis_scale:1,environment_seed:SEED}},baseline:{success:baseline.success,termination_reason:baseline.termination_reason,closest_final_m:baseline.closest_distance_m,degraded_fraction:baseline.saturation.degraded_fraction,minimum_saturation_scale:baseline.saturation.minimum_scale},candidate,comparison:{closest_change_m:candidate.closest_final_m===null?null:candidate.closest_final_m-baseline.closest_distance_m,improved:candidate.closest_final_m!==null&&candidate.closest_final_m<baseline.closest_distance_m},trace};
await mkdir("artifacts/rl-campaign",{recursive:true});await writeFile(OUT,JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({...report,trace:undefined},null,2));
