import {mkdir,readFile,writeFile} from "node:fs/promises";
import {HeadlessMarineSimulation,DeterministicVectorMarineSimulation} from "../../packages/core/src/simulation.ts";
import {SeededRandom} from "../../packages/core/src/random.ts";
import {resolveExperiment} from "../../packages/experiment-schema/src/index.ts";
import {LegacyProductionEngine} from "../../backends/node/src/legacy-production-engine.ts";
import {VEHICLE_C_MAX_FORWARD_THRUST_N,VEHICLE_C_MAX_REVERSE_THRUST_N} from "../../backends/node/src/vehicle-c-production.ts";
import {VehicleCCoriolisFeedforward} from "../../backends/node/src/vehicle-c-coriolis-feedforward.ts";
import {FROZEN_GAINS,losActionCandidate,VEHICLE_C_CANDIDATE_GAINS,VEHICLE_WRENCH_LIMITS} from "./ports/portable-controllers.ts";

const SEEDS=[30000,30007,30013,30048] as const;
const CANDIDATE="LOS-PID-v2-C-inertia-scaled-v1";
const CONTRACT="artifacts/rl-campaign/surveyor/task-contract-frozen.json";
const BASELINE="artifacts/rl-campaign/vehicle-c-thrust-increase-four-seed.json";
const OUT="artifacts/rl-campaign/vehicle-c-inertia-scaled-control-four-seed.json";
const I_A=17.89,I_C=757.937,KP_A=100,KD_A=35,ratio=I_C/I_A,kp=KP_A*ratio,kd=KD_A*Math.sqrt(ratio),omega=Math.sqrt(kp/I_C),actuatorBandwidth=1/.35;
if(JSON.stringify(FROZEN_GAINS)!==JSON.stringify({"LOS-PID-v2":{lookahead:8,kp:100,kd:35,speed:1},"LOS-SPEEDCAP-v2":{lookahead:4,kp:100,kd:35,speed:1}}))throw new Error("Frozen Vehicle A gains changed");
const candidate=VEHICLE_C_CANDIDATE_GAINS[CANDIDATE];
if(candidate.kp!==kp||candidate.kd!==kd||candidate.lookahead!==8)throw new Error("Inertia-scaled candidate does not match derivation");
const task=JSON.parse(await readFile(CONTRACT,"utf8")).tasks.find((x:any)=>x.task_id==="common-waypoint-transit-v1");
const prior=JSON.parse(await readFile(BASELINE,"utf8")),priorBySeed=Object.fromEntries(prior.rows.map((row:any)=>[row.seed,row]));
const dt=task.timing.physics_timestep_s,maxSteps=task.timing.episode_length_steps,hold=Math.round(task.timing.control_interval_s/dt),terminalRadius=task.learnability.absolute_success_rate_threshold.terminal_definition.radius_m,intermediateRadius=6,corridor=15.361124064575238;
const feedforward=new VehicleCCoriolisFeedforward(1);
const randomization=(seed:number)=>{const r=new SeededRandom(seed),u=(a:number,b:number)=>a+(b-a)*r.next(),rr=task.reset_randomization,angle=u(...rr.route_rotation_deg)*Math.PI/180,start:[number,number]=[10000+u(...rr.start_position_offset_m),10000+u(...rr.start_position_offset_m)],rot=([n,e]:number[]):[number,number]=>[start[0]+n*Math.cos(angle)-e*Math.sin(angle),start[1]+n*Math.sin(angle)+e*Math.cos(angle)],cs=u(...rr.current_speed_m_s),cd=u(0,2*Math.PI),ws=u(...rr.wind_speed_m_s),wd=u(0,2*Math.PI);return{start,heading:u(...rr.start_heading_deg)*Math.PI/180,route:rr.route_relative_m.map(rot),current:[cs*Math.cos(cd),cs*Math.sin(cd),0] as [number,number,number],wind:[ws*Math.cos(wd),ws*Math.sin(wd),0]};};
const specs=SEEDS.map(seed=>({seed,random:randomization(seed)}));
const configs=specs.map(({seed,random})=>resolveExperiment({schema_version:1,experiment:{name:`vehicle-c-inertia-scaled-${seed}`,seed,timestep_s:dt,duration_s:task.timing.episode_length_s},backend:{type:"node"},vehicle:{preset:"vehicle-c-azimuth",plant:"coupled6"},environment:{current_mps:random.current,wind_mps:random.wind},initial_state:{position_ned_m:[...random.start,0],attitude_rad:[0,0,random.heading]},mission:{type:"rl-common-waypoint-v1",waypoints:[{north_m:19000,east_m:19000}]},sensors:[]}as any));
const runs=specs.map(x=>({...x,waypoint:0,lastCommand:null as any,done:false,success:false,termination_reason:"timeout",final_leg_reached:false,final_leg_entry_time_s:null as number|null,closest_final_leg_distance_m:Infinity,lagNoticeable:0,samples:0,saturationActive:0,degraded:0,unreachable:0,minScale:1}));
const sim=new DeterministicVectorMarineSimulation(runs.length,()=>new HeadlessMarineSimulation(new LegacyProductionEngine()));sim.reset(configs);
const geometry=(run:any,truth:any)=>{const a=run.waypoint?run.random.route[run.waypoint-1]:run.random.start,b=run.random.route[run.waypoint],dn=b[0]-a[0],de=b[1]-a[1],length=Math.hypot(dn,de),cn=dn/length,ce=de/length,n=truth.position_ned_m[0],e=truth.position_ned_m[1],along=(n-a[0])*cn+(e-a[1])*ce,cross=-ce*(n-a[0])+cn*(e-a[1]);return{distance:Math.hypot(b[0]-n,b[1]-e),passed:along>=length&&Math.abs(cross)<=corridor,start:a,goal:b};};
for(let step=0;step<maxSteps&&runs.some(run=>!run.done);step++){
  const commands=runs.map((run:any,i)=>{if(run.done)return null;if(step%hold)return run.lastCommand;const truth:any=sim.getGroundTruth(i),g=geometry(run,truth),[surge,yaw]=losActionCandidate(CANDIDATE,{north_m:truth.position_ned_m[0],east_m:truth.position_ned_m[1],heading_rad:truth.attitude_rad[2],surge_mps:truth.velocity_body_mps[0],yaw_rate_rad_s:truth.angular_rate_body_rad_s[2]},g.start,g.goal,VEHICLE_WRENCH_LIMITS["vehicle-c-azimuth"]),applied=feedforward.apply([surge,0,0,0,0,yaw],truth,run.random.current);return run.lastCommand={actuators:{desiredWrench:applied.desired_wrench}};});
  const result=sim.step(commands.map(x=>x?{actuators:x.actuators}:null),runs.map(run=>!run.done));
  for(let i=0;i<runs.length;i++){const run:any=runs[i];if(run.done)continue;const truth:any=sim.getGroundTruth(i),d:any=result.infos[i].vehicle_diagnostics,a=d.allocation_diagnostics,g=geometry(run,truth),ach=a.achieved_wrench,del=d.full_wrench;run.samples++;const noticeable=(k:number)=>Math.abs(ach[k]-del[k])>Math.max(1,.05*Math.abs(ach[k]));if(noticeable(0)||noticeable(5))run.lagNoticeable++;if(a.saturation_scale<1-1e-12)run.saturationActive++;if(a.degradation!=="none")run.degraded++;if(!a.reachable)run.unreachable++;run.minScale=Math.min(run.minScale,a.saturation_scale);
    if(run.waypoint<run.random.route.length-1&&(g.distance<=intermediateRadius||g.passed)){run.waypoint++;if(run.waypoint===run.random.route.length-1){run.final_leg_reached=true;run.final_leg_entry_time_s=truth.time_s;}}
    if(run.waypoint===run.random.route.length-1){const final=run.random.route.at(-1),distance=Math.hypot(final[0]-truth.position_ned_m[0],final[1]-truth.position_ned_m[1]);run.closest_final_leg_distance_m=Math.min(run.closest_final_leg_distance_m,distance);if(distance<=terminalRadius){run.done=true;run.success=true;run.termination_reason="success";}}
    if(!run.done&&result.terminated[i]){run.done=true;run.termination_reason=String(result.infos[i].stop_reason??"simulator_termination");}else if(!run.done&&(result.truncated[i]||step===maxSteps-1)){run.done=true;run.termination_reason="timeout";}}
  if((step+1)%480===0)console.error(JSON.stringify({phase:"vehicle-c-inertia-scaled-four-seed",completed_steps:step+1,total_steps:maxSteps}));
}
sim.dispose();
const rows=runs.map((run:any)=>({seed:run.seed,success:run.success,termination_reason:run.termination_reason,final_leg_reached:run.final_leg_reached,final_leg_entry_time_s:run.final_leg_entry_time_s,closest_final_leg_distance_m:Number.isFinite(run.closest_final_leg_distance_m)?run.closest_final_leg_distance_m:null,post_dynamics_lag_tracking_gap:{threshold:"either surge or yaw absolute gap > max(1 unit, 5% of allocator-achieved component)",noticeable_fraction:run.lagNoticeable/run.samples},allocator_saturation:{active_fraction:run.saturationActive/run.samples,minimum_scale:run.minScale,degraded_fraction:run.degraded/run.samples,unreachable_fraction:run.unreachable/run.samples},best_prior_thrust_increase_full_compensation:{success:priorBySeed[run.seed].success,termination_reason:priorBySeed[run.seed].termination_reason,reported_closest_distance_m:priorBySeed[run.seed].closest_distance_m,note:"Prior artifact did not final-leg-gate this field.",saturation:priorBySeed[run.seed].saturation}}));
const report={schema_version:1,artifact_kind:"vehicle-c-inertia-scaled-control-four-seed",status:"COMPLETE_HALT_FOR_REVIEW",derivation:{vehicle_a_yaw_inertia_kg_m2:I_A,vehicle_c_total_yaw_inertia_kg_m2:I_C,inertia_ratio:ratio,kp_formula:`${KP_A} * (${I_C} / ${I_A})`,kp_vehicle_c:kp,kd_formula:`${KD_A} * sqrt(${I_C} / ${I_A})`,kd_vehicle_c:kd,natural_frequency_rad_s:omega,thrust_lag_time_constant_s:.35,actuator_bandwidth_rad_s:actuatorBandwidth,natural_frequency_to_actuator_bandwidth_ratio:omega/actuatorBandwidth,stability_margin_assessment:"CONCERN: the requested 2.36 rad/s closed-loop natural frequency is 82.7% of the first-order thrust-lag bandwidth (2.86 rad/s), before the nonlinear 30 deg/s azimuth slew is considered; this is not comfortably separated."},configuration:{candidate:CANDIDATE,gains:candidate,endpoint_geometry_fix:true,coriolis_compensation_scale:1,per_pod_forward_thrust_n:VEHICLE_C_MAX_FORWARD_THRUST_N,per_pod_reverse_thrust_n:VEHICLE_C_MAX_REVERSE_THRUST_N,combination_note:"First prescribed test combining inertia-scaled Vehicle C gains, endpoint geometry, full-scale Coriolis compensation, and the settled increased thrust rating."},frozen_path_check:{frozen_gains_runtime_value:FROZEN_GAINS,unchanged:true},seeds:SEEDS,prohibitions:{seed_30003_run:false,full_sweep:false,physics_or_geometry_changed:false,frozen_gains_changed:false,rejected_lookahead_4_candidate_deleted:false},rows};
await mkdir("artifacts/rl-campaign",{recursive:true});await writeFile(OUT,JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify(report,null,2));
