import {mkdir,readFile,writeFile} from "node:fs/promises";
import {HeadlessMarineSimulation} from "../../packages/core/src/simulation.ts";
import {SeededRandom} from "../../packages/core/src/random.ts";
import {resolveExperiment} from "../../packages/experiment-schema/src/index.ts";
import {LegacyProductionEngine} from "../../backends/node/src/legacy-production-engine.ts";
import {losAction,losDesiredHeading,VEHICLE_WRENCH_LIMITS} from "./ports/portable-controllers.ts";

const SEEDS=[30000,30048] as const,CONTRACT="artifacts/rl-campaign/surveyor/task-contract-frozen.json",OUT="artifacts/rl-campaign/vehicle-c-coriolis-check-30000-30048.json",task=JSON.parse(await readFile(CONTRACT,"utf8")).tasks.find((x:any)=>x.task_id==="common-waypoint-transit-v1"),dt=task.timing.physics_timestep_s,maxSteps=task.timing.episode_length_steps,hold=Math.round(task.timing.control_interval_s/dt),terminalRadius=task.learnability.absolute_success_rate_threshold.terminal_definition.radius_m,intermediateRadius=6;
const randomization=(seed:number)=>{const r=new SeededRandom(seed),u=(a:number,b:number)=>a+(b-a)*r.next(),rr=task.reset_randomization,angle=u(...rr.route_rotation_deg)*Math.PI/180,start:[number,number]=[10000+u(...rr.start_position_offset_m),10000+u(...rr.start_position_offset_m)],rot=([n,e]:number[]):[number,number]=>[start[0]+n*Math.cos(angle)-e*Math.sin(angle),start[1]+n*Math.sin(angle)+e*Math.cos(angle)],cs=u(...rr.current_speed_m_s),cd=u(0,2*Math.PI),ws=u(...rr.wind_speed_m_s),wd=u(0,2*Math.PI);return{start,heading:u(...rr.start_heading_deg)*Math.PI/180,route:rr.route_relative_m.map(rot),current:[cs*Math.cos(cd),cs*Math.sin(cd),0],wind:[ws*Math.cos(wd),ws*Math.sin(wd),0]}};
const quantile=(values:number[],p:number)=>{const sorted=[...values].sort((a,b)=>a-b),x=(sorted.length-1)*p,lo=Math.floor(x),hi=Math.ceil(x);return sorted[lo]+(sorted[hi]-sorted[lo])*(x-lo)},mean=(values:number[])=>values.reduce((a,b)=>a+b,0)/values.length,cancelFraction=(delivered:number,term:number)=>Math.abs(delivered)>=1?Math.max(0,-term*Math.sign(delivered))/Math.abs(delivered):null;
const episodes=[] as any[];
for(const seed of SEEDS){
  const random=randomization(seed),config=resolveExperiment({schema_version:1,experiment:{name:`vehicle-c-coriolis-${seed}`,seed,timestep_s:dt,duration_s:task.timing.episode_length_s},backend:{type:"node"},vehicle:{preset:"vehicle-c-azimuth",plant:"coupled6"},environment:{current_mps:random.current,wind_mps:random.wind},initial_state:{position_ned_m:[...random.start,0],attitude_rad:[0,0,random.heading]},mission:{type:"rl-common-waypoint-v1",waypoints:[{north_m:19000,east_m:19000}]},sensors:[]}as any),sim=new HeadlessMarineSimulation(new LegacyProductionEngine());
  let waypoint=0,lastCommand:any=null,success=false,terminationReason="timeout";const rows=[] as any[];sim.reset(config);
  const geometry=(truth:any)=>{const a=waypoint?random.route[waypoint-1]:random.start,b=random.route[waypoint],dn=b[0]-a[0],de=b[1]-a[1],length=Math.hypot(dn,de),cn=dn/length,ce=de/length,n=truth.position_ned_m[0],e=truth.position_ned_m[1],along=(n-a[0])*cn+(e-a[1])*ce,cross=-ce*(n-a[0])+cn*(e-a[1]);return{distance:Math.hypot(b[0]-n,b[1]-e),along,cross,length,passed:along>=length&&Math.abs(cross)<=15.361124064575238,start:a,goal:b}};
  for(let step=0;step<maxSteps;step++){
    const before:any=sim.getGroundTruth(),g0=geometry(before);
    if(step%hold===0){const [surge,yaw]=losAction("LOS-PID-v2",{north_m:before.position_ned_m[0],east_m:before.position_ned_m[1],heading_rad:before.attitude_rad[2],surge_mps:before.velocity_body_mps[0],yaw_rate_rad_s:before.angular_rate_body_rad_s[2]},g0.start,g0.goal,VEHICLE_WRENCH_LIMITS["vehicle-c-azimuth"]);lastCommand={actuators:{desiredWrench:[surge,0,0,0,0,yaw]}};}
    const result=sim.step(lastCommand),truth:any=sim.getGroundTruth(),checkpoint:any=sim.saveCheckpoint().payload,plant=checkpoint.plantRuntimeState.coupled6,breakdown=plant.forceBreakdown,delivered=checkpoint.actuatorState.lastFullWrench[5],coriolis=breakdown.Coriolis6[5],damping=breakdown.HydrodynamicDamping6[5],g=geometry(truth),heading=losDesiredHeading({north_m:truth.position_ned_m[0],east_m:truth.position_ned_m[1],heading_rad:truth.attitude_rad[2],surge_mps:truth.velocity_body_mps[0],yaw_rate_rad_s:truth.angular_rate_body_rad_s[2]},g.start,g.goal,8),headingError=Math.atan2(Math.sin(heading.desired_rad-truth.attitude_rad[2]),Math.cos(heading.desired_rad-truth.attitude_rad[2]));
    rows.push({t_s:truth.time_s,delivered_yaw_moment_nm:delivered,coriolis_moment_nm:coriolis,damping_moment_nm:damping,net_yaw_wrench_nm:delivered+coriolis+damping,observed_yaw_accel_rad_s2:null,yaw_rate_rad_s:truth.angular_rate_body_rad_s[2],surge_mps:truth.velocity_body_mps[0],heading_error_rad:headingError,waypoint_index:waypoint,coriolis_cancelled_fraction:cancelFraction(delivered,coriolis),damping_cancelled_fraction:cancelFraction(delivered,damping)});
    if(waypoint<random.route.length-1&&(g.distance<=intermediateRadius||g.passed))waypoint++;else if(waypoint===random.route.length-1&&g.distance<=terminalRadius){success=true;terminationReason="success";break;}else if(result.terminated){terminationReason=String(result.info.stop_reason??"simulator_termination");break;}else if(result.truncated||step===maxSteps-1){terminationReason="timeout";break;}
  }
  sim.dispose();
  for(let i=0;i<rows.length;i++)rows[i].observed_yaw_accel_rad_s2=i===0?(rows[1].yaw_rate_rad_s-rows[0].yaw_rate_rad_s)/dt:i===rows.length-1?(rows[i].yaw_rate_rad_s-rows[i-1].yaw_rate_rad_s)/dt:(rows[i+1].yaw_rate_rad_s-rows[i-1].yaw_rate_rad_s)/(2*dt);
  const eligible=rows.filter(x=>x.coriolis_cancelled_fraction!==null),turning=eligible.filter(x=>Math.abs(x.heading_error_rad)>=.35||Math.abs(x.yaw_rate_rad_s)>=.05),lower=eligible.filter(x=>Math.abs(x.heading_error_rad)<.35&&Math.abs(x.yaw_rate_rad_s)<.05),opposing=(x:any,key:string)=>Math.max(0,-x[key]*Math.sign(x.delivered_yaw_moment_nm)),sumOpposing=(selected:any[],key:string)=>selected.reduce((sum,x)=>sum+opposing(x,key),0),summarize=(selected:any[])=>({samples:selected.length,coriolis_mean_fraction:mean(selected.map(x=>x.coriolis_cancelled_fraction)),coriolis_p95_fraction:quantile(selected.map(x=>x.coriolis_cancelled_fraction),.95),damping_mean_fraction:mean(selected.map(x=>x.damping_cancelled_fraction)),damping_p95_fraction:quantile(selected.map(x=>x.damping_cancelled_fraction),.95)}),byWaypoint=Object.fromEntries([...new Set(eligible.map(x=>x.waypoint_index))].map(index=>[String(index),summarize(eligible.filter(x=>x.waypoint_index===index))])),concentration={turning_sample_fraction:turning.length/eligible.length,coriolis_opposing_moment_share_in_turning:sumOpposing(turning,"coriolis_moment_nm")/sumOpposing(eligible,"coriolis_moment_nm"),damping_opposing_moment_share_in_turning:sumOpposing(turning,"damping_moment_nm")/sumOpposing(eligible,"damping_moment_nm")};
  const old=JSON.parse(await readFile(`artifacts/rl-campaign/vehicle-c-wrench-path-current/seed-${seed}.json`,"utf8"));episodes.push({seed,success,termination_reason:terminationReason,post_dynamics_noticeable_gap_fraction:old.summary.post_lag_dynamics_gap.noticeable_surge_or_yaw_fraction,cancellation_fraction_definition:"max(0, -term*sign(delivered))/abs(delivered), evaluated only when abs(delivered)>=1 N m; values may exceed 1 when a term over-cancels",overall:summarize(eligible),phase:{turning_definition:"abs(heading_error)>=0.35 rad or abs(yaw_rate)>=0.05 rad/s",concentration,turning:summarize(turning),lower_demand:summarize(lower),by_waypoint:byWaypoint},rows});
}
const report={schema_version:1,artifact_kind:"vehicle-c-coriolis-cancellation-check",status:"COMPLETE_READ_ONLY",new_instrumentation_seeds:SEEDS,controller:"LOS-PID-v2 current frozen gains",timestep_s:dt,observed_acceleration_differencing:"central difference at 0.05 s for interior samples; forward/backward endpoints",episodes,three_seed_summary:[{seed:30000,dominant_mechanism:"mixed: lag-dynamics plus Coriolis and damping cancellation",lag_dynamics_noticeable_gap_fraction:episodes[0].post_dynamics_noticeable_gap_fraction,coriolis_mean_cancellation_fraction:episodes[0].overall.coriolis_mean_fraction,damping_mean_cancellation_fraction:episodes[0].overall.damping_mean_fraction},{seed:30007,dominant_mechanism:"Coriolis",lag_dynamics_noticeable_gap_fraction:0.6616666666666666,coriolis_cancellation_at_closest_fraction:.8935,damping_cancellation_at_closest_fraction:.0811,total_delivered_moment_cancelled_at_closest_fraction:.974622305715241,note:"Restated from existing seed-30007 artifacts; not rerun. The noticeable-gap fraction counts frequent threshold crossings, while its closest-approach post-lag norm was small."},{seed:30048,dominant_mechanism:"mixed: lag-dynamics plus Coriolis and damping cancellation",lag_dynamics_noticeable_gap_fraction:episodes[1].post_dynamics_noticeable_gap_fraction,coriolis_mean_cancellation_fraction:episodes[1].overall.coriolis_mean_fraction,damping_mean_cancellation_fraction:episodes[1].overall.damping_mean_fraction}],prohibitions:{seed_30007_rerun:false,seed_30013_run:false,seed_30003_run:false,full_sweep:false,parameters_changed:false,compensation_implemented:false}};
await mkdir("artifacts/rl-campaign",{recursive:true});await writeFile(OUT,JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({...report,episodes:episodes.map(({rows,...episode})=>episode)},null,2));
