import {mkdir,readFile,writeFile} from "node:fs/promises";
import {dirname} from "node:path";
import {DeterministicVectorMarineSimulation,HeadlessMarineSimulation} from "../../packages/core/src/simulation.ts";
import {SeededRandom} from "../../packages/core/src/random.ts";
import {resolveExperiment} from "../../packages/experiment-schema/src/index.ts";
import {LegacyProductionEngine} from "../../backends/node/src/legacy-production-engine.ts";
import {VehicleCCoriolisFeedforward} from "../../backends/node/src/vehicle-c-coriolis-feedforward.ts";
import {losAction,losDesiredHeading,VEHICLE_WRENCH_LIMITS} from "./ports/portable-controllers.ts";

type Policy="frozen-untrained-policy-v1"|"LOS-PID-v2"|"LOS-SPEEDCAP-v2";
type Run={policy:Policy;seed:number;start:[number,number];route:[number,number][];current:[number,number,number];waypoint:number;previousAction:[number,number];lastCommand:any;closestFinal:number;terminalHits:Record<number,boolean>;terminalHitTimes:Record<number,number|null>};

const CONTRACT="artifacts/rl-campaign/surveyor/task-contract-frozen.json",PARAMETERS="validation/gazebo-vehicles/vehicle-c-parameter-map.json",OUT="artifacts/rl-campaign/vehicle-c/terminal-radius-sweep-candidate.json";
const SEED_FIRST=30100,EPISODES_PER_POLICY=200,SEEDS=Array.from({length:EPISODES_PER_POLICY},(_,i)=>SEED_FIRST+i),DIAGNOSTIC_SEEDS=[30000,30003,30007,30013,30048];
const RADII=[1.75,2,3,4,5,6,7,8,9,10,12,15,17.5],VEHICLE_LENGTH=3.5,DEFENSIBLE_MINIMUM=.5*VEHICLE_LENGTH,DEFENSIBILITY_CEILING=5*VEHICLE_LENGTH,BORROWED_GPS_SIGMA=.8,GPS_COMFORT_MINIMUM=2*BORROWED_GPS_SIGMA,INTERMEDIATE_RADIUS=6,PLANE_CROSSING_CORRIDOR=15.361124064575238;
const task=JSON.parse(await readFile(CONTRACT,"utf8")).tasks.find((x:any)=>x.task_id==="common-waypoint-transit-v1"),parameters=JSON.parse(await readFile(PARAMETERS,"utf8"));
const dt=task.timing.physics_timestep_s,controlInterval=task.timing.control_interval_s,controlHold=Math.round(controlInterval/dt),maxSteps=task.timing.episode_length_steps,feedforward=new VehicleCCoriolisFeedforward(1);
const clamp=(x:number,lo:number,hi:number)=>Math.min(hi,Math.max(lo,x));
const networkRandom=new SeededRandom(7319),randomWeight=()=>2*networkRandom.next()-1,W1=Array.from({length:16},()=>Array.from({length:9},randomWeight)),b1=Array.from({length:16},randomWeight),W2=Array.from({length:2},()=>Array.from({length:16},randomWeight)),b2=Array.from({length:2},randomWeight);
const scenario=(seed:number)=>{const random=new SeededRandom(seed),uniform=(a:number,b:number)=>a+(b-a)*random.next(),rr=task.reset_randomization,angle=uniform(...rr.route_rotation_deg)*Math.PI/180,start:[number,number]=[10000+uniform(...rr.start_position_offset_m),10000+uniform(...rr.start_position_offset_m)],rotate=([n,e]:number[]):[number,number]=>[start[0]+n*Math.cos(angle)-e*Math.sin(angle),start[1]+n*Math.sin(angle)+e*Math.cos(angle)],currentSpeed=uniform(...rr.current_speed_m_s),currentDirection=uniform(0,2*Math.PI),windSpeed=uniform(...rr.wind_speed_m_s),windDirection=uniform(0,2*Math.PI);return{start,heading:uniform(...rr.start_heading_deg)*Math.PI/180,route:rr.route_relative_m.map(rotate),current:[currentSpeed*Math.cos(currentDirection),currentSpeed*Math.sin(currentDirection),0] as [number,number,number],wind:[windSpeed*Math.cos(windDirection),windSpeed*Math.sin(windDirection),0] as [number,number,number]};};
const geometry=(run:Run,truth:any)=>{const start=run.waypoint?run.route[run.waypoint-1]:run.start,goal=run.route[run.waypoint],dn=goal[0]-start[0],de=goal[1]-start[1],length=Math.hypot(dn,de),cn=dn/length,ce=de/length,n=truth.position_ned_m[0],e=truth.position_ned_m[1],along=(n-start[0])*cn+(e-start[1])*ce,cross=-ce*(n-start[0])+cn*(e-start[1]);return{start,goal,distance:Math.hypot(goal[0]-n,goal[1]-e),cross,passed:along>=length&&Math.abs(cross)<=PLANE_CROSSING_CORRIDOR};};
const untrainedAction=(run:Run,truth:any,g:any):[number,number]=>{const desired=losDesiredHeading({north_m:truth.position_ned_m[0],east_m:truth.position_ned_m[1],heading_rad:truth.attitude_rad[2],surge_mps:truth.velocity_body_mps[0],yaw_rate_rad_s:truth.angular_rate_body_rad_s[2]},g.start,g.goal,8).desired_rad,error=Math.atan2(Math.sin(desired-truth.attitude_rad[2]),Math.cos(desired-truth.attitude_rad[2])),obs=[clamp(g.distance/100,0,1),Math.sin(error),Math.cos(error),truth.velocity_body_mps[0]/3,truth.velocity_body_mps[1]/3,truth.angular_rate_body_rad_s[2],run.previousAction[0]/150,run.previousAction[1]/100,1],hidden=W1.map((row,i)=>Math.tanh(row.reduce((sum,weight,j)=>sum+weight*obs[j],b1[i])));return[150*Math.tanh(W2[0].reduce((sum,weight,j)=>sum+weight*hidden[j],b2[0])),100*Math.tanh(W2[1].reduce((sum,weight,j)=>sum+weight*hidden[j],b2[1]))];};

async function simulateBatch(policies:Policy[],seeds:number[]){
  const specs=policies.flatMap(policy=>seeds.map(seed=>({policy,seed,random:scenario(seed)}))),runs:Run[]=specs.map(x=>({policy:x.policy,seed:x.seed,start:x.random.start,route:x.random.route,current:x.random.current,waypoint:0,previousAction:[0,0],lastCommand:null,closestFinal:Infinity,terminalHits:Object.fromEntries(RADII.map(radius=>[radius,false])),terminalHitTimes:Object.fromEntries(RADII.map(radius=>[radius,null]))}));
  const configs=specs.map(x=>resolveExperiment({schema_version:1,experiment:{name:`vehicle-c-radius-${x.policy}-${x.seed}`,seed:x.seed,timestep_s:dt,duration_s:task.timing.episode_length_s},backend:{type:"node"},vehicle:{preset:"vehicle-c-azimuth",plant:"coupled6"},environment:{current_mps:x.random.current,wind_mps:x.random.wind},initial_state:{position_ned_m:[...x.random.start,0],attitude_rad:[0,0,x.random.heading]},mission:{type:"rl-common-waypoint-v1",waypoints:[{north_m:19000,east_m:19000}]},sensors:[]}as any));
  const sim=new DeterministicVectorMarineSimulation(runs.length,()=>new HeadlessMarineSimulation(new LegacyProductionEngine()));sim.reset(configs);
  for(let step=0;step<maxSteps;step++){
    const commands=runs.map((run,i)=>{if(step%controlHold&&run.lastCommand)return run.lastCommand;const truth:any=sim.getGroundTruth(i),g=geometry(run,truth),action=run.policy==="frozen-untrained-policy-v1"?untrainedAction(run,truth,g):losAction(run.policy,{north_m:truth.position_ned_m[0],east_m:truth.position_ned_m[1],heading_rad:truth.attitude_rad[2],surge_mps:truth.velocity_body_mps[0],yaw_rate_rad_s:truth.angular_rate_body_rad_s[2]},g.start,g.goal,VEHICLE_WRENCH_LIMITS["vehicle-c-azimuth"]),applied=feedforward.apply([action[0],0,0,0,0,action[1]],truth,run.current);run.previousAction=action;return run.lastCommand={actuators:{desiredWrench:applied.desired_wrench}};});
    sim.step(commands.map(command=>({actuators:command.actuators})));
    for(let i=0;i<runs.length;i++){const run=runs[i],truth:any=sim.getGroundTruth(i),g=geometry(run,truth);if(run.waypoint<run.route.length-1&&(g.distance<=INTERMEDIATE_RADIUS||g.passed))run.waypoint++;const current=geometry(run,truth);if(run.waypoint===run.route.length-1){run.closestFinal=Math.min(run.closestFinal,current.distance);for(const radius of RADII)if(current.distance<=radius){run.terminalHits[radius]=true;if(run.terminalHitTimes[radius]===null)run.terminalHitTimes[radius]=(step+1)*dt;}}}
  }
  sim.dispose();return runs.map(run=>({policy:run.policy,seed:run.seed,closest_final_m:Number.isFinite(run.closestFinal)?run.closestFinal:null,terminal_hits:run.terminalHits,terminal_hit_times_s:run.terminalHitTimes}));
}

const raw:any[]=[];for(let offset=0;offset<SEEDS.length;offset+=20){const batch=SEEDS.slice(offset,offset+20);raw.push(...await simulateBatch(["frozen-untrained-policy-v1","LOS-PID-v2","LOS-SPEEDCAP-v2"],batch));console.error(JSON.stringify({phase:"vehicle-c-terminal-radius-sweep",completed_episodes:Math.min((offset+batch.length)*3,SEEDS.length*3),total_episodes:SEEDS.length*3}));}
const rate=(policy:Policy,radius:number)=>raw.filter(row=>row.policy===policy&&row.terminal_hits[radius]).length/EPISODES_PER_POLICY;
const cells=RADII.map(radius=>{const untrained=rate("frozen-untrained-policy-v1",radius),pid=rate("LOS-PID-v2",radius),speedcap=rate("LOS-SPEEDCAP-v2",radius),best=Math.max(pid,speedcap),ceiling=radius<=DEFENSIBILITY_CEILING,gps=radius>=GPS_COMFORT_MINIMUM,length=radius>=DEFENSIBLE_MINIMUM,band=best>=.4&&best<=.7;return{radius_m:radius,rates:{untrained,los_pid:pid,los_speedcap:speedcap,best_classical:best},separation_ratio:best>0?(best-untrained)/best:null,checks:{best_classical_in_40_70:band,defensibility_ceiling:ceiling?"PASS":"FAIL",gps_comfort_floor:gps?"PASS":"FAIL",half_vehicle_length_floor:length?"PASS":"FAIL"},eligible:band&&ceiling&&gps&&length&&best>0};}),eligible=cells.filter(cell=>cell.eligible).sort((a,b)=>b.separation_ratio!-a.separation_ratio!||a.radius_m-b.radius_m),selected=eligible[0]??null;
const report={schema_version:1,artifact_kind:"vehicle-c-terminal-radius-sweep-candidate",status:selected?"ELIGIBLE_RADIUS_FOUND_HALT_FOR_REVIEW":"NO_ELIGIBLE_RADIUS_HALT_FOR_REVIEW",vehicle:"vehicle-c-azimuth",method:{approach:"radius-only Vehicle C script duplicating only Surveyor's approved sweep method",selection_rule:"Smallest radius maximizing separation ratio between untrained and best classical success, subject to the 40-70% band and all sanity checks.",terminal_variant:"pass-through",timeout_s:task.timing.episode_length_s},vehicle_parameters:{source:PARAMETERS,asserted_source_length_m:parameters.geometry_m.length,vehicle_length_m:VEHICLE_LENGTH,defensible_minimum_m:DEFENSIBLE_MINIMUM,defensibility_ceiling_m:DEFENSIBILITY_CEILING},controller_configuration:{classical:["LOS-PID-v2","LOS-SPEEDCAP-v2"],shared_controller_call:"losAction(name, ...) with frozen gains and endpoint point-capture geometry",vehicle_limits:VEHICLE_WRENCH_LIMITS["vehicle-c-azimuth"],coriolis_feedforward:{scale:1,formula:"tau_comp = C(M, nu_r) * nu_r",commanded_components:["surge","yaw"],sway_reported_not_commanded:true},rejected_configuration_excluded:["losActionCandidate / VEHICLE_C_CANDIDATE_GAINS","0.5-scale Coriolis compensation"]},untrained_baseline:{id:"frozen-untrained-policy-v1",source:"Exact existing frozen 9-16-2 tanh network definition and seed 7319 from surveyor-calibration.ts; evaluated on Vehicle C without training."},seed_protocol:{first:SEEDS[0],last:SEEDS.at(-1),episodes_per_policy:EPISODES_PER_POLICY,total_episodes:raw.length,reason:"Fresh contiguous block above all Vehicle C diagnostic/tuning seeds through 30048.",diagnostic_seeds:DIAGNOSTIC_SEEDS,overlap:SEEDS.filter(seed=>DIAGNOSTIC_SEEDS.includes(seed))},gps_noise_floor:{horizontal_sigma_m_per_axis:BORROWED_GPS_SIGMA,comfortable_minimum_m:GPS_COMFORT_MINIMUM,status:"BORROWED_NOT_INDEPENDENTLY_VERIFIED_FOR_VEHICLE_C",source:"Surveyor gps@1.0.0 calibration configuration; no Vehicle-C-specific GPS noise calibration was found.",gps_applied_in_sweep:false,methodological_note:"Terminal hits use simulator truth; this is only a portability sanity check."},candidate_radii_m:RADII,cells,selected:selected&&{...selected,reference_policy:selected.rates.los_pid>=selected.rates.los_speedcap?"LOS-PID-v2":"LOS-SPEEDCAP-v2"},diagnostic_context:{not_used_for_selection:true,full_scale_closest_approach_m:{30007:7.4995,30013:5.1575,30048:5.7161},would_be_passes_at_selected_radius:selected?Object.fromEntries([[30007,7.4995],[30013,5.1575],[30048,5.7161]].map(([seed,distance])=>[seed,distance<=selected.radius_m])):null},raw,decision:{human_approval_required:true,frozen:false,task_contract_touched:false}};
await mkdir(dirname(OUT),{recursive:true});await writeFile(OUT,JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({...report,raw:undefined},null,2));
