import {mkdir,readFile,writeFile} from "node:fs/promises";
import {HeadlessMarineSimulation,DeterministicVectorMarineSimulation} from "../../packages/core/src/simulation.ts";
import {SeededRandom} from "../../packages/core/src/random.ts";
import {resolveExperiment} from "../../packages/experiment-schema/src/index.ts";
import {LegacyProductionEngine} from "../../backends/node/src/legacy-production-engine.ts";
import {VEHICLE_C_MAX_FORWARD_THRUST_N,VEHICLE_C_MAX_REVERSE_THRUST_N} from "../../backends/node/src/vehicle-c-production.ts";
import {VehicleCCoriolisFeedforward} from "../../backends/node/src/vehicle-c-coriolis-feedforward.ts";
import {losAction,VEHICLE_WRENCH_LIMITS} from "./ports/portable-controllers.ts";

const SEEDS=[30000,30007,30013,30048] as const,CONTRACT="artifacts/rl-campaign/surveyor/task-contract-frozen.json",BASELINE="artifacts/rl-campaign/vehicle-c-coriolis-compensation-four-seed.json",OUT="artifacts/rl-campaign/vehicle-c-thrust-increase-four-seed.json";
const task=JSON.parse(await readFile(CONTRACT,"utf8")).tasks.find((x:any)=>x.task_id==="common-waypoint-transit-v1"),baseline=JSON.parse(await readFile(BASELINE,"utf8")),baselineBySeed=Object.fromEntries(baseline.rows.map((row:any)=>[row.seed,row])),dt=task.timing.physics_timestep_s,maxSteps=task.timing.episode_length_steps,hold=Math.round(task.timing.control_interval_s/dt),terminalRadius=task.learnability.absolute_success_rate_threshold.terminal_definition.radius_m,intermediateRadius=6,corridor=15.361124064575238,feedforward=new VehicleCCoriolisFeedforward(1);
const quantile=(values:number[],p:number)=>{const a=[...values].sort((x,y)=>x-y),position=(a.length-1)*p,index=Math.floor(position);return a[index]+(a[Math.min(index+1,a.length-1)]-a[index])*(position-index);};
const distribution=(values:number[])=>({count:values.length,mean:values.reduce((sum,x)=>sum+x,0)/values.length,median:quantile(values,.5),p95:quantile(values,.95),p05:quantile(values,.05),min:Math.min(...values)});
const baselineSaturation=baseline.rows.map((row:any)=>{const active=row.trace.map((x:any)=>x.saturation_scale).filter((x:number)=>x<1-1e-12),required=active.map((x:number)=>1/x);return{seed:row.seed,active_fraction:active.length/row.trace.length,saturation_scale:distribution(active),required_authority_multiplier:{median:quantile(required,.5),p95:quantile(required,.95),max:Math.max(...required)},multiplier_to_raise_p05_scale_to_0p95:.95/quantile(active,.05)};});
const randomization=(seed:number)=>{const r=new SeededRandom(seed),u=(a:number,b:number)=>a+(b-a)*r.next(),rr=task.reset_randomization,angle=u(...rr.route_rotation_deg)*Math.PI/180,start:[number,number]=[10000+u(...rr.start_position_offset_m),10000+u(...rr.start_position_offset_m)],rot=([n,e]:number[]):[number,number]=>[start[0]+n*Math.cos(angle)-e*Math.sin(angle),start[1]+n*Math.sin(angle)+e*Math.cos(angle)],cs=u(...rr.current_speed_m_s),cd=u(0,2*Math.PI),ws=u(...rr.wind_speed_m_s),wd=u(0,2*Math.PI);return{start,heading:u(...rr.start_heading_deg)*Math.PI/180,route:rr.route_relative_m.map(rot),current:[cs*Math.cos(cd),cs*Math.sin(cd),0] as [number,number,number],wind:[ws*Math.cos(wd),ws*Math.sin(wd),0]};};
const specs=SEEDS.map(seed=>({seed,random:randomization(seed)})),configs=specs.map(({seed,random})=>resolveExperiment({schema_version:1,experiment:{name:`vehicle-c-thrust-increase-${seed}`,seed,timestep_s:dt,duration_s:task.timing.episode_length_s},backend:{type:"node"},vehicle:{preset:"vehicle-c-azimuth",plant:"coupled6"},environment:{current_mps:random.current,wind_mps:random.wind},initial_state:{position_ned_m:[...random.start,0],attitude_rad:[0,0,random.heading]},mission:{type:"rl-common-waypoint-v1",waypoints:[{north_m:19000,east_m:19000}]},sensors:[]}as any)),runs=specs.map(x=>({...x,waypoint:0,lastCommand:null as any,done:false,success:false,termination_reason:"timeout",closest_distance_m:Infinity,trace:[] as any[]})),sim=new DeterministicVectorMarineSimulation(runs.length,()=>new HeadlessMarineSimulation(new LegacyProductionEngine()));sim.reset(configs);
const geometry=(run:any,truth:any)=>{const a=run.waypoint?run.random.route[run.waypoint-1]:run.random.start,b=run.random.route[run.waypoint],dn=b[0]-a[0],de=b[1]-a[1],length=Math.hypot(dn,de),cn=dn/length,ce=de/length,n=truth.position_ned_m[0],e=truth.position_ned_m[1],along=(n-a[0])*cn+(e-a[1])*ce,cross=-ce*(n-a[0])+cn*(e-a[1]);return{distance:Math.hypot(b[0]-n,b[1]-e),passed:along>=length&&Math.abs(cross)<=corridor,start:a,goal:b};};
for(let step=0;step<maxSteps&&runs.some(run=>!run.done);step++){
  const commands=runs.map((run:any,i)=>{if(run.done)return null;if(step%hold)return run.lastCommand;const truth:any=sim.getGroundTruth(i),g=geometry(run,truth),[surge,yaw]=losAction("LOS-PID-v2",{north_m:truth.position_ned_m[0],east_m:truth.position_ned_m[1],heading_rad:truth.attitude_rad[2],surge_mps:truth.velocity_body_mps[0],yaw_rate_rad_s:truth.angular_rate_body_rad_s[2]},g.start,g.goal,VEHICLE_WRENCH_LIMITS["vehicle-c-azimuth"]),applied=feedforward.apply([surge,0,0,0,0,yaw],truth,run.random.current);return run.lastCommand={actuators:{desiredWrench:applied.desired_wrench}};}),result=sim.step(commands.map(x=>x?{actuators:x.actuators}:null),runs.map(run=>!run.done));
  for(let i=0;i<runs.length;i++){const run:any=runs[i];if(run.done)continue;const truth:any=sim.getGroundTruth(i),diagnostics:any=result.infos[i].vehicle_diagnostics,allocation=diagnostics.allocation_diagnostics,g=geometry(run,truth),final=run.random.route.at(-1),distanceFinal=Math.hypot(final[0]-truth.position_ned_m[0],final[1]-truth.position_ned_m[1]);run.closest_distance_m=Math.min(run.closest_distance_m,distanceFinal);run.trace.push({t_s:truth.time_s,saturation_scale:allocation.saturation_scale,degradation:allocation.degradation,reachable:allocation.reachable,residual_wrench:allocation.residual_wrench});if(run.waypoint<run.random.route.length-1&&(g.distance<=intermediateRadius||g.passed))run.waypoint++;else if(run.waypoint===run.random.route.length-1&&g.distance<=terminalRadius){run.done=true;run.success=true;run.termination_reason="success";}else if(result.terminated[i]){run.done=true;run.termination_reason=String(result.infos[i].stop_reason??"simulator_termination");}else if(result.truncated[i]||step===maxSteps-1){run.done=true;run.termination_reason="timeout";}}
  if((step+1)%240===0)console.error(JSON.stringify({phase:"vehicle-c-thrust-increase-four-seed",completed_steps:step+1,total_steps:maxSteps}));
}
sim.dispose();
const rows=runs.map((run:any)=>{const active=run.trace.map((x:any)=>x.saturation_scale).filter((x:number)=>x<1-1e-12),base=baselineBySeed[run.seed];return{seed:run.seed,success:run.success,termination_reason:run.termination_reason,closest_distance_m:run.closest_distance_m,saturation:{active_fraction:active.length/run.trace.length,active_scale_distribution:active.length?distribution(active):null,minimum_scale:Math.min(...run.trace.map((x:any)=>x.saturation_scale)),degraded_fraction:run.trace.filter((x:any)=>x.degradation!=="none").length/run.trace.length,unreachable_fraction:run.trace.filter((x:any)=>!x.reachable).length/run.trace.length},full_compensation_baseline:{success:base.success,termination_reason:base.termination_reason,closest_distance_m:base.closest_distance_m,minimum_saturation_scale:base.allocation.minimum_saturation_scale,degraded_fraction:base.allocation.degraded_fraction},trace:run.trace};});
const matchedPrediction=rows.map((row:any)=>{const old=baselineBySeed[row.seed].trace,oldActive=old.map((x:any,index:number)=>x.saturation_scale<1-1e-12?index:-1).filter((index:number)=>index>=0),covered=oldActive.filter((index:number)=>row.trace[index].saturation_scale>=.95).length;return{seed:row.seed,old_active_timesteps:oldActive.length,new_scale_at_least_0p95_on_old_active_timesteps:covered,fraction:covered/oldActive.length};});
const report={schema_version:1,artifact_kind:"vehicle-c-thrust-increase-four-seed-diagnostic",status:"COMPLETE_HALT_FOR_REVIEW",change:{only_variable:"per-pod thrust rating",multiplier:2,old:{forward_n:500,reverse_n:250},new:{forward_n:VEHICLE_C_MAX_FORWARD_THRUST_N,reverse_n:VEHICLE_C_MAX_REVERSE_THRUST_N},ratio_preserved:"2:1",unchanged:{pod_positions_m:[[-1.5,-.81,-.18],[-1.5,.81,-.18]],thrust_lag_s:.35,azimuth_slew_deg_s:30,hull_geometry:true,controller:"frozen LOS-PID-v2 plus endpoint geometry fix",coriolis_compensation_scale:1}},derivation:{source:BASELINE,active_saturation_by_seed:baselineSaturation,rule:"Choose authority multiplier so the worst per-seed fifth percentile saturation scale reaches approximately 0.95; this covers 95% of active events without sizing to the single worst instant.",worst_p05_scale:Math.min(...baselineSaturation.map((x:any)=>x.saturation_scale.p05)),exact_multiplier:Math.max(...baselineSaturation.map((x:any)=>x.multiplier_to_raise_p05_scale_to_0p95)),selected_multiplier:2,matched_timestep_prediction_check:matchedPrediction,assessment:"The percentile prediction held for seeds 30000, 30007, and 30013, but not 30048; the changed trajectory and remaining severe tail left only 88.3% of its formerly active timesteps at scale >=0.95."},physical_plausibility:{finding:"Within documented commercial pod-drive thrust, though aggressive for this research USV.",comparison:"Torqeedo Cruise 6.0 FP lists 230 lbf static thrust (approximately 1023 N), close to the selected 1000 N per pod.",manufacturer_url:"https://www.torqeedo.com/us/en-us/c-service-center",limitation:"The comparison establishes thrust-scale plausibility, not a complete mass, power, endurance, packaging, or maneuvering validation for Vehicle C."},source_of_truth:{runtime:"backends/node/src/vehicle-c-production.ts",documentation_mirror:"validation/gazebo-vehicles/vehicle-c-parameter-map.json"},seeds:SEEDS,prohibitions:{seed_30003_run:false,full_sweep:false,terminal_radius_calibration_rerun:false,controller_changed:false,pod_position_changed:false,hull_changed:false,lag_or_slew_changed:false},rows};
await mkdir("artifacts/rl-campaign",{recursive:true});await writeFile(OUT,JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({...report,rows:rows.map(({trace,...row})=>row)},null,2));
