import {createHash} from "node:crypto";
import {mkdir,readFile,writeFile} from "node:fs/promises";
import {dirname,resolve} from "node:path";
import {fileURLToPath} from "node:url";

const base="https://encdirect.noaa.gov/arcgis/rest/services/encdirect/enc_harbour/MapServer",output=resolve(process.argv[2]??"artifacts/environment-coverage/enc-live-confirmatory-pass.json"),metadataSuffixes=[".Quality_of_Data_area",".Accuracy_of_Data_area",".Compilation_Scale_of_Data_area"] as const,phase0bFields=["CATZOC","POSACC","SOUACC","VERACC","CSCALE"] as const,codedFields=["WATLEV","CATOBS","CATWRK","CONDTN","QUASOU","TECSOU","EXPSOU","VERDAT","CATZOC"] as const;
const sha256=(value:string)=>createHash("sha256").update(value).digest("hex"),sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));let lastRequestStarted=-Infinity;
interface RequestEvidence{url:string;status:number;ok:boolean;latency_ms:number;content_type:string|null;bytes:number;checksum_sha256:string}
async function requestJson(url:string):Promise<{json:any;evidence:RequestEvidence}>{const wait=200-(performance.now()-lastRequestStarted);if(wait>0)await sleep(wait);lastRequestStarted=performance.now();const started=performance.now(),response=await fetch(url,{headers:{Accept:"application/json, application/geo+json"}}),text=await response.text(),latency=performance.now()-started,evidence={url,status:response.status,ok:response.ok,latency_ms:Number(latency.toFixed(3)),content_type:response.headers.get("content-type"),bytes:Buffer.byteLength(text),checksum_sha256:sha256(text)};if(!response.ok)throw new Error(`ENC Direct request failed: HTTP ${response.status} ${response.statusText} for ${url}`);let json:any;try{json=JSON.parse(text);}catch{throw new Error(`ENC Direct returned non-JSON content for ${url}: ${text.slice(0,200)}`);}if(json?.error)throw new Error(`ENC Direct ArcGIS error for ${url}: ${JSON.stringify(json.error)}`);return{json,evidence};}
function populated(value:unknown){return value!==null&&value!==undefined&&!(typeof value==="string"&&value.trim()==="");}
function resolveLayer(layers:any[],suffix:string){const matches=layers.filter(layer=>typeof layer?.name==="string"&&layer.name.endsWith(suffix));if(matches.length!==1)throw new Error(`Expected exactly one ENC harbour layer ending ${suffix}; found ${matches.length}.`);return matches[0];}
async function queryLayer(layer:any){const all:any[]=[],requests:RequestEvidence[]=[];for(let offset=0;;offset+=1000){const url=new URL(`${base}/${layer.id}/query`);url.search=new URLSearchParams({geometry:"-122.52,37.70,-122.32,37.88",geometryType:"esriGeometryEnvelope",inSR:"4326",outSR:"4326",spatialRel:"esriSpatialRelIntersects",outFields:"*",returnGeometry:"true",f:"geojson",resultOffset:String(offset),resultRecordCount:"1000"}).toString();const response=await requestJson(url.toString()),features=Array.isArray(response.json.features)?response.json.features:[];requests.push(response.evidence);all.push(...features);if(features.length<1000)break;}return{features:all,requests};}
function ringContains(point:number[],ring:number[][]){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const[xi,yi]=ring[i],[xj,yj]=ring[j];if((yi>point[1])!==(yj>point[1])&&point[0]<(xj-xi)*(point[1]-yi)/((yj-yi)||Number.EPSILON)+xi)inside=!inside;}return inside;}
function polygonContains(point:number[],rings:number[][][]){return Boolean(rings[0]&&ringContains(point,rings[0])&&!rings.slice(1).some(ring=>ringContains(point,ring)));}
function geometryContains(point:number[],geometry:any){return geometry?.type==="Polygon"?polygonContains(point,geometry.coordinates):geometry?.type==="MultiPolygon"?geometry.coordinates.some((polygon:number[][][])=>polygonContains(point,polygon)):false;}
function geometrySummary(geometry:any){const points:number[][]=[];const visit=(value:any)=>{if(Array.isArray(value)&&value.length>=2&&typeof value[0]==="number"&&typeof value[1]==="number")points.push(value);else if(Array.isArray(value))value.forEach(visit);};visit(geometry?.coordinates);return{type:geometry?.type??null,vertex_count:points.length,bbox:points.length?[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1])),Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))]:null};}
function encoding(features:any[],field:string){const values=features.map(feature=>feature?.properties?.[field]).filter(populated),types=[...new Set(values.map(value=>typeof value))].sort();return{representation:!values.length?"absent":types.length===1&&types[0]==="string"?"predecoded-string":types.length===1&&types[0]==="number"?"raw-numeric":"mixed",non_null_values:values.length,types};}
const gebcoCell=(point:number[])=>`${Math.floor((point[1]+90)*240)},${Math.floor((point[0]+180)*240)}`;

export async function probeEnc(){
  const existing=JSON.parse(await readFile(output,"utf8"));if(existing?.summary?.features_returned!==497||!Array.isArray(existing.results))throw new Error("Phase 0 artifact is missing or no longer contains the reviewed 497-feature result; refusing to replace it.");
  for(const result of existing.results)if(result.layer_suffix===".Buoy_Lateral_point"||result.layer_suffix===".Pile_point")result.population_rates.VALSOU={...result.population_rates.VALSOU,applicability:"not-applicable",note:"VALSOU is a sounding depth and is not meaningful for floating or protruding objects."};
  const catalogue=await requestJson(`${base}/layers?f=pjson`),layers=Array.isArray(catalogue.json.layers)?catalogue.json.layers:[],resolved=metadataSuffixes.map(suffix=>({suffix,layer:resolveLayer(layers,suffix)})),metadata:any[]=[],requests=[catalogue.evidence];
  for(const{suffix,layer}of resolved){const queried=await queryLayer(layer);requests.push(...queried.requests);const features=queried.features,population_rates=Object.fromEntries(phase0bFields.map(field=>{const count=features.filter(feature=>populated(feature?.properties?.[field])).length;return[field,{populated:count,total:features.length,rate:features.length?count/features.length:0}];})),values=features.map(feature=>feature?.properties?.CATZOC).filter(populated).map(String),catzoc_value_counts=Object.fromEntries([...new Set(values)].sort().map(value=>[value,values.filter(item=>item===value).length]));metadata.push({layer_suffix:suffix,resolved_name:layer.name,resolved_layer_id:layer.id,polygon_count:features.length,population_rates,catzoc_value_counts,sample_polygons:features.slice(0,3).map(feature=>({properties:feature.properties,geometry:geometrySummary(feature.geometry)})),requests:queried.requests,_features:features});}
  const inlineDomains=Object.fromEntries(resolved.map(({layer})=>[layer.id,(layer.fields??[]).filter((field:any)=>field.domain).map((field:any)=>({name:field.name,domain:field.domain}))])),hasInlineDomains=Object.values(inlineDomains).some((fields:any)=>fields.length),allLayerIds=[...new Set([...existing.results.map((result:any)=>result.resolved_layer_id),...resolved.map(item=>item.layer.id)])].sort((a,b)=>a-b);let domains:any;
  if(hasInlineDomains)domains={status:"success",source:"inline-mapserver-layers",layers:inlineDomains};else{const url=new URL(`${base}/queryDomains`);url.search=new URLSearchParams({layers:JSON.stringify(allLayerIds),f:"pjson"}).toString();const response=await requestJson(url.toString());requests.push(response.evidence);if(!Array.isArray(response.json?.domains)||response.json.domains.length===0)throw new Error(`ENC Direct queryDomains returned no domain tables for integer layer ids ${JSON.stringify(allLayerIds)}; Amendment 2 forbids guessing an alternate request shape.`);domains={status:"success",source:"queryDomains-with-layer-id-array",request:response.evidence,response:response.json};}
  const obstacles:any[]=[];for(const result of existing.results){const layer=layers.find((candidate:any)=>candidate.id===result.resolved_layer_id);if(!layer)throw new Error(`Reviewed Phase 0 layer ${result.resolved_layer_id} disappeared from the catalogue.`);const queried=await queryLayer(layer);requests.push(...queried.requests);obstacles.push(...queried.features);}if(obstacles.length!==497)throw new Error(`Phase 0b re-query returned ${obstacles.length} obstacles instead of reviewed count 497; stop for drift review.`);
  const quality=metadata.find(item=>item.layer_suffix===".Quality_of_Data_area")!._features,assignments=obstacles.filter(feature=>feature.geometry?.type==="Point").map(feature=>{const candidates=quality.filter((polygon:any)=>geometryContains(feature.geometry.coordinates,polygon.geometry)).sort((a:any,b:any)=>Number(b.properties?.CATZOC??-Infinity)-Number(a.properties?.CATZOC??-Infinity)||Number(a.properties?.OBJECTID??Infinity)-Number(b.properties?.OBJECTID??Infinity)),selected=candidates[0];return{obstacle_ref:`${feature.properties?.DSNM??"unknown"}:${feature.properties?.OBJECTID??"unknown"}`,source_class:feature.properties?.OBJL??null,catzoc_code:selected?.properties?.CATZOC??null,zoc_polygon_id:selected?.properties?.OBJECTID??null,candidate_count:candidates.length};}),covered=assignments.filter(item=>item.candidate_count>0),weightedValues=assignments.map(item=>item.catzoc_code).filter(populated).map(String),weightedCounts=Object.fromEntries([...new Set(weightedValues)].sort((a,b)=>Number(a)-Number(b)).map(value=>[value,{count:weightedValues.filter(item=>item===value).length,percentage:weightedValues.filter(item=>item===value).length/assignments.length}])),bboxCells=new Set<string>(),occupiedCells=new Set(obstacles.filter(feature=>feature.geometry?.type==="Point").map(feature=>gebcoCell(feature.geometry.coordinates)));for(let lat=Math.floor((37.70+90)*240);lat<=Math.floor((37.88+90)*240);lat++)for(let lon=Math.floor((-122.52+180)*240);lon<=Math.floor((-122.32+180)*240);lon++)bboxCells.add(`${lat},${lon}`);
  const allFeatures=[...obstacles,...metadata.flatMap(item=>item._features)],field_encodings=Object.fromEntries(codedFields.map(field=>[field,encoding(allFeatures,field)]));for(const item of metadata)delete item._features;
  existing.generated_at=new Date().toISOString();existing.methodology=`${existing.methodology} Amendment 1 Phase 0b appended from live metadata-area queries over the same bbox; Phase 0 feature results retained. Amendment 2 adds deterministic obstacle-weighted CATZOC assignment.`;existing.domains=domains;existing.phase0b={status:"passed-tier-1-approved",bbox:existing.dataset.bbox,results:metadata,quality_coverage:{obstacle_count:497,covered_obstacle_count:covered.length,coverage_fraction:covered.length/497},obstacleWeightedZoc:{resolution_rule:["finest scale band","numerically worst CATZOC within band","ascending polygon id"],counts:weightedCounts,obstacles_with_multiple_candidates:assignments.filter(item=>item.candidate_count>1).length,assignments},gebco_15_arcsecond_cells:{cell_count_in_bbox:bboxCells.size,cells_with_at_least_one_obstacle:occupiedCells.size,occupied_fraction:occupiedCells.size/bboxCells.size},field_encodings,requests,contingency_tier_selected:"tier-1",human_review_required:false};existing.summary={...existing.summary,domain_request_succeeded:true,phase_0_gate:"passed-amendment-1",phase_0b_gate:"passed-tier-1-approved"};existing.credential_leak_scan={pass:requests.every(request=>!/[?&](token|key|password|secret)=/i.test(request.url)),findings:[]};await mkdir(dirname(output),{recursive:true});await writeFile(output,`${JSON.stringify(existing,null,2)}\n`);return existing;
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const report=await probeEnc();console.log(JSON.stringify({output,summary:report.summary,phase0b:{status:report.phase0b.status,quality_coverage:report.phase0b.quality_coverage,gebco_cells:report.phase0b.gebco_15_arcsecond_cells,results:report.phase0b.results.map((result:any)=>({name:result.resolved_name,id:result.resolved_layer_id,count:result.polygon_count,population_rates:Object.fromEntries(Object.entries(result.population_rates).map(([field,value]:any)=>[field,value.rate])),catzoc_value_counts:result.catzoc_value_counts}))}},null,2));}
