import {createHash} from "node:crypto";
import {mkdirSync,writeFileSync} from "node:fs";
import {dirname,resolve} from "node:path";
import {CoopsSource,NdbcSource,NomadsRtofsGridDecoder,NwsSource,RtofsSource} from "../../packages/environment/src/index.ts";

const site={id:"san-francisco",latitude_deg:37.806,longitude_deg:-122.465};
const startedAt=new Date().toISOString(),sha=(bytes:Uint8Array|string)=>createHash("sha256").update(bytes).digest("hex"),clock=()=>Number(process.hrtime.bigint())/1e6;
const observedRequests:any[]=[];
const checkedFetch=async(url:string|URL|Request,init?:RequestInit)=>{const start=clock(),response=await fetch(url,init),bytes=new Uint8Array(await response.arrayBuffer()),record={url:String(url).replace(/([?&](?:key|token)=)[^&]+/gi,"$1[REDACTED]"),status:response.status,ok:response.ok,latency_ms:Number((clock()-start).toFixed(3)),content_type:response.headers.get("content-type"),content_length_header:response.headers.get("content-length"),bytes:bytes.byteLength,checksum_sha256:sha(bytes)};observedRequests.push(record);if(!response.ok)throw Object.assign(new Error(`HTTP ${response.status} ${response.statusText}`),{record});return new Response(bytes,{status:response.status,headers:response.headers});};
const textFetcher=async(url:string,headers?:Record<string,string>)=>{const response=await checkedFetch(url,{headers});return{text:()=>response.text(),json:()=>response.json()};};
type Result={source:string;site:string;success:boolean;status:"success"|"failed"|"blocked"|"partial";observed_latency_ms:number;upstream_requests:any[];payload_shape:string|null;fixture_match:boolean|null;fixture_discrepancies:string[];notes:string[]};
async function measured(source:string,run:()=>Promise<{success:boolean;status?:Result["status"];payload_shape?:string;fixture_match?:boolean;fixture_discrepancies?:string[];notes?:string[]}>):Promise<Result>{const before=observedRequests.length,start=clock();try{const value=await run();return{source,site:site.id,success:value.success,status:value.status??(value.success?"success":"failed"),observed_latency_ms:Number((clock()-start).toFixed(3)),upstream_requests:observedRequests.slice(before),payload_shape:value.payload_shape??null,fixture_match:value.fixture_match??null,fixture_discrepancies:value.fixture_discrepancies??[],notes:value.notes??[]};}catch(error){const message=error instanceof Error?error.message:String(error);return{source,site:site.id,success:false,status:"failed",observed_latency_ms:Number((clock()-start).toFixed(3)),upstream_requests:observedRequests.slice(before),payload_shape:null,fixture_match:null,fixture_discrepancies:[],notes:[message]};}}
const currentTime=new Date().toISOString(),station={id:"46026",position:{latitude_deg:37.759,longitude_deg:-122.833}},coopsStation={id:"9414290",position:{latitude_deg:37.806,longitude_deg:-122.465}};
const results:Result[]=[];
results.push(await measured("ndbc",async()=>{const value=await new NdbcSource([station],textFetcher as any).query(site,currentTime,"realtime_forecast");return{success:Boolean(value),payload_shape:value?`standard meteorological text -> ${Object.keys(value.patch).join(",")}`:"no parsed row",fixture_match:Boolean(value),fixture_discrepancies:value?[]:["Live NDBC payload did not produce a parsed standard-meteorological row."],notes:["Real station 46026; production NdbcSource and parser used."]};}));
results.push(await measured("coops",async()=>{const value=await new CoopsSource([coopsStation],textFetcher as any).query(site,currentTime,"realtime_forecast");return{success:Boolean(value),payload_shape:value?"JSON data[] with t/v water-level row":"no data[] row",fixture_match:Boolean(value),fixture_discrepancies:value?[]:["Live CO-OPS response did not contain the fixture-assumed data[] water-level row."],notes:["Real station 9414290; production CoopsSource parser used."]};}));
results.push(await measured("nws",async()=>{const value=await new NwsSource({application:"BCOD live confirmatory pass",contact:"https://github.com/bcod-sim"},textFetcher as any).query(site,currentTime,"realtime_forecast");return{success:Boolean(value),payload_shape:value?"points metadata -> forecastGridData GeoJSON properties/value arrays":"no grid result",fixture_match:Boolean(value),fixture_discrepancies:value?[]:["Live NWS points/grid response did not match the fixture-assumed forecastGridData structure."],notes:["Production NwsSource made both real API calls with the required identifying User-Agent."]};}));
results.push(await measured("rtofs",async()=>{const now=new Date(),cycleDate=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()-1)),date=cycleDate.toISOString().slice(0,10).replaceAll("-",""),time=new Date(cycleDate.getTime()+24*3600_000).toISOString(),decoder=new NomadsRtofsGridDecoder(`${date}T00Z`,undefined,checkedFetch as typeof fetch),value=await new RtofsSource(decoder).query(site,time,"realtime_forecast"),p=value?.patch.water;return{success:Boolean(value&&p&&Number.isFinite(p.temperature_c)&&Number.isFinite(p.salinity_psu)),status:"success",payload_shape:value?`decoded NetCDF4/HDF5 grid cell ${value.provenance.station_or_grid_id}`:"no decoded result",fixture_match:Boolean(value),fixture_discrepancies:value?[]:["Production RTOFS decoder did not return a live grid cell."],notes:[`Pinned cycle ${date}T00Z, forecast lead f024; complete real payload decoded through the production adapter.`,value?`north=${p?.current_ned_mps?.[0]}, east=${p?.current_ned_mps?.[1]}, temperature_c=${p?.temperature_c}, salinity_psu=${p?.salinity_psu}`:""]};}));
results.push(await measured("era5",async()=>{const credentialNames=["CDSAPI_KEY","CDS_API_KEY","ERA5_API_KEY"],credential=credentialNames.find(name=>process.env[name]?.trim()),url="https://cds.climate.copernicus.eu/api/retrieve/v1/processes/reanalysis-era5-single-levels";if(!credential){let behavior="not contacted";try{const response=await checkedFetch(url,{method:"GET"}),body=await response.json() as any;behavior=`unauthenticated process-metadata probe succeeded; JSON keys: ${Object.keys(body).slice(0,12).join(",")}`;}catch(error){behavior=`unauthenticated API probe failed: ${String(error)}`;}return{success:false,status:"blocked",payload_shape:"public CDS process metadata only; no ERA5 data payload",fixture_match:false,fixture_discrepancies:["Fixture assumes valid CDS credentials and successful queued jobs; no CDS credential is configured on this host."],notes:[behavior,"No retrieval job was submitted and no secret was written to the artifact."]};}return{success:false,status:"blocked",payload_shape:null,fixture_match:null,fixture_discrepancies:[],notes:[`Credential ${credential} exists, but this confirmatory runner intentionally does not infer its format; configure an explicit approved CDS credential mapping before job submission.`]};}));
results.push(await measured("bathymetry_cascade",async()=>{const response=await checkedFetch("https://wms.gebco.net/mapserv?service=WMS&request=GetCapabilities&version=1.3.0"),text=await response.text(),layers=[...text.matchAll(/<Name>([^<]+)<\/Name>/g)].slice(0,12).map(x=>x[1]),valid=/<WMS_Capabilities|<WMT_MS_Capabilities/.test(text);return{success:false,status:valid?"partial":"failed",payload_shape:valid?`GEBCO WMS capabilities XML; layers=${layers.join(",")}`:"unexpected capabilities payload",fixture_match:false,fixture_discrepancies:["Fixture models eHydro→lidar→estuarine_dem→CUDEM→GEBCO as directly queryable catalog adapters, but the repository has no live depth-source adapter implementations.","GEBCO WMS provides map imagery/capabilities, not the fixture's direct numeric DepthValue contract."],notes:["Real GEBCO fallback endpoint contacted successfully; cascade resolution cannot be completed by current production code."]};}));

const mismatches=results.filter(x=>x.fixture_match===false).map(x=>({source:x.source,discrepancies:x.fixture_discrepancies})),artifact:any={schema_version:1,artifact_kind:"environmental-source-live-confirmatory-pass",started_at:startedAt,completed_at:new Date().toISOString(),methodology:"One real upstream retrieval/probe per named source at the San Francisco coverage site. This supplements and does not replace the deterministic 48-cell matrix.",site,results,mismatch_summary:mismatches,summary:{sources:results.length,success:results.filter(x=>x.status==="success").length,partial:results.filter(x=>x.status==="partial").length,blocked:results.filter(x=>x.status==="blocked").length,failed:results.filter(x=>x.status==="failed").length,fixture_mismatches:mismatches.length}};
const serialized=JSON.stringify(artifact),leakPatterns=[/AKIA[0-9A-Z]{16}/,/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,/(?:bearer|basic)\s+[A-Za-z0-9+/_=-]{12,}/i,/https?:\/\/[^\s:@]+:[^\s@]+@/],leaks=leakPatterns.flatMap(pattern=>serialized.match(pattern)??[]);artifact.credential_leak_scan={pass:leaks.length===0,findings:leaks.map(()=>"redacted-finding"),scanner:"serialized live artifact: cloud keys, authorization values, URL credentials, private keys"};if(leaks.length)throw new Error("Credential-like material detected in live confirmatory artifact; output refused.");
const output=resolve(process.argv[2]??"artifacts/environment-coverage/live-confirmatory-pass.json");mkdirSync(dirname(output),{recursive:true});writeFileSync(output,`${JSON.stringify(artifact,null,2)}\n`);console.log(JSON.stringify({output,summary:artifact.summary,results:results.map(({source,status,observed_latency_ms,fixture_discrepancies})=>({source,status,observed_latency_ms,fixture_discrepancies}))},null,2));
