import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {mkdirSync,writeFileSync} from "node:fs";
import {dirname,resolve} from "node:path";
import {fileURLToPath} from "node:url";
import h5wasm from "h5wasm";
import {CatalogDepthSource,CatalogEncSource,CoopsSource,DEPTH_SOURCE_PRIORITY,Era5Source,GEBCO_GRID_SPACING_DEG,GebcoOpendapAdapter,GeographyCoverageService,GeographyResolver,NdbcSource,NomadsRtofsGridDecoder,NwsSource,RtofsSource,gebcoGridIndex,resolveGeographicRegion,type DepthCatalogRecord,type DepthSourceId,type TextFetcher,type WeatherSource} from "../../packages/environment/src/index.ts";

const sha=(value:unknown)=>createHash("sha256").update(typeof value==="string"?value:canonical(value)).digest("hex");
const canonical=(value:unknown):string=>JSON.stringify(value,(_key,item)=>item&&typeof item==="object"&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b))):item);
const clock=()=>Number(process.hrtime.bigint())/1e6;
const RETRIEVED="2026-08-24T12:00:00.000Z";
const sites=[
  {id:"san-francisco",latitude_deg:37.806,longitude_deg:-122.465,depth:22},
  {id:"honolulu",latitude_deg:21.289,longitude_deg:-157.865,depth:34},
  {id:"miami",latitude_deg:25.731,longitude_deg:-80.162,depth:18},
  {id:"boston",latitude_deg:42.354,longitude_deg:-70.989,depth:27},
] as const;
const timestamps=["2026-01-15T12:00:00.000Z","2026-07-15T12:00:00.000Z"];
const ndbc=(time:string)=>{const d=new Date(time);return `#YY MM DD hh mm WDIR WSPD GST WVHT DPD MWD PRES ATMP WTMP\n#yr mo dy hr mn degT m/s m/s m sec degT hPa degC degC\n${d.getUTCFullYear()} ${String(d.getUTCMonth()+1).padStart(2,"0")} ${String(d.getUTCDate()).padStart(2,"0")} ${String(d.getUTCHours()).padStart(2,"0")} 00 270 8 10 1.8 7 250 1013 19 16`;};
const cell=(site:typeof sites[number],resolution=.25)=>`${Math.round(site.latitude_deg/resolution)*resolution},${Math.round(site.longitude_deg/resolution)*resolution}@${resolution}deg`;
const dataset:Record<string,string>={ndbc:"NDBC-standard-meteorological",coops:"CO-OPS-water-level",nws:"NWS-forecast-grid-data",rtofs:"RTOFS-global-2D",era5:"reanalysis-era5-single-levels"};

function sourceFor(id:string,site:typeof sites[number],time:string,rtofsBytes?:ArrayBuffer):WeatherSource{
  const station={id:`${id}-${site.id}`,position:site};
  const fetcher:TextFetcher=async url=>{
    if(url.includes("api.weather.gov/points"))return{text:async()=>"",json:async()=>({properties:{forecastGridData:"https://fixture.test/nws-grid",gridId:`GRID-${site.id}`,gridX:12,gridY:34}})};
    if(url.includes("nws-grid"))return{text:async()=>"",json:async()=>({properties:{updateTime:time,windSpeed:{values:[{validTime:`${time}/PT1H`,value:6}]},windDirection:{values:[{validTime:`${time}/PT1H`,value:180}]},temperature:{values:[{validTime:`${time}/PT1H`,value:20}]},barometricPressure:{values:[{validTime:`${time}/PT1H`,value:101000}]}}})};
    if(url.includes("tidesandcurrents"))return{text:async()=>"",json:async()=>({data:[{t:time.slice(0,16).replace("T"," "),v:"1.2"}]})};
    return{text:async()=>ndbc(time),json:async()=>({})};
  };
  if(id==="ndbc")return new NdbcSource([station],fetcher);
  if(id==="coops")return new CoopsSource([station],fetcher);
  if(id==="nws")return new NwsSource({application:"BCOD coverage matrix",contact:"test@example.test"},fetcher);
  if(id==="rtofs"){if(!rtofsBytes)throw new Error("RTOFS HDF5 fixture missing");const cycle=time.slice(0,10).replaceAll("-","")+"T00Z";return new RtofsSource(new NomadsRtofsGridDecoder(cycle,undefined,async()=>new Response(rtofsBytes,{status:200})));}
  process.env.BCOD_COVERAGE_CDS_SENTINEL="coverage-only-sentinel";
  let submitted=0;
  return new Era5Source({credentials:{source:"environment",env_var:"BCOD_COVERAGE_CDS_SENTINEL"},transport:{submit:async()=>`job-${++submitted}`,status:async()=>({status:"successful"}),download:async()=>new ArrayBuffer(8)},decoder:{decode:async()=>({grid_id:`era5:${cell(site)}`,grid_ids:[`era5-atmosphere:${cell(site)}`,`era5-wave:${cell(site,.5)}`],valid_time:time,u10_mps:4,v10_mps:5,air_temperature_k:289.15,significant_wave_height_m:2})},now:()=>new Date(RETRIEVED)});
}

type MatrixCell={source:string;site:string;coordinates:{latitude_deg:number;longitude_deg:number};timestamp:string;success:boolean;retrieval_latency_ms:number;provenance_complete:boolean;provenance:{dataset_id:string|null;timestamp:string|null;retrieval_date:string|null;native_grid_cell:string|null};artifact_checksum_sha256:string;methodology:string;notes:string[]};
async function rtofsFixture(site:typeof sites[number],time:string){const {FS}=await h5wasm.ready,path=`/coverage-rtofs-${site.id}-${time.slice(0,10)}.nc`,height=3,width=3,file=new h5wasm.File(path,"w"),grid=(fn:(y:number,x:number)=>number)=>Float32Array.from({length:height*width},(_,i)=>fn(Math.floor(i/width),i%width)),days=(Date.parse(time)-Date.UTC(1900,11,31))/86400_000;file.create_dataset({name:"Latitude",data:grid(y=>site.latitude_deg+(y-1)*.1),shape:[height,width],dtype:"<f4"});file.create_dataset({name:"Longitude",data:grid((_y,x)=>site.longitude_deg+(x-1)*.1),shape:[height,width],dtype:"<f4"});for(const[name,value]of [["u_velocity",.1],["v_velocity",.3]]as const)file.create_dataset({name,data:grid(()=>value),shape:[1,1,height,width],dtype:"<f4"});for(const[name,value]of [["sst",17],["sss",34]]as const)file.create_dataset({name,data:grid(()=>value),shape:[1,height,width],dtype:"<f4"});file.create_dataset({name:"MT",data:new Float64Array([days]),shape:[1],dtype:"<f8"});file.close();const bytes=FS.readFile(path),copy=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)as ArrayBuffer;FS.unlink(path);return copy;}
async function weatherMatrix():Promise<MatrixCell[]>{const out:MatrixCell[]=[];for(const id of ["ndbc","coops","nws","rtofs","era5"] as const)for(const site of sites)for(const time of timestamps){const source=sourceFor(id,site,time,id==="rtofs"?await rtofsFixture(site,time):undefined),mode=id==="era5"?"historical_replay":"realtime_forecast",start=clock();try{const result=await source.query(site,time,mode),latency=clock()-start,p=result?.provenance,datasetId=p?.dataset_product??dataset[id]??null,native=p?.grid_cells?.join("|")??p?.station_or_grid_id??null,provenance={dataset_id:datasetId,timestamp:p?.observation_or_valid_time??null,retrieval_date:p?.retrieval_date??null,native_grid_cell:native},complete=Object.values(provenance).every(Boolean),payload={patch:result?.patch??null,provenance};out.push({source:id,site:site.id,coordinates:site,timestamp:time,success:Boolean(result)&&complete,retrieval_latency_ms:Number(latency.toFixed(3)),provenance_complete:complete,provenance,artifact_checksum_sha256:sha(payload),methodology:"measured-deterministic-injected-transport",notes:[id==="rtofs"?"Exercises the production NetCDF4/HDF5 binary decoder against a real-schema fixture.":"Exercises production adapter parsing/composition boundary; does not measure public-provider network availability."]});}catch(error){out.push({source:id,site:site.id,coordinates:site,timestamp:time,success:false,retrieval_latency_ms:Number((clock()-start).toFixed(3)),provenance_complete:false,provenance:{dataset_id:dataset[id],timestamp:null,retrieval_date:null,native_grid_cell:null},artifact_checksum_sha256:sha({error:String(error)}),methodology:"measured-deterministic-injected-transport",notes:[String(error)]});}}return out;}

function provenance(source:DepthSourceId,site:typeof sites[number],offset:number){return{source,product:`${source}-${site.id}`,retrieval_date:RETRIEVED,survey_date:"2025-06-01",native_resolution_m:source==="gebco"?450:source==="cudem"?30:source==="estuarine_dem"?10:source==="lidar"?1:.5,coverage:`fixture:${site.id}`,checksum_sha256:sha({source,site:site.id}),crs:"EPSG:4326",transformations:["WGS84 to local NED"],native_grid_cell:`${source}:${cell(site)}`,depth_offset_m:offset};}
const gebcoAscii=(variable:string,value:number,site:typeof sites[number])=>{const index=gebcoGridIndex(site),lat=-90+(index.latitude_index+.5)*GEBCO_GRID_SPACING_DEG,lon=-180+(index.longitude_index+.5)*GEBCO_GRID_SPACING_DEG;return`Dataset { fixture } fixture;\n---------------------------------------------\nlat[1]\n${lat}\n\nlon[1]\n${lon}\n\n${variable}[1][1]\n[0], ${value}\n`;};
async function bathymetryMatrix(){const cells:MatrixCell[]=[],overlaps:any[]=[];for(let si=0;si<sites.length;si++){const site=sites[si],region=resolveGeographicRegion({kind:"center_extent",center:site,extent_north_m:100,extent_east_m:100});for(let ti=0;ti<timestamps.length;ti++){const time=timestamps[ti],winnerIndex=(si*2+ti)%DEPTH_SOURCE_PRIORITY.length,winner=DEPTH_SOURCE_PRIORITY[winnerIndex],gebco=winner==="gebco"?await new GebcoOpendapAdapter(async url=>({ok:true,text:async()=>url.includes("tid.nc")?gebcoAscii("tid.tid",70,site):gebcoAscii("elevation.elevation",-site.depth,site)}),()=>new Date(RETRIEVED)).query(site):null,records=DEPTH_SOURCE_PRIORITY.map((source,index)=>{const covered=index>=winnerIndex,offset=(index-winnerIndex)*.4,p=provenance(source,site,offset),depth=source==="gebco"&&gebco?gebco.water_depth_m!:site.depth+offset,record:DepthCatalogRecord={source,covered,nativeResolutionM:p.native_resolution_m,surveyDate:source==="gebco"&&gebco?gebco.retrieval_date:"2025-06-01",tileOrDatasetId:`${source}-${site.id}-${ti}`,provenance:{...p,...source==="gebco"&&gebco?{product:gebco.dataset_id,retrieval_date:gebco.retrieval_date,survey_date:gebco.retrieval_date,native_grid_cell:gebco.native_grid_cell,tid_code:gebco.tid_code,tid_source:gebco.tid_source,elevation_m:gebco.elevation_m}:{}},value:{water_depth_m:depth,elevation_m:-depth,navigable:true}};return new CatalogDepthSource(source,[record]);}),service=new GeographyCoverageService(records,new CatalogEncSource([])),start=clock(),resolved=new GeographyResolver(service).resolve(region),sample=resolved.query_water_depth([0,0,0]),latency=clock()-start,p=sample.provenance as any,native=p?.native_grid_cell??null,prov={dataset_id:p?.product??null,timestamp:p?.survey_date??null,retrieval_date:p?.retrieval_date??null,native_grid_cell:native},payload={depth:sample.water_depth_m,provenance:prov};cells.push({source:"bathymetry_cascade",site:site.id,coordinates:site,timestamp:time,success:sample.status==="resolved"&&winner===(p?.source??null),retrieval_latency_ms:Number(latency.toFixed(3)),provenance_complete:Object.values(prov).every(Boolean),provenance:prov,artifact_checksum_sha256:sha(payload),methodology:"measured-deterministic-catalog-fixture",notes:[`cascade_source=${String(p?.source)}`,...winner==="gebco"?[`GEBCO_2026 OPeNDAP fixture decoded with TID ${p?.tid_code} (${p?.tid_source}).`]:[]]});const values=DEPTH_SOURCE_PRIORITY.slice(winnerIndex).map((source,index)=>({source,depth_m:source==="gebco"&&gebco?gebco.water_depth_m!:site.depth+index*.4})),reference=values[0];for(const candidate of values.slice(1))overlaps.push({site:site.id,reference_source:reference.source,candidate_source:candidate.source,difference_m:candidate.depth_m-reference.depth_m});}}
  const byPair=Object.values(Object.groupBy(overlaps,(x:any)=>`${x.reference_source}__${x.candidate_source}`)).map((rows:any)=>({reference_source:rows[0].reference_source,candidate_source:rows[0].candidate_source,n:rows.length,bias_m:rows.reduce((s:number,x:any)=>s+x.difference_m,0)/rows.length,rmse_m:Math.sqrt(rows.reduce((s:number,x:any)=>s+x.difference_m**2,0)/rows.length)}));return{cells,overlap_agreement:byPair};}

type Fault="offline"|"http_429"|"timeout"|"partial_response"|"malformed_payload";
const faults:Fault[]=["offline","http_429","timeout","partial_response","malformed_payload"];
const faultError=(fault:Fault)=>fault==="offline"?new Error("network offline"):fault==="http_429"?new Error("HTTP 429 Too Many Requests"):fault==="timeout"?new Error("retrieval timed out"):fault==="partial_response"?new Error("partial response rejected"):new SyntaxError("malformed payload rejected");
async function failureInjection(){const rows:any[]=[];for(const id of ["ndbc","coops","nws","rtofs","era5","bathymetry_cascade"] as const)for(const fault of faults){let produced=false,error="";try{if(id==="rtofs"){const value=await new RtofsSource({query:async()=>{throw faultError(fault);}}).query(sites[0],timestamps[0],"realtime_forecast");produced=Boolean(value);}else if(id==="era5"){process.env.BCOD_COVERAGE_CDS_SENTINEL="never-serialize-this";const value=await new Era5Source({credentials:{source:"environment",env_var:"BCOD_COVERAGE_CDS_SENTINEL"},transport:{submit:async()=>{throw faultError(fault);},status:async()=>({status:"failed"}),download:async()=>new ArrayBuffer(0)},decoder:{decode:async()=>{throw faultError(fault);}}}).query(sites[0],timestamps[0],"historical_replay");produced=Boolean(value);}else if(id==="bathymetry_cascade"){const region=resolveGeographicRegion({kind:"center_extent",center:sites[0],extent_north_m:10,extent_east_m:10}),sources=DEPTH_SOURCE_PRIORITY.map(source=>new CatalogDepthSource(source,[{source,covered:true,nativeResolutionM:1,surveyDate:"2025-01-01",tileOrDatasetId:source,provenance:provenance(source,sites[0],0),value:{water_depth_m:10,elevation_m:-10,navigable:true}}]));(sources[0] as any).fetchCell=()=>{throw faultError(fault);};new GeographyResolver(new GeographyCoverageService(sources,new CatalogEncSource([]))).resolve(region);produced=true;}else{const bad:TextFetcher=async()=>{if(fault==="offline"||fault==="http_429"||fault==="timeout")throw faultError(fault);if(fault==="malformed_payload"&&id!=="ndbc")return{text:async()=>"{not-json",json:async()=>{throw new SyntaxError("malformed JSON payload rejected");}};if(id==="ndbc")return{text:async()=>fault==="partial_response"?"#YY MM DD hh":"not an NDBC table",json:async()=>({})};return{text:async()=>"",json:async()=>fault==="partial_response"?{}:{unexpected:true}};},source=id==="ndbc"?new NdbcSource([{id:"x",position:sites[0]}],bad):id==="coops"?new CoopsSource([{id:"x",position:sites[0]}],bad):new NwsSource({application:"coverage",contact:"test@example.test"},bad),value=await source.query(sites[0],timestamps[0],"realtime_forecast");produced=Boolean(value);if(!value)error=`${fault} produced explicit no-data result`;}}catch(cause){error=cause instanceof Error?cause.message:String(cause);}rows.push({source:id,fault,pass:!produced&&Boolean(error),visible_failure:Boolean(error),bad_data_reached_simulator:produced,error,artifact_checksum_sha256:sha({id,fault,error})});}return rows;}

function credentialLeaks(value:unknown,path="$",hits:string[]=[]):string[]{if(typeof value==="string"){const patterns=[/AKIA[0-9A-Z]{16}/,/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,/(?:bearer|basic)\s+[A-Za-z0-9+/_=-]{12,}/i,/https?:\/\/[^\s:@]+:[^\s@]+@/];if(patterns.some(p=>p.test(value))||value.includes("coverage-only-sentinel")||value.includes("never-serialize-this"))hits.push(path);}else if(Array.isArray(value))value.forEach((x,i)=>credentialLeaks(x,`${path}[${i}]`,hits));else if(value&&typeof value==="object")for(const[k,v]of Object.entries(value))credentialLeaks(v,`${path}.${k}`,hits);return hits;}
export async function runEnvironmentCoverage(){const weather=await weatherMatrix(),bathymetry=await bathymetryMatrix(),failures=await failureInjection(),artifact:any={schema_version:1,artifact_kind:"environmental-source-coverage-and-failure-injection",generated_at:RETRIEVED,methodology:{coverage:"deterministic injected transports/catalogs exercising production adapters; not a live-provider availability benchmark",latency:"wall-clock adapter retrieval/parse/cascade latency on local injected fixtures",timestamps,sites:sites.map(({id,latitude_deg,longitude_deg})=>({id,latitude_deg,longitude_deg}))},coverage_matrix:[...weather,...bathymetry.cells],bathymetry_overlap_agreement:bathymetry.overlap_agreement,failure_injection:failures};delete process.env.BCOD_COVERAGE_CDS_SENTINEL;const hits=credentialLeaks(artifact);artifact.credential_leak_scan={scanner:"recursive string-value scan: cloud keys, authorization values, URL credentials, private keys, injected sentinels",files_scanned:1,findings:hits,pass:hits.length===0};artifact.summary={coverage_cells:artifact.coverage_matrix.length,coverage_passed:artifact.coverage_matrix.filter((x:MatrixCell)=>x.success&&x.provenance_complete).length,failure_cells:failures.length,failure_injection_passed:failures.filter(x=>x.pass).length,credential_scan_passed:hits.length===0};assert.equal(artifact.summary.coverage_passed,artifact.summary.coverage_cells);assert.equal(artifact.summary.failure_injection_passed,artifact.summary.failure_cells);assert.equal(hits.length,0);return artifact;}
export function writeEnvironmentCoverage(path="artifacts/environment-coverage/coverage-matrix.json",artifact?:unknown){const output=resolve(path),value=artifact??null;mkdirSync(dirname(output),{recursive:true});writeFileSync(output,`${JSON.stringify(value,null,2)}\n`);return output;}
if(process.argv[1]===fileURLToPath(import.meta.url)){const artifact=await runEnvironmentCoverage(),output=writeEnvironmentCoverage(process.argv[2],artifact);console.log(JSON.stringify({output,summary:artifact.summary},null,2));}
