import {createHash} from "node:crypto";
import {mkdirSync,writeFileSync} from "node:fs";
import {dirname,resolve} from "node:path";
import {fileURLToPath} from "node:url";
import {resolveExperiment} from "../../packages/experiment-schema/src/index.ts";
import {HeadlessMarineSimulation} from "../../packages/core/src/simulation.ts";
import {LegacyProductionEngine} from "../../backends/node/src/legacy-production-engine.ts";

export function runVehicleBProduction(){const config=resolveExperiment({schema_version:1,experiment:{name:"vehicle-b-production-coupled6",seed:2027,timestep_s:.02,duration_s:6},backend:{type:"node"},vehicle:{preset:"vehicle-b-rudder",plant:"coupled6"},mission:{type:"production-integration"},outputs:{state_hz:10}}),sim=new HeadlessMarineSimulation(new LegacyProductionEngine());sim.reset(config);const trace=[],max={heave_m:0,roll_rad:0,pitch_rad:0};let result:any;for(let step=0;step<300;step++){const command=step<100?{propeller_rps:15,rudder_rad:0}:step<200?{propeller_rps:18,rudder_rad:.2}:{propeller_rps:10,rudder_rad:-.15};result=sim.step({actuators:command});const truth=sim.getGroundTruth() as any;max.heave_m=Math.max(max.heave_m,Math.abs(truth.position_ned_m[2]));max.roll_rad=Math.max(max.roll_rad,Math.abs(truth.attitude_rad[0]));max.pitch_rad=Math.max(max.pitch_rad,Math.abs(truth.attitude_rad[1]));trace.push({step,time_s:truth.time_s,position_ned_m:truth.position_ned_m,attitude_rad:truth.attitude_rad,velocity_body_mps:truth.velocity_body_mps,angular_rate_body_rad_s:truth.angular_rate_body_rad_s,applied_command:result.info.vehicle_diagnostics.applied_command,full_wrench:result.info.vehicle_diagnostics.full_wrench});}const encoded=JSON.stringify(trace),artifact={schema_version:1,artifact_kind:"vehicle-b-production-coupled6-integration",status:"integration-passed-dynamics-unvalidated",is_behavioral_validation_evidence:false,vehicle_path:result.info.vehicle_path,scenario:{steps:300,dt_s:.02,duration_s:6,command_segments:[{steps:[0,99],propeller_rps:15,rudder_rad:0},{steps:[100,199],propeller_rps:18,rudder_rad:.2},{steps:[200,299],propeller_rps:10,rudder_rad:-.15}]},checks:{finite_trace:trace.every((sample)=>Object.values(sample).flat(Infinity).filter((value)=>typeof value==="number").every(Number.isFinite)),coupled6_out_of_plane_dofs_free:max.roll_rad>0&&max.pitch_rad>0,mmg_force_components_present:Boolean(result.info.vehicle_diagnostics.force_components.hull&&result.info.vehicle_diagnostics.force_components.propeller&&result.info.vehicle_diagnostics.force_components.rudder)},out_of_plane_maxima:max,final_state:trace.at(-1),trace_checksum_sha256:createHash("sha256").update(encoded).digest("hex"),claim_limit:"Confirms production wiring and numerical execution only. Vehicle B USV-scale maneuvering and damping coefficients remain unvalidated.",limitations:["USV MMG coefficients are engineering bootstrap estimates.","Capytaine coefficients use a bootstrap mesh and fixed-frequency approximation.","No independent Vehicle B trajectory or free-decay reference is compared."]};sim.dispose();if(!Object.values(artifact.checks).every(Boolean))throw new Error("Vehicle B production integration checks failed.");return artifact;}
if(process.argv[1]===fileURLToPath(import.meta.url)){const output=resolve(process.argv[2]??"artifacts/vehicle-b/production-coupled6-integration.json"),artifact=runVehicleBProduction();mkdirSync(dirname(output),{recursive:true});writeFileSync(output,`${JSON.stringify(artifact,null,2)}\n`);console.log(JSON.stringify({output,status:artifact.status,checks:artifact.checks,trace_checksum_sha256:artifact.trace_checksum_sha256},null,2));}
