import {compareTrajectory,type ComparisonMetrics,type ReferenceTrajectory,type TrajectorySample} from "./trajectory.ts";
export interface Coupled6ReferenceRunner {readonly plant:"coupled6";readonly constrained_dofs:ReadonlyArray<"surge"|"sway"|"heave"|"roll"|"pitch"|"yaw">;resetHydrostaticEquilibrium():void;stepAppliedWrench(wrench:[number,number,number,number,number,number],dt:number):TrajectorySample}
export interface ValidationArtifact {protocol:string;claim:string;limitations:string[];constraints:{dof:string;reason:string}[];primary_evidence:boolean;metrics:ComparisonMetrics}
export function runAero4RiverProtocol(reference:ReferenceTrajectory,runner:Coupled6ReferenceRunner):ValidationArtifact{
  if(reference.metadata.reference!=="AERO4River")throw new Error("AERO4River protocol requires an AERO4River reference trajectory.");
  if(runner.plant!=="coupled6")throw new Error("AERO4River evidence must execute through coupled6.");
  runner.resetHydrostaticEquilibrium();const samples:TrajectorySample[]=[];
  for(let i=0;i<reference.samples.length;i++){const current=reference.samples[i],previous=reference.samples[Math.max(0,i-1)];const dt=i===0?0:current.time_s-previous.time_s;const planar=previous.input_wrench_body_n_nm??[0,0,0,0,0,0];samples.push(runner.stepAppliedWrench([planar[0],planar[1],0,0,0,planar[5]],dt));}
  const actual:ReferenceTrajectory={metadata:{...reference.metadata,reference:"BCOD",notes:[...reference.metadata.notes,"Executed through coupled6; comparison projects surge/sway/yaw while retaining out-of-plane diagnostics."]},samples};
  const constraints=runner.constrained_dofs.map((dof)=>({dof,reason:"Runner declared constraint; run cannot support primary Vehicle C evidence."}));
  return{protocol:"aero4river-coupled6-applied-wrench",claim:"Applied-wrench surge/sway/yaw response through coupled6 only.",limitations:["Does not validate dual water-azimuth propulsion.","No measured heave/roll/pitch reference channels."],constraints,primary_evidence:constraints.length===0,metrics:compareTrajectory(reference,actual)};
}
export type ImoManeuverMetricName="advance"|"tactical-diameter"|"first-overshoot"|"second-overshoot";
export interface PublishedManeuverMetric {name:ImoManeuverMetricName;published_value:number;unit:"L"|"deg";tolerance_percent:number;source_location:string}
export interface ManeuverMetricResult extends PublishedManeuverMetric {actual_value:number;absolute_percent_error:number;passed:boolean}
export interface ManeuveringStructureArtifact {artifact_kind:"kvlcc2-mmg-reference-reproduction"|"vehicle-b-usv-parameterization";evidence_status:"reference-reproduction-only"|"usv-parameterization-unvalidated";stage:"model-structure"|"usv-scale";reference:"YASUKAWA_YOSHIMURA_2015"|"SIMMAN"|"VEHICLE_B_USV";parameter_set_id:string;source_vessel:"KVLCC2"|"KCS"|"Vehicle-B-USV";claim:string;may_validate_usv_coefficients:boolean}
export function validateVehicleBStages(structure:ManeuveringStructureArtifact,usv:ManeuveringStructureArtifact):void{if(structure.artifact_kind!=="kvlcc2-mmg-reference-reproduction"||structure.evidence_status!=="reference-reproduction-only")throw new Error("Vehicle B Stage 1 must be labeled as KVLCC2 MMG reference reproduction only.");if(structure.stage!=="model-structure"||!["KVLCC2","KCS"].includes(structure.source_vessel))throw new Error("Vehicle B Stage 1 must use published KVLCC2 or KCS model-structure parameters.");if(structure.may_validate_usv_coefficients)throw new Error("Commercial-vessel evidence cannot validate USV coefficients.");if(usv.artifact_kind!=="vehicle-b-usv-parameterization"||usv.evidence_status!=="usv-parameterization-unvalidated"||usv.stage!=="usv-scale"||usv.source_vessel!=="Vehicle-B-USV"||usv.reference!=="VEHICLE_B_USV")throw new Error("Stage 2 must use an independent, unvalidated Vehicle B USV parameterization.");if(structure.parameter_set_id===usv.parameter_set_id)throw new Error("Commercial-vessel coefficients must not transfer into Vehicle B.");}
export function comparePublishedManeuverMetrics(reference:PublishedManeuverMetric[],actual:Partial<Record<ImoManeuverMetricName,number>>):{passed:boolean;comparison_basis:"published-imo-scalar-metrics";trajectory_overlays_gating:false;results:ManeuverMetricResult[]}{
  const required:ImoManeuverMetricName[]=["advance","tactical-diameter","first-overshoot","second-overshoot"];
  if(reference.length!==required.length||required.some((name)=>!reference.some((metric)=>metric.name===name)))throw new Error("Stage 1 requires all published scalar maneuver metric categories available in Tables 4-5.");
  const results=reference.map((metric)=>{const value=actual[metric.name];if(!Number.isFinite(metric.published_value)||metric.published_value===0||!Number.isFinite(metric.tolerance_percent)||metric.tolerance_percent<=0||!metric.source_location)throw new Error(`Invalid published metric contract for ${metric.name}.`);if(!Number.isFinite(value))throw new Error(`Missing reproduced metric ${metric.name}.`);const absolute_percent_error=Math.abs((value!-metric.published_value)/metric.published_value)*100;return{...metric,actual_value:value!,absolute_percent_error,passed:absolute_percent_error<=metric.tolerance_percent};});
  return{passed:results.every((result)=>result.passed),comparison_basis:"published-imo-scalar-metrics",trajectory_overlays_gating:false,results};
}
