import {NetCDFReader} from "netcdfjs";
import type {Attribute} from "netcdfjs";
import type {Wgs84Position} from "./geography.ts";
import type {WeatherPatch,WeatherProvenance,WeatherSourceResult} from "./weather.ts";

export type Era5CredentialConfig={source:"environment";env_var:string}|{source:"file";path:string};
export interface Era5Credentials{url:string;key:string}
export interface Era5JobTransport{
  submit(dataset:string,request:Record<string,unknown>,credentials:Era5Credentials):Promise<string>;
  status(jobId:string,credentials:Era5Credentials):Promise<{status:"accepted"|"running"|"successful"|"failed"|"rejected";message?:string}>;
  download(jobId:string,credentials:Era5Credentials):Promise<ArrayBuffer>;
}
export interface Era5DecodedCell{grid_id:string;grid_ids?:string[];valid_time:string;u10_mps?:number;v10_mps?:number;mean_sea_level_pressure_pa?:number;air_temperature_k?:number;total_precipitation_m?:number;significant_wave_height_m?:number;sea_surface_temperature_k?:number}
export interface Era5Decoder{decode(files:ArrayBuffer[],point:Wgs84Position,time:string):Promise<Era5DecodedCell>}
export interface Era5SourceOptions{credentials:Era5CredentialConfig;transport?:Era5JobTransport;decoder?:Era5Decoder;timeoutMs?:number;pollInitialMs?:number;pollMaxMs?:number;now?:()=>Date;sleep?:(ms:number)=>Promise<void>}

function parseCredentialText(text:string):Era5Credentials{const url=text.match(/^\s*url\s*:\s*(.+)\s*$/m)?.[1]?.trim()??"https://cds.climate.copernicus.eu/api",key=text.match(/^\s*key\s*:\s*(.+)\s*$/m)?.[1]?.trim();if(!key)throw new Error("CDS API key not configured");return{url,key};}
export async function loadEra5Credentials(config:Era5CredentialConfig):Promise<Era5Credentials>{
  if(config.source==="environment"){const value=(globalThis as any).process?.env?.[config.env_var];if(!value?.trim())throw new Error("CDS API key not configured");return{url:"https://cds.climate.copernicus.eu/api",key:value.trim()};}
  try{const moduleName="node:fs/promises",fs=await import(/* @vite-ignore */moduleName),path=config.path.startsWith("~/")?`${(globalThis as any).process?.env?.HOME??""}/${config.path.slice(2)}`:config.path;return parseCredentialText(await fs.readFile(path,"utf8"));}catch(error){if(error instanceof Error&&error.message==="CDS API key not configured")throw error;throw new Error("CDS API key not configured");}
}

export class CdsRestJobTransport implements Era5JobTransport{
  readonly fetcher:typeof fetch;constructor(fetcher:typeof fetch=fetch){this.fetcher=fetcher;}
  #headers(credentials:Era5Credentials){return{"PRIVATE-TOKEN":credentials.key,"Content-Type":"application/json"};}
  async #request(url:string,init?:RequestInit){let response:Response|undefined;for(let attempt=0;attempt<4;attempt++){response=await this.fetcher(url,init);if(response.status!==429&&response.status<500)return response;if(attempt<3)await new Promise(resolve=>setTimeout(resolve,500*2**attempt));}return response!;}
  async #failure(operation:string,response:Response){let detail="";try{const body=await response.json() as any;detail=body.detail??body.title??body.message??"";}catch{}return new Error(`CDS ${operation} failed: HTTP ${response.status}${detail?` — ${detail}`:""}`);}
  async submit(dataset:string,request:Record<string,unknown>,credentials:Era5Credentials){const response=await this.#request(`${credentials.url}/retrieve/v1/processes/${dataset}/execution`,{method:"POST",headers:this.#headers(credentials),body:JSON.stringify({inputs:request})});if(!response.ok)throw await this.#failure("submission",response);const body=await response.json() as any,id=body.jobID??body.job_id??body.id??response.headers.get("Location")?.split("/").at(-1);if(!id)throw new Error("CDS submission returned no job id.");return id;}
  async status(jobId:string,credentials:Era5Credentials){const response=await this.#request(`${credentials.url}/retrieve/v1/jobs/${jobId}`,{headers:this.#headers(credentials)});if(!response.ok)throw await this.#failure("status",response);const body=await response.json() as any;return{status:body.status,message:body.message};}
  async download(jobId:string,credentials:Era5Credentials){const response=await this.#request(`${credentials.url}/retrieve/v1/jobs/${jobId}/results`,{headers:this.#headers(credentials)});if(!response.ok)throw await this.#failure("results",response);const body=await response.json() as any,href=body.asset?.value?.href??body.assets?.[0]?.href??body.links?.find((x:any)=>x.rel==="download")?.href;if(!href)throw new Error("CDS results returned no download asset.");const file=await this.#request(href,{headers:{"PRIVATE-TOKEN":credentials.key}});if(!file.ok)throw await this.#failure("download",file);return file.arrayBuffer();}
}

function attribute(attributes:readonly Attribute[],...names:string[]):Attribute|undefined{return attributes.find(item=>names.includes(item.name));}
function scalar(reader:NetCDFReader,names:string[]):number|undefined{for(const name of names){try{const variable=reader.variables.find(item=>item.name===name);if(!variable)continue;const values=reader.getDataVariable(name) as ArrayLike<number>,attributes:readonly Attribute[]=variable.attributes,missing=attribute(attributes,"missing_value","_FillValue")?.value,raw=Array.from(values).map(Number).find(value=>Number.isFinite(value)&&value!==missing);if(raw===undefined)continue;const scale=Number(attribute(attributes,"scale_factor")?.value??1),offset=Number(attribute(attributes,"add_offset")?.value??0);return raw*scale+offset;}catch{}}return undefined;}
function era5GridPoint(point:Wgs84Position,resolutionDeg=.25):Wgs84Position{return{latitude_deg:Math.round(point.latitude_deg/resolutionDeg)*resolutionDeg,longitude_deg:Math.round(point.longitude_deg/resolutionDeg)*resolutionDeg};}
function gridId(point:Wgs84Position){return`era5:${point.latitude_deg.toFixed(2)},${point.longitude_deg.toFixed(2)}`;}
export class Era5NetcdfDecoder implements Era5Decoder{async decode(files:ArrayBuffer[],point:Wgs84Position,time:string){const atmosphereGrid=era5GridPoint(point),waveGrid=era5GridPoint(point,.5),merged:Era5DecodedCell={grid_id:gridId(atmosphereGrid),grid_ids:[gridId(atmosphereGrid),gridId(waveGrid)],valid_time:new Date(time).toISOString()};for(const file of files){const reader=new NetCDFReader(file);Object.assign(merged,{u10_mps:scalar(reader,["u10","10m_u_component_of_wind"])??merged.u10_mps,v10_mps:scalar(reader,["v10","10m_v_component_of_wind"])??merged.v10_mps,mean_sea_level_pressure_pa:scalar(reader,["msl","mean_sea_level_pressure"])??merged.mean_sea_level_pressure_pa,air_temperature_k:scalar(reader,["t2m","2m_temperature"])??merged.air_temperature_k,total_precipitation_m:scalar(reader,["tp","total_precipitation"])??merged.total_precipitation_m,significant_wave_height_m:scalar(reader,["swh","significant_height_of_combined_wind_waves_and_swell"])??merged.significant_wave_height_m,sea_surface_temperature_k:scalar(reader,["sst","sea_surface_temperature"])??merged.sea_surface_temperature_k});}return merged;}}

function request(time:string,point:Wgs84Position,variables:string[],resolutionDeg=.25){const date=new Date(time),pad=(x:number)=>String(x).padStart(2,"0"),grid=era5GridPoint(point,resolutionDeg),lat=grid.latitude_deg,lon=grid.longitude_deg;return{product_type:["reanalysis"],variable:variables,year:[String(date.getUTCFullYear())],month:[pad(date.getUTCMonth()+1)],day:[pad(date.getUTCDate())],time:[`${pad(date.getUTCHours())}:00`],area:[lat,lon,lat,lon],data_format:"netcdf_legacy",download_format:"unarchived"};}
export class Era5Source{
  readonly id="era5" as const;readonly options:Era5SourceOptions;
  constructor(options:Era5SourceOptions){this.options=options;}
  async #retrieve(dataset:string,selection:Record<string,unknown>,credentials:Era5Credentials){const transport=this.options.transport??new CdsRestJobTransport(),id=await transport.submit(dataset,selection,credentials),started=Date.now(),timeout=this.options.timeoutMs??30*60_000;let delay=this.options.pollInitialMs??1000;for(;;){const state=await transport.status(id,credentials);if(state.status==="successful")return transport.download(id,credentials);if(state.status==="failed"||state.status==="rejected")throw new Error(`CDS ERA5 job ${id} ${state.status}: ${state.message??"no detail"}`);if(Date.now()-started>=timeout)throw new Error(`CDS ERA5 job ${id} timed out after ${timeout} ms.`);await(this.options.sleep??((ms)=>new Promise(resolve=>setTimeout(resolve,ms))))(delay);delay=Math.min(delay*2,this.options.pollMaxMs??30_000);}}
  async query(point:Wgs84Position,time:string,mode:"realtime_forecast"|"historical_replay"):Promise<WeatherSourceResult|null>{if(mode!=="historical_replay")return null;const credentials=await loadEra5Credentials(this.options.credentials),dataset="reanalysis-era5-single-levels",atmosphere=request(time,point,["10m_u_component_of_wind","10m_v_component_of_wind","mean_sea_level_pressure","2m_temperature","total_precipitation","sea_surface_temperature"]),wave=request(time,point,["significant_height_of_combined_wind_waves_and_swell"],.5),files=await Promise.all([this.#retrieve(dataset,atmosphere,credentials),this.#retrieve(dataset,wave,credentials)]),cell=await(this.options.decoder??new Era5NetcdfDecoder()).decode(files,point,time),patch:WeatherPatch={atmosphere:{...cell.u10_mps!==undefined&&cell.v10_mps!==undefined?{wind_ned_mps:[cell.v10_mps,cell.u10_mps,0]}:{},...cell.mean_sea_level_pressure_pa!==undefined?{pressure_pa:cell.mean_sea_level_pressure_pa}:{},...cell.air_temperature_k!==undefined?{air_temperature_c:cell.air_temperature_k-273.15}:{},...cell.total_precipitation_m!==undefined?{rain_rate_mm_h:cell.total_precipitation_m*1000}:{}},water:{...cell.sea_surface_temperature_k!==undefined?{temperature_c:cell.sea_surface_temperature_k-273.15}:{}},surface:{...cell.significant_wave_height_m!==undefined?{significant_wave_height_m:cell.significant_wave_height_m}:{}}},retrieval=(this.options.now??(()=>new Date()))().toISOString(),provenance:WeatherProvenance={source:"era5",station_or_grid_id:cell.grid_id,retrieval_date:retrieval,observation_or_valid_time:cell.valid_time,distance_m:null,staleness_s:Math.max((Date.parse(time)-Date.parse(cell.valid_time))/1000,0),dataset_product:dataset,time_range:`${new Date(time).toISOString().slice(0,13)}:00:00Z`,grid_cells:cell.grid_ids??[cell.grid_id]};return{patch,kind:"grid",provenance};}
}
