import type{Wgs84Position}from"./geography.ts";

export const GEBCO_GRID_VERSION="GEBCO_2026"as const;
export const GEBCO_GRID_DOI="10.5285/4f68d5c7-45eb-f999-e063-7086abc036fa"as const;
export const GEBCO_GRID_SPACING_DEG=1/240;
export const GEBCO_GRID_SHAPE={latitude:43200,longitude:86400}as const;
const ROOT="https://dap.ceda.ac.uk/thredds/dodsC/bodc/gebco/global/gebco_2026",ELEVATION=`${ROOT}/ice_surface_elevation/netcdf/GEBCO_2026.nc`,TID=`${ROOT}/type_identifier_grid/netcdf/gebco_2026_tid.nc`;
export const GEBCO_TID_MEANINGS:Readonly<Record<number,string>>={0:"land",10:"singlebeam",11:"multibeam",12:"seismic",13:"isolated_sounding",14:"enc_sounding",15:"lidar",16:"optical",17:"combined_direct_measurements",40:"predicted_satellite_gravity",41:"algorithmic_interpolation",42:"chart_contour",43:"enc_contour",44:"bathymetric_sounding_constrained_grid",45:"predicted_airborne_gravity",46:"grounded_iceberg_draft",47:"grounded_argo_float",48:"animal_borne_logger",70:"pre_generated_mixed_source_grid",71:"unknown",72:"steering_point"};
export interface GebcoFetcher{(url:string):Promise<{ok?:boolean;status?:number;text():Promise<string>}>}
export interface GebcoGridIndex{latitude_index:number;longitude_index:number}
export interface GebcoQueryUrls{elevation:string;tid:string}
export interface GebcoCell{dataset_id:typeof GEBCO_GRID_VERSION;dataset_doi:typeof GEBCO_GRID_DOI;latitude_index:number;longitude_index:number;latitude_deg:number;longitude_deg:number;elevation_m:number;water_depth_m:number|null;status:"resolved"|"land";tid_code:number;tid_source:string;retrieval_date:string;native_grid_cell:string;response_checksums_sha256:{elevation:string;tid:string};query_urls:GebcoQueryUrls}
const clamp=(x:number,min:number,max:number)=>Math.max(min,Math.min(max,x));
export function gebcoGridIndex(point:Wgs84Position):GebcoGridIndex{if(!Number.isFinite(point.latitude_deg)||!Number.isFinite(point.longitude_deg)||point.latitude_deg< -90||point.latitude_deg>90)throw new Error("GEBCO query requires finite WGS84 latitude/longitude.");const longitude=((point.longitude_deg+180)%360+360)%360-180;return{latitude_index:clamp(Math.floor((point.latitude_deg+90)/GEBCO_GRID_SPACING_DEG),0,GEBCO_GRID_SHAPE.latitude-1),longitude_index:clamp(Math.floor((longitude+180)/GEBCO_GRID_SPACING_DEG),0,GEBCO_GRID_SHAPE.longitude-1)};}
const constraint=(variable:string,y0:number,y1:number,x0:number,x1:number)=>`lat[${y0}:1:${y1}],lon[${x0}:1:${x1}],${variable}[${y0}:1:${y1}][${x0}:1:${x1}]`;
export function gebcoConstraintUrls(point:Wgs84Position,radius=0):GebcoQueryUrls{if(!Number.isInteger(radius)||radius<0)throw new Error("GEBCO subset radius must be a non-negative integer.");const{latitude_index:y,longitude_index:x}=gebcoGridIndex(point),y0=clamp(y-radius,0,GEBCO_GRID_SHAPE.latitude-1),y1=clamp(y+radius,0,GEBCO_GRID_SHAPE.latitude-1),x0=clamp(x-radius,0,GEBCO_GRID_SHAPE.longitude-1),x1=clamp(x+radius,0,GEBCO_GRID_SHAPE.longitude-1);return{elevation:`${ELEVATION}.ascii?${constraint("elevation",y0,y1,x0,x1)}`,tid:`${TID}.ascii?${constraint("tid",y0,y1,x0,x1)}`};}
function section(text:string,label:string){const escaped=label.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),match=text.match(new RegExp(`(?:^|\\n)${escaped}\\[[^\\n]*\\]\\n([^\\n]+)`));if(!match)throw new Error(`GEBCO OPeNDAP response is missing ${label}.`);return match[1];}
function scalar(text:string,label:string){const row=section(text,label),value=Number(row.replace(/^\[\d+\],\s*/,"").split(",")[0]);if(!Number.isFinite(value))throw new Error(`GEBCO OPeNDAP ${label} value is not finite.`);return value;}
async function checksum(text:string){const bytes=new TextEncoder().encode(text),digest=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("");}
export class GebcoOpendapAdapter{readonly fetcher:GebcoFetcher;readonly now:()=>Date;constructor(fetcher:GebcoFetcher=fetch as any,now:()=>Date=()=>new Date()){this.fetcher=fetcher;this.now=now;}async query(point:Wgs84Position):Promise<GebcoCell>{const index=gebcoGridIndex(point),query_urls=gebcoConstraintUrls(point),[elevationResponse,tidResponse]=await Promise.all([this.fetcher(query_urls.elevation),this.fetcher(query_urls.tid)]);for(const[name,response]of[["elevation",elevationResponse],["TID",tidResponse]]as const)if(response.ok===false)throw new Error(`GEBCO ${name} OPeNDAP query failed: HTTP ${response.status??"unknown"}`);const[elevationText,tidText]=await Promise.all([elevationResponse.text(),tidResponse.text()]),latitude_deg=scalar(elevationText,"lat"),longitude_deg=scalar(elevationText,"lon"),elevation_m=scalar(elevationText,"elevation.elevation"),tid_code=scalar(tidText,"tid.tid");if(scalar(tidText,"lat")!==latitude_deg||scalar(tidText,"lon")!==longitude_deg)throw new Error("GEBCO elevation and TID grids returned different native cells.");if(!Number.isInteger(tid_code)||tid_code===127)throw new Error(`GEBCO TID is missing or invalid (${tid_code}).`);const tid_source=GEBCO_TID_MEANINGS[tid_code];if(!tid_source)throw new Error(`GEBCO returned undocumented TID code ${tid_code}.`);const land=tid_code===0||elevation_m>=0;if((tid_code===0)!==land)throw new Error(`GEBCO elevation/TID land classification disagrees: elevation=${elevation_m}, TID=${tid_code}.`);return{dataset_id:GEBCO_GRID_VERSION,dataset_doi:GEBCO_GRID_DOI,...index,latitude_deg,longitude_deg,elevation_m,water_depth_m:land?null:-elevation_m,status:land?"land":"resolved",tid_code,tid_source,retrieval_date:this.now().toISOString(),native_grid_cell:`${GEBCO_GRID_VERSION}:lat[${index.latitude_index}],lon[${index.longitude_index}]`,response_checksums_sha256:{elevation:await checksum(elevationText),tid:await checksum(tidText)},query_urls};}}
