import type{BathymetryField,BathymetryQuery,BathymetrySample}from"./bathymetry.ts";
import type{BoundingBoxNed,GeographicRegion,GeographicRegionInput,Vec3}from"./geography.ts";
import{resolveGeographicRegion}from"./geography.ts";

export type DepthSourceId="ehydro"|"lidar"|"estuarine_dem"|"cudem"|"gebco";
export const DEPTH_SOURCE_PRIORITY:readonly DepthSourceId[]=["ehydro","lidar","estuarine_dem","cudem","gebco"];
export type FeatureRole="rendering"|"collision"|"navigation"|"bathymetry"|"sensor_simulation"|"environmental_boundary";
export interface SourceProvenance extends Record<string,unknown>{source:DepthSourceId|string;product:string;retrieval_date:string;survey_date:string|null;native_resolution_m:number;coverage:string;checksum_sha256:string;crs:string;transformations:string[]}
export interface DepthSourceCoverage{source:DepthSourceId;covered:boolean;nativeResolutionM:number;surveyDate:string|null;tileOrDatasetId:string;boundsM?:BoundingBoxNed;provenance?:SourceProvenance}
export interface CascadeCoverageCell{cellId:string;boundsM:BoundingBoxNed;winningSource:DepthSourceId|null;resolutionM:number|null;status:"resolved"|"no_data"}
export interface EncCoverage{cell_id:string;scale:"harbor"|"approach"|"coastal"|"general"|"overview";scale_denominator:number;covered:boolean;retrieval_date:string;checksum_sha256:string}
export interface CoverageReport{region:GeographicRegion;bySource:DepthSourceCoverage[];enc:EncCoverage|null;cascadeResult:{cells:CascadeCoverageCell[]}}
export interface DepthValue{water_depth_m:number|null;elevation_m:number|null;navigable:boolean;nearest_shore_m?:number}
export interface DepthSourceAdapter{readonly id:DepthSourceId;checkCoverage(region:GeographicRegion):DepthSourceCoverage[];fetchCell(cell:CascadeCoverageCell,coverage:DepthSourceCoverage):DepthValue}
export interface EncFeature{id:string;kind:"shoreline"|"land"|"navigable_water"|"channel"|"pier"|"dock"|"breakwater"|"bridge"|"aid_to_navigation"|"hazard"|"restricted_region";bounds_m:BoundingBoxNed;roles:FeatureRole[];properties?:Record<string,unknown>}
export interface EncAdapter{checkCoverage(region:GeographicRegion):EncCoverage[];fetchFeatures(region:GeographicRegion,cell:EncCoverage):EncFeature[]}
const inside=(p:Vec3,b:BoundingBoxNed)=>p[0]>=b.min_ned_m[0]&&p[0]<=b.max_ned_m[0]&&p[1]>=b.min_ned_m[1]&&p[1]<=b.max_ned_m[1];
const overlap=(a:BoundingBoxNed,b:BoundingBoxNed)=>a.min_ned_m[0]<b.max_ned_m[0]&&a.max_ned_m[0]>b.min_ned_m[0]&&a.min_ned_m[1]<b.max_ned_m[1]&&a.max_ned_m[1]>b.min_ned_m[1];
const canonical=(v:unknown):string=>JSON.stringify(v,(_k,x)=>x&&typeof x==="object"&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x);
export class GeographyCoverageService{
  readonly depthSources:DepthSourceAdapter[];readonly enc:EncAdapter;
  constructor(depthSources:DepthSourceAdapter[],enc:EncAdapter){this.depthSources=depthSources;this.enc=enc;const ids=new Set(depthSources.map(x=>x.id));for(const id of DEPTH_SOURCE_PRIORITY)if(!ids.has(id))throw new Error(`Missing depth coverage adapter: ${id}`);}
  checkCoverage(input:GeographicRegion|GeographicRegionInput,saved:Record<string,GeographicRegionInput>={}):CoverageReport{const region="bounds_ned_m"in input?input:resolveGeographicRegion(input,saved),bySource=this.depthSources.flatMap(s=>s.checkCoverage(region).map(c=>({...c,source:s.id}))),enc=this.selectLargestScaleEnc(this.enc.checkCoverage(region));const xs=new Set([region.bounds_ned_m.min_ned_m[0],region.bounds_ned_m.max_ned_m[0]]),ys=new Set([region.bounds_ned_m.min_ned_m[1],region.bounds_ned_m.max_ned_m[1]]);for(const c of bySource)if(c.covered&&c.boundsM&&overlap(c.boundsM,region.bounds_ned_m)){xs.add(Math.max(c.boundsM.min_ned_m[0],region.bounds_ned_m.min_ned_m[0]));xs.add(Math.min(c.boundsM.max_ned_m[0],region.bounds_ned_m.max_ned_m[0]));ys.add(Math.max(c.boundsM.min_ned_m[1],region.bounds_ned_m.min_ned_m[1]));ys.add(Math.min(c.boundsM.max_ned_m[1],region.bounds_ned_m.max_ned_m[1]));}const xa=[...xs].sort((a,b)=>a-b),ya=[...ys].sort((a,b)=>a-b),cells:CascadeCoverageCell[]=[];for(let i=0;i<xa.length-1;i++)for(let j=0;j<ya.length-1;j++){const boundsM={min_ned_m:[xa[i],ya[j],region.bounds_ned_m.min_ned_m[2]]as Vec3,max_ned_m:[xa[i+1],ya[j+1],region.bounds_ned_m.max_ned_m[2]]as Vec3},center=[(xa[i]+xa[i+1])/2,(ya[j]+ya[j+1])/2,0]as Vec3,winner=DEPTH_SOURCE_PRIORITY.map(id=>bySource.find(c=>c.source===id&&c.covered&&(!c.boundsM||inside(center,c.boundsM)))).find(Boolean);cells.push({cellId:`${region.id}:${i}:${j}`,boundsM,winningSource:winner?.source??null,resolutionM:winner?.nativeResolutionM??null,status:winner?"resolved":"no_data"});}return{region,bySource,enc,cascadeResult:{cells}};}
  selectLargestScaleEnc(cells:EncCoverage[]):EncCoverage|null{return cells.filter(x=>x.covered).sort((a,b)=>a.scale_denominator-b.scale_denominator||a.cell_id.localeCompare(b.cell_id))[0]??null;}
}
export interface ResolvedDepthCell extends CascadeCoverageCell{value:DepthValue|null;provenance:SourceProvenance|null}
export interface EncDepthMismatch{feature_id:string;feature_kind:EncFeature["kind"];position_ned_m:Vec3;enc_value:"land_or_hazard";cascade_depth_m:number|null;cascade_navigable:boolean;depth_source:DepthSourceId|null}
export interface ResolvedGeographyArtifact extends Record<string,unknown>{schema_version:1;region:GeographicRegion;cells:ResolvedDepthCell[];enc:{coverage:EncCoverage|null;features:EncFeature[]};mismatches:EncDepthMismatch[];unresolved_cell_ids:string[];simplification?:SimplificationMetrics}
export interface GeographyCache{get(key:string):ResolvedDepthCell|undefined;put(key:string,value:ResolvedDepthCell):void}
export class MemoryGeographyCache implements GeographyCache{#items=new Map<string,ResolvedDepthCell>();get(k:string){const x=this.#items.get(k);return x?structuredClone(x):undefined;}put(k:string,v:ResolvedDepthCell){this.#items.set(k,structuredClone(v));}}
export class PinnedGeographyCache implements GeographyCache{#items=new Map<string,ResolvedDepthCell>();constructor(snapshot?:Record<string,ResolvedDepthCell>){for(const[k,v]of Object.entries(snapshot??{}))this.#items.set(k,structuredClone(v));}get(k:string){const x=this.#items.get(k);return x?structuredClone(x):undefined;}put(k:string,v:ResolvedDepthCell){this.#items.set(k,structuredClone(v));}snapshot():Record<string,ResolvedDepthCell>{return Object.fromEntries([...this.#items].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,structuredClone(v)]));}}
export interface DepthCatalogRecord extends DepthSourceCoverage{value:DepthValue}
/** Metadata catalogs are queried without fetching raster payloads; fetchCell accesses only the selected record. */
export class CatalogDepthSource implements DepthSourceAdapter{readonly id:DepthSourceId;readonly #records:DepthCatalogRecord[];constructor(id:DepthSourceId,records:DepthCatalogRecord[]){this.id=id;this.#records=structuredClone(records);}checkCoverage(region:GeographicRegion){return this.#records.filter(r=>!r.boundsM||overlap(r.boundsM,region.bounds_ned_m)).map(({value:_value,...metadata})=>structuredClone(metadata));}fetchCell(cell:CascadeCoverageCell,coverage:DepthSourceCoverage){const record=this.#records.find(r=>r.tileOrDatasetId===coverage.tileOrDatasetId&&(!r.boundsM||overlap(r.boundsM,cell.boundsM)));if(!record)throw new Error(`Depth payload ${coverage.tileOrDatasetId} is unavailable.`);return structuredClone(record.value);}}
export interface EncCatalogRecord{coverage:EncCoverage;features:EncFeature[]}
export class CatalogEncSource implements EncAdapter{readonly #records:EncCatalogRecord[];constructor(records:EncCatalogRecord[]){this.#records=structuredClone(records);}checkCoverage(){return this.#records.map(x=>structuredClone(x.coverage));}fetchFeatures(_region:GeographicRegion,cell:EncCoverage){return structuredClone(this.#records.find(x=>x.coverage.cell_id===cell.cell_id)?.features??[]);}}
export class ResolvedGeography implements BathymetryField{
  readonly artifact:ResolvedGeographyArtifact;constructor(artifact:ResolvedGeographyArtifact){this.artifact=artifact;}
  #cell(p:Vec3){return this.artifact.cells.find(c=>inside(p,c.boundsM));}
  sample(q:BathymetryQuery):BathymetrySample{const c=this.#cell(q.position_ned_m);return c?.value?.water_depth_m==null?{water_depth_m:null,status:"no_data",provenance:c?.provenance??null}:{water_depth_m:c.value.water_depth_m,status:"resolved",provenance:c.provenance};}
  query_water_depth(p:Vec3){return this.sample({position_ned_m:p,time_s:0});}
  query_elevation(p:Vec3){const c=this.#cell(p);return{elevation_m:c?.value?.elevation_m??null,status:c?.value?"resolved"as const:"no_data"as const,provenance:c?.provenance??null};}
  query_navigability(p:Vec3){const c=this.#cell(p),enc=this.query_chart_feature(p),blocked=enc.some(f=>f.kind==="land"||f.kind==="hazard"||f.kind==="restricted_region");return{navigable:Boolean(c?.value?.navigable)&&!blocked,depth_source:c?.winningSource??null,enc_blocked:blocked};}
  query_nearest_shore(p:Vec3){const c=this.#cell(p);if(c?.value?.nearest_shore_m!==undefined)return c.value.nearest_shore_m;const shores=this.artifact.enc.features.filter(f=>f.kind==="shoreline"||f.kind==="land");return shores.length?Math.min(...shores.map(f=>Math.hypot(Math.max(f.bounds_m.min_ned_m[0]-p[0],0,p[0]-f.bounds_m.max_ned_m[0]),Math.max(f.bounds_m.min_ned_m[1]-p[1],0,p[1]-f.bounds_m.max_ned_m[1])))):null;}
  query_chart_feature(p:Vec3){return this.artifact.enc.features.filter(f=>inside(p,f.bounds_m));}
  raycast_terrain(origin:Vec3,direction:Vec3,maxRangeM:number){const mag=Math.hypot(...direction);if(!(mag>0&&maxRangeM>0))throw new Error("Terrain ray requires a direction and positive range.");const d=direction.map(x=>x/mag)as Vec3;for(let r=0;r<=maxRangeM;r+=1){const p=origin.map((x,i)=>x+d[i]*r)as Vec3,depth=this.query_water_depth(p).water_depth_m;if(depth!==null&&p[2]>=depth)return{distance_m:r,position_ned_m:p,depth_m:depth};}return null;}
  provenance(){return structuredClone(this.artifact);}
}
export class GeographyResolver{
  readonly coverage:GeographyCoverageService;readonly cache:GeographyCache;readonly simplificationToleranceM:number;constructor(coverage:GeographyCoverageService,cache:GeographyCache=new MemoryGeographyCache(),simplificationToleranceM=0){this.coverage=coverage;this.cache=cache;this.simplificationToleranceM=simplificationToleranceM;}
  resolve(region:GeographicRegion):ResolvedGeography{const report=this.coverage.checkCoverage(region),cells=report.cascadeResult.cells.map(cell=>{if(!cell.winningSource)return{...cell,value:null,provenance:null};const adapter=this.coverage.depthSources.find(x=>x.id===cell.winningSource)!,meta=report.bySource.find(c=>c.source===cell.winningSource&&c.covered&&(!c.boundsM||inside([(cell.boundsM.min_ned_m[0]+cell.boundsM.max_ned_m[0])/2,(cell.boundsM.min_ned_m[1]+cell.boundsM.max_ned_m[1])/2,0],c.boundsM)))!,key=canonical({region:region.id,cell:cell.cellId,source:cell.winningSource,retrieval_date:meta.provenance?.retrieval_date,survey_date:meta.surveyDate}),cached=this.cache.get(key);if(cached)return cached;const resolved={...cell,value:adapter.fetchCell(cell,meta),provenance:meta.provenance??null};this.cache.put(key,resolved);return resolved;}),rawFeatures=report.enc?this.coverage.enc.fetchFeatures(region,report.enc):[];for(const f of rawFeatures)if(!f.roles.length)throw new Error(`ENC feature ${f.id} must declare at least one validated role.`);const simplified=simplifyFeatures(rawFeatures,this.simplificationToleranceM),features=simplified.features,artifact:ResolvedGeographyArtifact={schema_version:1,region,cells,enc:{coverage:report.enc,features},mismatches:[],unresolved_cell_ids:cells.filter(x=>x.status==="no_data").map(x=>x.cellId),simplification:simplified.metrics};const resolved=new ResolvedGeography(artifact);for(const f of features.filter(x=>x.kind==="land"||x.kind==="hazard")){const p:[number,number,number]=[(f.bounds_m.min_ned_m[0]+f.bounds_m.max_ned_m[0])/2,(f.bounds_m.min_ned_m[1]+f.bounds_m.max_ned_m[1])/2,0],cell=cells.find(x=>inside(p,x.boundsM));if(cell?.value?.navigable)artifact.mismatches.push({feature_id:f.id,feature_kind:f.kind,position_ned_m:p,enc_value:"land_or_hazard",cascade_depth_m:cell.value.water_depth_m,cascade_navigable:true,depth_source:cell.winningSource});}return resolved;}
}
export interface SimplificationMetrics{input_vertices:number;output_vertices:number;max_error_m:number;preserved_roles:FeatureRole[]}
export function simplifyFeatures(features:EncFeature[],toleranceM:number):{features:EncFeature[];metrics:SimplificationMetrics}{if(!Number.isFinite(toleranceM)||toleranceM<0)throw new Error("Simplification tolerance must be non-negative.");const protectedRoles:FeatureRole[]=["collision","navigation","bathymetry","sensor_simulation","environmental_boundary"],preserved=new Set<FeatureRole>();for(const f of features)for(const r of f.roles)if(protectedRoles.includes(r))preserved.add(r);return{features:structuredClone(features),metrics:{input_vertices:features.length*4,output_vertices:features.length*4,max_error_m:0,preserved_roles:[...preserved].sort()}};}
export function coveragePreview(service:GeographyCoverageService,input:GeographicRegionInput,saved:Record<string,GeographicRegionInput>={}):CoverageReport{return service.checkCoverage(input,saved);}
