export type Vec3=[number,number,number];
export interface Wgs84Position{latitude_deg:number;longitude_deg:number;altitude_m?:number}
export interface BoundingBoxWgs84{south_deg:number;west_deg:number;north_deg:number;east_deg:number}
export interface BoundingBoxNed{min_ned_m:Vec3;max_ned_m:Vec3}
export type GeographicRegionInput=
  |{kind:"center_extent";center:Wgs84Position;extent_north_m:number;extent_east_m:number}
  |{kind:"bounding_box";bounds:BoundingBoxWgs84}
  |{kind:"polygon";vertices:Wgs84Position[]}
  |{kind:"saved";name:string}
  |{kind:"waypoints";waypoints:Wgs84Position[];padding_m?:number};
export interface GeographicRegion{id:string;input_kind:GeographicRegionInput["kind"];polygon_wgs84:Wgs84Position[];bounds_wgs84:BoundingBoxWgs84;origin:Wgs84Position;heading_deg:number;bounds_ned_m:BoundingBoxNed}

const A=6378137,F=1/298.257223563,E2=F*(2-F),RAD=Math.PI/180;
function validPoint(p:Wgs84Position):void{if(!Number.isFinite(p.latitude_deg)||p.latitude_deg < -90||p.latitude_deg>90||!Number.isFinite(p.longitude_deg)||p.longitude_deg < -180||p.longitude_deg>180||!Number.isFinite(p.altitude_m??0))throw new Error("Invalid WGS84 position.");}
function ecef(p:Wgs84Position):Vec3{validPoint(p);const lat=p.latitude_deg*RAD,lon=p.longitude_deg*RAD,h=p.altitude_m??0,n=A/Math.sqrt(1-E2*Math.sin(lat)**2);return[(n+h)*Math.cos(lat)*Math.cos(lon),(n+h)*Math.cos(lat)*Math.sin(lon),(n*(1-E2)+h)*Math.sin(lat)];}
function geodetic(v:Vec3):Wgs84Position{const [x,y,z]=v,lon=Math.atan2(y,x),p=Math.hypot(x,y);let lat=Math.atan2(z,p*(1-E2));for(let i=0;i<10;i++){const n=A/Math.sqrt(1-E2*Math.sin(lat)**2);lat=Math.atan2(z+E2*n*Math.sin(lat),p);}const n=A/Math.sqrt(1-E2*Math.sin(lat)**2),h=p/Math.cos(lat)-n;return{latitude_deg:lat/RAD,longitude_deg:lon/RAD,altitude_m:h};}
function rotate(n:number,e:number,headingRad:number):[number,number]{const c=Math.cos(headingRad),s=Math.sin(headingRad);return[c*n+s*e,-s*n+c*e];}
/** Geography is runtime-NED. ENU and source z-up coordinates may only cross this explicit boundary; never pass them to sensor propagation. */
export class LocalGeographicFrame{
  readonly origin:Required<Wgs84Position>;readonly heading_deg:number;readonly #originEcef:Vec3;readonly #lat:number;readonly #lon:number;
  constructor(origin:Wgs84Position,headingDeg=0){validPoint(origin);if(!Number.isFinite(headingDeg)||headingDeg < -180||headingDeg>180)throw new Error("Geographic heading must be finite in [-180, 180].");this.origin={...origin,altitude_m:origin.altitude_m??0};this.heading_deg=headingDeg;this.#originEcef=ecef(this.origin);this.#lat=origin.latitude_deg*RAD;this.#lon=origin.longitude_deg*RAD;}
  wgs84ToNed(point:Wgs84Position):Vec3{const q=ecef(point),dx=q[0]-this.#originEcef[0],dy=q[1]-this.#originEcef[1],dz=q[2]-this.#originEcef[2],east=-Math.sin(this.#lon)*dx+Math.cos(this.#lon)*dy,north=-Math.sin(this.#lat)*Math.cos(this.#lon)*dx-Math.sin(this.#lat)*Math.sin(this.#lon)*dy+Math.cos(this.#lat)*dz,up=Math.cos(this.#lat)*Math.cos(this.#lon)*dx+Math.cos(this.#lat)*Math.sin(this.#lon)*dy+Math.sin(this.#lat)*dz,[n,e]=rotate(north,east,this.heading_deg*RAD);return[n,e,-up];}
  nedToWgs84(ned:Vec3):Wgs84Position{if(ned.length!==3||ned.some(x=>!Number.isFinite(x)))throw new Error("NED position must contain three finite values.");const [north,east]=rotate(ned[0],ned[1],-this.heading_deg*RAD),up=-ned[2],dx=-Math.sin(this.#lat)*Math.cos(this.#lon)*north-Math.sin(this.#lon)*east+Math.cos(this.#lat)*Math.cos(this.#lon)*up,dy=-Math.sin(this.#lat)*Math.sin(this.#lon)*north+Math.cos(this.#lon)*east+Math.cos(this.#lat)*Math.sin(this.#lon)*up,dz=Math.cos(this.#lat)*north+Math.sin(this.#lat)*up;return geodetic([this.#originEcef[0]+dx,this.#originEcef[1]+dy,this.#originEcef[2]+dz]);}
  nedToEnu(ned:Vec3):Vec3{return[ned[1],ned[0],-ned[2]];}
  enuToNed(enu:Vec3):Vec3{return[enu[1],enu[0],-enu[2]];}
}
const hash=(s:string)=>{let h=2166136261;for(const b of new TextEncoder().encode(s)){h^=b;h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,"0");};
export function resolveGeographicRegion(input:GeographicRegionInput,saved:Record<string,GeographicRegionInput>={},headingDeg=0):GeographicRegion{if(input.kind==="saved"){const found=saved[input.name];if(!found)throw new Error(`Unknown saved geographic region: ${input.name}`);return resolveGeographicRegion(found,saved,headingDeg);}let polygon:Wgs84Position[];if(input.kind==="center_extent"){validPoint(input.center);if(input.extent_north_m<=0||input.extent_east_m<=0)throw new Error("Region extents must be positive.");const f=new LocalGeographicFrame(input.center,headingDeg),n=input.extent_north_m/2,e=input.extent_east_m/2;polygon=[[-n,-e,0],[-n,e,0],[n,e,0],[n,-e,0]].map(([nn,ee,d])=>f.nedToWgs84([nn,ee,d]));}else if(input.kind==="bounding_box"){const b=input.bounds;if(!(b.south_deg<b.north_deg&&b.west_deg<b.east_deg))throw new Error("Invalid geographic bounding box.");polygon=[{latitude_deg:b.south_deg,longitude_deg:b.west_deg},{latitude_deg:b.south_deg,longitude_deg:b.east_deg},{latitude_deg:b.north_deg,longitude_deg:b.east_deg},{latitude_deg:b.north_deg,longitude_deg:b.west_deg}];}else{const points=input.kind==="polygon"?input.vertices:input.waypoints;if(points.length<(input.kind==="polygon"?3:1))throw new Error("Geographic region has too few points.");points.forEach(validPoint);polygon=[...points];if(input.kind==="waypoints"&&(input.padding_m??0)>0){const lats=points.map(x=>x.latitude_deg),lons=points.map(x=>x.longitude_deg),center={latitude_deg:(Math.min(...lats)+Math.max(...lats))/2,longitude_deg:(Math.min(...lons)+Math.max(...lons))/2},f=new LocalGeographicFrame(center),ned=points.map(p=>f.wgs84ToNed(p)),pad=input.padding_m!;return resolveGeographicRegion({kind:"center_extent",center,extent_north_m:Math.max(...ned.map(x=>x[0]))-Math.min(...ned.map(x=>x[0]))+2*pad,extent_east_m:Math.max(...ned.map(x=>x[1]))-Math.min(...ned.map(x=>x[1]))+2*pad},saved,headingDeg);}}
  const lats=polygon.map(x=>x.latitude_deg),lons=polygon.map(x=>x.longitude_deg),bounds={south_deg:Math.min(...lats),west_deg:Math.min(...lons),north_deg:Math.max(...lats),east_deg:Math.max(...lons)},origin={latitude_deg:(bounds.south_deg+bounds.north_deg)/2,longitude_deg:(bounds.west_deg+bounds.east_deg)/2,altitude_m:0},frame=new LocalGeographicFrame(origin,headingDeg),points=polygon.map(p=>frame.wgs84ToNed(p)),boundsNed={min_ned_m:[Math.min(...points.map(x=>x[0])),Math.min(...points.map(x=>x[1])),Math.min(...points.map(x=>x[2]))]as Vec3,max_ned_m:[Math.max(...points.map(x=>x[0])),Math.max(...points.map(x=>x[1])),Math.max(...points.map(x=>x[2]))]as Vec3};return{id:`region-${hash(JSON.stringify({input,headingDeg}))}`,input_kind:input.kind,polygon_wgs84:polygon,bounds_wgs84:bounds,origin,heading_deg:headingDeg,bounds_ned_m:boundsNed};}
