import{LocalGeographicFrame,type GeographicRegion,type Wgs84Position}from"./geography.ts";import{toGroupedEnvironmentSample,type EnvironmentSample,type GroupedEnvironmentSample}from"./index.ts";
import{decodeRtofsNetcdf4}from"./rtofs.ts";
export type WeatherSourceId="ndbc"|"coops"|"nws"|"rtofs"|"era5";
export type WeatherMode="realtime_forecast"|"historical_replay";
export interface NwsUserAgentConfig{application:string;contact:string}
export interface WeatherProvenance{source:WeatherSourceId;station_or_grid_id:string;retrieval_date:string;observation_or_valid_time:string;distance_m:number|null;staleness_s:number;forecast_cycle?:string;checksum?:string;dataset_product?:string;time_range?:string;grid_cells?:string[]}
export interface WeatherResult{sample:GroupedEnvironmentSample;provenance:WeatherProvenance[];coverage:"station"|"grid"|"mixed";limitations:string[]}
export interface WeatherQuery{position_ned_m:[number,number,number];time:string;mode:WeatherMode}
export interface WeatherPatch{atmosphere?:Partial<GroupedEnvironmentSample["atmosphere"]>;water?:Partial<GroupedEnvironmentSample["water"]>;surface?:Partial<GroupedEnvironmentSample["surface"]>}
export interface WeatherSourceResult{patch:WeatherPatch;provenance:WeatherProvenance;kind:"station"|"grid"}
export interface WeatherSource{readonly id:WeatherSourceId;query(point:Wgs84Position,time:string,mode:WeatherMode):Promise<WeatherSourceResult|null>}
const RAD=Math.PI/180,missing=(v:string)=>v==="MM"||v==="999"||v==="9999"||v==="";
const vector=(speed:number,directionFromDeg:number):[number,number,number]=>{const toward=(directionFromDeg+180)*RAD;return[speed*Math.cos(toward),speed*Math.sin(toward),0];};
const distance=(a:Wgs84Position,b:Wgs84Position)=>Math.hypot(...new LocalGeographicFrame(a).wgs84ToNed(b).slice(0,2));
const beaufort=(speed:number)=>Math.max(0,Math.min(12,Math.round(Math.pow(Math.max(speed,0)/0.836,2/3))));
const age=(valid:string,requested:string)=>Math.max((Date.parse(requested)-Date.parse(valid))/1000,0);
export interface StationDescriptor{id:string;position:Wgs84Position}
export interface TextFetcher{(url:string,headers?:Record<string,string>):Promise<{text():Promise<string>;json():Promise<any>}>}
export function parseNdbcStandardMeteorological(text:string):Array<{time:string;wind_speed_mps?:number;wind_direction_deg?:number;gust_mps?:number;wave_height_m?:number;dominant_wave_period_s?:number;mean_wave_direction_deg?:number;pressure_pa?:number;air_temperature_c?:number;water_temperature_c?:number}>{const lines=text.trim().split(/\r?\n/).filter(Boolean),header=lines.find(x=>x.startsWith("#YY")||x.startsWith("#YYYY"));if(!header)return[];const keys=header.replace(/^#/,'').trim().split(/\s+/),start=lines.indexOf(header)+1,out=[];for(const line of lines.slice(start)){if(line.startsWith("#"))continue;const values=line.trim().split(/\s+/),get=(k:string)=>values[keys.indexOf(k)],year=Number(get("YY")??get("YYYY")),yyyy=year<100?2000+year:year,time=new Date(Date.UTC(yyyy,Number(get("MM"))-1,Number(get("DD")),Number(get("hh")),Number(get("mm")||0))).toISOString(),num=(k:string)=>{const x=get(k);return x===undefined||missing(x)?undefined:Number(x)};out.push({time,...num("WSPD")!==undefined?{wind_speed_mps:num("WSPD")}:{},...num("WDIR")!==undefined?{wind_direction_deg:num("WDIR")}:{},...num("GST")!==undefined?{gust_mps:num("GST")}:{},...num("WVHT")!==undefined?{wave_height_m:num("WVHT")}:{},...num("DPD")!==undefined?{dominant_wave_period_s:num("DPD")}:{},...num("MWD")!==undefined?{mean_wave_direction_deg:num("MWD")}:{},...num("PRES")!==undefined?{pressure_pa:num("PRES")!*100}:{},...num("ATMP")!==undefined?{air_temperature_c:num("ATMP")}:{},...num("WTMP")!==undefined?{water_temperature_c:num("WTMP")}:{}});}return out;}
export class NdbcSource implements WeatherSource{readonly id="ndbc"as const;readonly stations:StationDescriptor[];readonly fetcher:TextFetcher;readonly maxDistanceM:number;constructor(stations:StationDescriptor[],fetcher:TextFetcher=fetch as any,maxDistanceM=200000){this.stations=stations;this.fetcher=fetcher;this.maxDistanceM=maxDistanceM;}async query(point:Wgs84Position,time:string,mode:WeatherMode){const candidates=this.stations.map(s=>({s,d:distance(point,s.position)})).filter(x=>x.d<=this.maxDistanceM).sort((a,b)=>a.d-b.d);for(const{x,d}of candidates.map(({s,d})=>({x:s,d}))){const year=new Date(time).getUTCFullYear(),url=mode==="historical_replay"?`https://www.ndbc.noaa.gov/view_text_file.php?filename=${x.id.toLowerCase()}h${year}.txt.gz&dir=data/historical/stdmet/`:`https://www.ndbc.noaa.gov/data/realtime2/${x.id}.txt`,rows=parseNdbcStandardMeteorological(await(await this.fetcher(url)).text()),row=rows.sort((a,b)=>Math.abs(Date.parse(a.time)-Date.parse(time))-Math.abs(Date.parse(b.time)-Date.parse(time)))[0];if(!row)continue;const patch:WeatherPatch={atmosphere:{...row.wind_speed_mps!==undefined&&row.wind_direction_deg!==undefined?{wind_ned_mps:vector(row.wind_speed_mps,row.wind_direction_deg)}:{},...row.gust_mps!==undefined&&row.wind_direction_deg!==undefined?{gust_ned_mps:vector(row.gust_mps,row.wind_direction_deg)}:{},...row.pressure_pa!==undefined?{pressure_pa:row.pressure_pa}:{},...row.air_temperature_c!==undefined?{air_temperature_c:row.air_temperature_c}:{}},water:{...row.water_temperature_c!==undefined?{temperature_c:row.water_temperature_c}:{}},surface:{...row.wind_speed_mps!==undefined?{sea_state_beaufort:beaufort(row.wind_speed_mps)}:{},...row.wave_height_m!==undefined?{significant_wave_height_m:row.wave_height_m}:{},...row.dominant_wave_period_s!==undefined?{dominant_wave_period_s:row.dominant_wave_period_s}:{},...row.mean_wave_direction_deg!==undefined?{mean_wave_direction_rad:row.mean_wave_direction_deg*RAD}:{}}};return{patch,kind:"station"as const,provenance:{source:this.id,station_or_grid_id:x.id,retrieval_date:new Date().toISOString(),observation_or_valid_time:row.time,distance_m:d,staleness_s:age(row.time,time)}};}return null;}}
export class CoopsSource implements WeatherSource{readonly id="coops"as const;readonly stations:StationDescriptor[];readonly fetcher:TextFetcher;readonly maxDistanceM:number;constructor(stations:StationDescriptor[],fetcher:TextFetcher=fetch as any,maxDistanceM=100000){this.stations=stations;this.fetcher=fetcher;this.maxDistanceM=maxDistanceM;}async query(point:Wgs84Position,time:string,mode:WeatherMode){const nearest=this.stations.map(s=>({s,d:distance(point,s.position)})).filter(x=>x.d<=this.maxDistanceM).sort((a,b)=>a.d-b.d)[0];if(!nearest)return null;const day=new Date(time).toISOString().slice(0,10).replaceAll("-",""),product="water_level",url=`https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?${mode==="historical_replay"?`begin_date=${day}&end_date=${day}`:"date=latest"}&station=${nearest.s.id}&product=${product}&datum=MLLW&time_zone=gmt&units=metric&application=BCOD&format=json`,json=await(await this.fetcher(url)).json(),row=(json.data??json.predictions??[]).at(-1);if(!row)return null;const valid=new Date(String(row.t).replace(" ","T")+"Z").toISOString();return{patch:{surface:{tide_m:Number(row.v)}},kind:"station"as const,provenance:{source:this.id,station_or_grid_id:nearest.s.id,retrieval_date:new Date().toISOString(),observation_or_valid_time:valid,distance_m:nearest.d,staleness_s:age(valid,time)}};}}
function validateAgent(config:NwsUserAgentConfig){if(!config.application?.trim()||!config.contact?.trim()||!(/@|https?:\/\//.test(config.contact)))throw new Error("NWS User-Agent requires an application name and email or URL contact.");return`${config.application} (${config.contact})`;}
export class NwsSource implements WeatherSource{readonly id="nws"as const;readonly userAgent:string;readonly fetcher:TextFetcher;constructor(config:NwsUserAgentConfig,fetcher:TextFetcher=fetch as any){this.userAgent=validateAgent(config);this.fetcher=fetcher;}async query(point:Wgs84Position,time:string,mode:WeatherMode){if(mode==="historical_replay")return null;const headers={"User-Agent":this.userAgent,"Accept":"application/geo+json"},meta=await(await this.fetcher(`https://api.weather.gov/points/${point.latitude_deg},${point.longitude_deg}`,headers)).json(),url=meta.properties?.forecastGridData;if(!url)return null;const grid=await(await this.fetcher(url,headers)).json(),p=grid.properties,nearest=(values:any[])=>values?.filter(x=>Date.parse(x.validTime.split('/')[0])<=Date.parse(time)).at(-1)?.value,wind=nearest(p.windSpeed?.values),direction=nearest(p.windDirection?.values),temperature=nearest(p.temperature?.values),pressure=nearest(p.barometricPressure?.values),humidity=nearest(p.relativeHumidity?.values),precip=nearest(p.quantitativePrecipitation?.values),valid=p.updateTime??time;return{patch:{atmosphere:{...wind!=null&&direction!=null?{wind_ned_mps:vector(wind,direction)}:{},...temperature!=null?{air_temperature_c:temperature}:{},...pressure!=null?{pressure_pa:pressure}:{},...humidity!=null?{humidity_fraction:humidity/100}:{},...precip!=null?{rain_rate_mm_h:precip}:{}}},kind:"grid"as const,provenance:{source:this.id,station_or_grid_id:`${meta.properties.gridId}/${meta.properties.gridX},${meta.properties.gridY}`,retrieval_date:new Date().toISOString(),observation_or_valid_time:valid,distance_m:null,staleness_s:age(valid,time)}};}}
export interface RtofsGridDecoder{query(point:Wgs84Position,time:string):Promise<{grid_id:string;cycle:string;valid_time:string;current_north_mps:number;current_east_mps:number;temperature_c:number;salinity_psu:number}>}
export interface RtofsDecodedCell{grid_id:string;valid_time:string;current_north_mps:number;current_east_mps:number;temperature_c:number;salinity_psu:number}
export type RtofsBinaryDecoder=(bytes:ArrayBuffer,point:Wgs84Position,time:string)=>Promise<RtofsDecodedCell>;
/** NOMADS transport is separate from GRIB2 decoding so browser, Node, and native clients can supply their platform decoder. The cycle is required and therefore pinned. */
export class NomadsRtofsGridDecoder implements RtofsGridDecoder{readonly cycle:string;readonly decode:RtofsBinaryDecoder;readonly fetcher:typeof fetch;constructor(cycle:string,decode:RtofsBinaryDecoder=decodeRtofsNetcdf4,fetcher:typeof fetch=fetch){if(!/^\d{8}T00Z$/.test(cycle))throw new Error("RTOFS forecast cycle must be pinned as YYYYMMDDT00Z.");this.cycle=cycle;this.decode=decode;this.fetcher=fetcher;}async query(point:Wgs84Position,time:string){const date=this.cycle.slice(0,8),hour=this.cycle.slice(9,11),lead=Math.max(0,Math.min(192,Math.round((Date.parse(time)-Date.parse(`${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}T${hour}:00:00Z`))/3600000))),url=`https://nomads.ncep.noaa.gov/pub/data/nccf/com/rtofs/prod/rtofs.${date}/rtofs_glo_2ds_f${String(lead).padStart(3,"0")}_prog.nc`;const response=await this.fetcher(url);if(!response.ok)throw new Error(`RTOFS fetch failed for pinned cycle ${this.cycle}: HTTP ${response.status}`);return{...await this.decode(await response.arrayBuffer(),point,time),cycle:this.cycle};}}
export class RtofsSource implements WeatherSource{readonly id="rtofs"as const;readonly decoder:RtofsGridDecoder;constructor(decoder:RtofsGridDecoder){this.decoder=decoder;}async query(point:Wgs84Position,time:string,mode:WeatherMode):Promise<WeatherSourceResult|null>{if(mode==="historical_replay")return null;const x=await this.decoder.query(point,time);return{patch:{water:{current_ned_mps:[x.current_north_mps,x.current_east_mps,0] as [number,number,number],temperature_c:x.temperature_c,salinity_psu:x.salinity_psu}},kind:"grid",provenance:{source:this.id,station_or_grid_id:x.grid_id,retrieval_date:new Date().toISOString(),observation_or_valid_time:x.valid_time,distance_m:null,staleness_s:age(x.valid_time,time),forecast_cycle:x.cycle}};}}
export interface WeatherCache{get(key:string):WeatherResult|undefined;put(key:string,value:WeatherResult):void}
export class PinnedWeatherCache implements WeatherCache{#items=new Map<string,WeatherResult>();constructor(snapshot?:Record<string,WeatherResult>){for(const[k,v]of Object.entries(snapshot??{}))this.#items.set(k,structuredClone(v));}get(k:string){const v=this.#items.get(k);return v?structuredClone(v):undefined;}put(k:string,v:WeatherResult){this.#items.set(k,structuredClone(v));}snapshot(){return Object.fromEntries([...this.#items].sort(([a],[b])=>a.localeCompare(b)));}}
export interface ResolvedWeatherArtifact{schema_version:1;region_id:string;queries:Record<string,WeatherResult>;source_retrieval_index:Record<string,WeatherProvenance>}
const merge=(base:GroupedEnvironmentSample,p:WeatherPatch)=>toGroupedEnvironmentSample({...base,atmosphere:{...base.atmosphere,...p.atmosphere},water:{...base.water,...p.water},surface:{...base.surface,...p.surface}});
export class WeatherEnvironmentField{readonly region:GeographicRegion;readonly base:EnvironmentSample;readonly sources:WeatherSource[];readonly cache:WeatherCache;constructor(region:GeographicRegion,base:EnvironmentSample,sources:WeatherSource[],cache:WeatherCache=new PinnedWeatherCache()){this.region=region;this.base=base;this.sources=sources;this.cache=cache;}async query(q:WeatherQuery):Promise<WeatherResult>{const frame=new LocalGeographicFrame(this.region.origin,this.region.heading_deg),point=frame.nedToWgs84(q.position_ned_m),key=JSON.stringify({region:this.region.id,mode:q.mode,time:q.time,sources:this.sources.map(x=>x.id).sort()}),cached=this.cache.get(key);if(cached)return cached;let sample=toGroupedEnvironmentSample(this.base);const results:WeatherSourceResult[]=[],priority=q.mode==="historical_replay"?["era5","ndbc","coops","nws","rtofs"]:["ndbc","coops","nws","rtofs","era5"];for(const source of [...this.sources].sort((a,b)=>priority.indexOf(a.id)-priority.indexOf(b.id))){const value=await source.query(point,q.time,q.mode);if(value){sample=merge(sample,value.patch);results.push(value);}}const kinds=new Set(results.map(x=>x.kind)),hasEra5=results.some(x=>x.provenance.source==="era5"),result={sample,provenance:results.map(x=>x.provenance),coverage:kinds.size>1?"mixed"as const:(kinds.has("grid")?"grid"as const:"station"as const),limitations:q.mode==="historical_replay"&&!hasEra5?["Historical replay is point-source-only (NDBC/CO-OPS) and spatially sparse because ERA5 was not selected."]:[]};this.cache.put(key,result);return result;}resolvedArtifact():ResolvedWeatherArtifact{const queries=(this.cache as PinnedWeatherCache).snapshot?.();if(!queries)throw new Error("Resolved weather artifacts require a snapshot-capable pinned cache.");const source_retrieval_index=Object.fromEntries(Object.values(queries).flatMap(result=>result.provenance.map(item=>[JSON.stringify({region:this.region.id,source:item.source,retrieval_date:item.retrieval_date,station_or_grid_id:item.station_or_grid_id}),structuredClone(item)])));return{schema_version:1,region_id:this.region.id,queries,source_retrieval_index};}}
