export type Vector3=[number,number,number];
export type Wrench6=[number,number,number,number,number,number];
export type PlanarWrench=[number,number,number];
export interface DynamicsConfig {tau?:number;rateMax?:number;min?:number;max?:number}
export type ActuatorFailureMode="healthy"|"failed-off"|"stuck";
export interface EffectorCommand {command?:number;thrust?:number;value?:number;deflection?:number;speed?:number;azimuth?:number;failure_mode?:ActuatorFailureMode}
export interface EffectorConfig {id:string;type:"FixedThruster"|"AzimuthThruster"|"ControlSurface"|"Rotor";pos?:Vector3;positionBody?:Vector3;axis?:Vector3;directionBody?:Vector3;dynamics?:DynamicsConfig;maxForwardThrust?:number;maxReverseThrust?:number;maxThrust?:number;conversion?:Record<string,unknown>;steer?:DynamicsConfig;azimuth?:DynamicsConfig&{initial?:number};foil?:Record<string,number>;forceAxis?:Vector3;inducedInflow?:boolean;spinDirection?:number}
export interface ActuatorCheckpointEffector {id:string;command?:number;value?:number;thrust?:number;azimuth?:number;deflection?:number;omega?:number;axis?:Vector3}
export interface ActuatorCheckpoint {effectors:ActuatorCheckpointEffector[];lastFullWrench:Wrench6;lastEffectorCommands:Record<string,EffectorCommand>;stepIndex?:number;events?:ActuatorEvent[];lastAllocationDiagnostics?:AllocationDiagnostics|null}
export interface ActuatorCommand {appliedWrench?:number[];effectors?:Record<string,EffectorCommand>;failureStates?:Record<string,ActuatorFailureMode|{mode:ActuatorFailureMode;source?:string}>;tauDes?:PlanarWrench;desiredWrench?:number[];surgeForce?:number;yawMoment?:number;differentialForce?:number;[key:string]:unknown}
export interface ActuatorEvent {type:"ACTUATOR_FAILURE"|"ACTUATOR_STATE_TRANSITION";actuator_id:string;step:number;mode:ActuatorFailureMode;previous_mode:ActuatorFailureMode;source:string}
export interface AllocationDiagnostics {mode:"nominal"|"failed-off-reduced-set"|"stuck-bias-rejection";rank:number;condition_number:number|null;singular_values:number[];bias_wrench:Wrench6;achieved_wrench:Wrench6;residual_wrench:Wrench6;reachable:boolean;degradation:"none"|"infeasible"|"rank-deficient"}
export interface VehicleActuatorParameters {actuator?:Record<string,unknown>;allocator?:Record<string,unknown>;effectors?:EffectorConfig[];controlledDOF?:string[];geometry?:Record<string,number>;massProps?:Record<string,unknown>;buoyancy?:Record<string,number>}
export declare class FixedThruster {id:string;type:string;pos:Vector3;axis:Vector3;dynamics:Required<DynamicsConfig>;conversion:Record<string,unknown>;command:number;value:number;thrust:number;constructor(config:EffectorConfig,params:VehicleActuatorParameters);reset():void;commandToValue(command:number):number;advance(dt:number,command?:EffectorCommand):number;wrench(params:VehicleActuatorParameters):Wrench6;wrenchWithUnitCommand(params:VehicleActuatorParameters,state?:unknown,env?:Record<string,unknown>):Wrench6;wrenchWithUnitThrust(params:VehicleActuatorParameters):Wrench6}
export declare class AzimuthThruster extends FixedThruster {steer:Required<DynamicsConfig>;azimuth:number;advance(dt:number,command?:EffectorCommand):number}
export declare class ControlSurface {id:string;type:string;deflection:number;constructor(config:EffectorConfig,params:VehicleActuatorParameters);reset():void;advance(dt:number,command?:EffectorCommand):number;wrench(params:VehicleActuatorParameters,state?:unknown,env?:Record<string,unknown>):Wrench6;wrenchWithUnitCommand(params:VehicleActuatorParameters,state?:unknown,env?:Record<string,unknown>):Wrench6}
export declare class Rotor {id:string;type:string;omega:number;constructor(config:EffectorConfig,params:VehicleActuatorParameters);reset():void;advance(dt:number,command?:EffectorCommand):number;wrench(params:VehicleActuatorParameters):Wrench6;wrenchWithUnitCommand(params:VehicleActuatorParameters,state?:unknown,env?:Record<string,unknown>):Wrench6}
export type Effector=FixedThruster|AzimuthThruster|ControlSurface|Rotor;
export declare function allocationMatrix(effectors:Effector[],params:VehicleActuatorParameters,controlledDOF?:string[],state?:unknown,env?:Record<string,unknown>):number[][];
export declare function allocateLeastSquares(effectors:Effector[],params:VehicleActuatorParameters,tau6:number[],options?:Record<string,unknown>,state?:unknown,env?:Record<string,unknown>):number[];
export declare function buildEffectors(params:VehicleActuatorParameters):Effector[];
export declare class ActuationModel {params:VehicleActuatorParameters;effectors:Effector[];lastFullWrench:Wrench6;lastEffectorCommands:Record<string,EffectorCommand>;lastAllocationDiagnostics:AllocationDiagnostics|null;constructor(params:VehicleActuatorParameters);reset():void;saveState():ActuatorCheckpoint;loadState(state:ActuatorCheckpoint):void;setFailureMode(id:string,mode:ActuatorFailureMode,source?:string):void;drainEvents():ActuatorEvent[];getEnergyMetrics():{actuator_energy_j:number;propulsion_energy_j:number;actuator_power_w:number};commandWrench(command?:ActuatorCommand,dt?:number,state?:unknown,env?:Record<string,unknown>):number[];prepareStep(ctx:Record<string,unknown>):void;computeWrench(ctx:Record<string,unknown>):number[];resolveEffectorCommands(command?:ActuatorCommand,state?:unknown,env?:Record<string,unknown>):Record<string,EffectorCommand>;allocate(tau6?:number[],state?:unknown,env?:Record<string,unknown>):Record<string,EffectorCommand>}
export declare class ActuatorModel extends ActuationModel {}
