import {ForceModel} from "./force-model.js";
import {MmgManeuveringModel} from "./mmg.js";

const clamp=(value,min,max)=>Math.min(Math.max(value,min),max);
const approach=(value,target,limit)=>value+clamp(target-value,-limit,limit);

export function createVehicleBMmgParameters(vehicle,configuration,{rho=1025}={}){
    if(configuration.schema_version!==1||configuration.parameter_set_id!==vehicle.maneuvering_model?.parameter_set_id)throw new Error("Vehicle B MMG parameter-set identity mismatch.");
    if(configuration.stage!=="usv-scale"||configuration.source_vessel!=="Vehicle-B-USV"||configuration.may_validate_usv_coefficients!==false)throw new Error("Production Vehicle B must use the explicitly unvalidated USV-scale parameter set.");
    const geometry=vehicle.geometry,interaction=configuration.interaction,propeller=configuration.propeller;
    return{id:configuration.parameter_set_id,sourceVessel:"Vehicle-B-USV",rho,L:geometry.length.value,d:geometry.draft.value,B:geometry.width.value,volume:vehicle.mass.value/rho,mass:vehicle.mass.value,xG:configuration.x_g_m,Iz:vehicle.inertia.value[2],DP:propeller.diameter_m,AR:configuration.rudder.area_m2,rudderSpan:configuration.rudder.span_m,xR:configuration.rudder.x_m,hull:{...configuration.hull_derivatives},added:{mx:0,my:0,Jz:0},interaction:{...interaction},propeller:{k0:propeller.k0,k1:propeller.k1,k2:propeller.k2,wP0:propeller.w_P0},provenance:{reference:configuration.provenance.source,parameterSet:configuration.parameter_set_id,evidenceScope:"vehicle-b-usv-parameterization-unvalidated",capytaineAddedMassOverwrite:false,coefficientChecksum:configuration.provenance.checksum_sha256},production:{resistance_n_per_mps2:configuration.resistance_n_per_mps2,max_propeller_rps:propeller.max_rps,max_rudder_rad:configuration.rudder.max_angle_deg*Math.PI/180,propeller_time_constant_s:propeller.time_constant_s,propeller_rate_rps2:propeller.rate_rps2,rudder_time_constant_s:configuration.rudder.time_constant_s,rudder_rate_rad_s:configuration.rudder.rate_deg_s*Math.PI/180,max_surge_command_n:configuration.command_mapping.max_surge_force_n,max_yaw_command_nm:configuration.command_mapping.max_yaw_moment_nm}};
}

export class VehicleBMmgForceModel extends ForceModel{
    constructor(params){super();this.params=params;this.model=new MmgManeuveringModel(params);this.propellerRps=0;this.rudderRad=0;this.lastFullWrench=[0,0,0,0,0,0];this.lastBreakdown={};this.lastCommand={propeller_rps:0,rudder_rad:0};this.stepIndex=0;}
    reset(){this.propellerRps=0;this.rudderRad=0;this.lastFullWrench=[0,0,0,0,0,0];this.lastBreakdown={};this.lastCommand={propeller_rps:0,rudder_rad:0};this.stepIndex=0;}
    resolveCommand(command={}){const limits=this.params.production,explicitPropeller=Number.isFinite(command.propeller_rps),explicitRudder=Number.isFinite(command.rudder_rad),surge=clamp(command.surgeForce??0,-limits.max_surge_command_n,limits.max_surge_command_n),yaw=clamp(command.yawMoment??((command.differentialForce??0)*this.params.B),-limits.max_yaw_command_nm,limits.max_yaw_command_nm);return{propeller_rps:explicitPropeller?clamp(command.propeller_rps,-limits.max_propeller_rps,limits.max_propeller_rps):Math.sign(surge)*limits.max_propeller_rps*Math.sqrt(Math.abs(surge)/limits.max_surge_command_n),rudder_rad:explicitRudder?clamp(command.rudder_rad,-limits.max_rudder_rad,limits.max_rudder_rad):clamp(yaw/limits.max_yaw_command_nm,-1,1)*limits.max_rudder_rad};}
    prepareStep(ctx){const desired=this.resolveCommand(ctx.command),dt=ctx.dt??0,p=this.params.production,propellerFiltered=p.propeller_time_constant_s>0?this.propellerRps+(desired.propeller_rps-this.propellerRps)*(1-Math.exp(-dt/p.propeller_time_constant_s)):desired.propeller_rps,rudderFiltered=p.rudder_time_constant_s>0?this.rudderRad+(desired.rudder_rad-this.rudderRad)*(1-Math.exp(-dt/p.rudder_time_constant_s)):desired.rudder_rad;this.propellerRps=approach(this.propellerRps,propellerFiltered,p.propeller_rate_rps2*dt);this.rudderRad=approach(this.rudderRad,rudderFiltered,p.rudder_rate_rad_s*dt);this.lastCommand={propeller_rps:this.propellerRps,rudder_rad:this.rudderRad};this.stepIndex+=1;}
    computeWrench(ctx){const breakdown=this.model.computeComponents(ctx.state,{...this.lastCommand,straight_resistance_n:this.params.production.resistance_n_per_mps2,resistance_reference_speed_mps:1}),total=breakdown.total;this.lastBreakdown=structuredClone(breakdown);this.lastFullWrench=[total[0],total[1],0,0,0,total[2]];return total;}
    saveState(){return{version:1,propeller_rps:this.propellerRps,rudder_rad:this.rudderRad,last_command:structuredClone(this.lastCommand),last_full_wrench:[...this.lastFullWrench],step_index:this.stepIndex};}
    loadState(state){if(state?.version!==1||![state.propeller_rps,state.rudder_rad,...state.last_full_wrench].every(Number.isFinite))throw new Error("Invalid Vehicle B MMG checkpoint state.");this.propellerRps=state.propeller_rps;this.rudderRad=state.rudder_rad;this.lastCommand=structuredClone(state.last_command);this.lastFullWrench=[...state.last_full_wrench];this.stepIndex=state.step_index;}
}
