import {ForceModel} from "./force-model.js";
function appWorldVectorToBody3(vector,yaw=0){const cos=Math.cos(yaw),sin=Math.sin(yaw),stbd=(vector.x||0)*cos-(vector.z||0)*sin,fwd=(vector.x||0)*sin+(vector.z||0)*cos;return[fwd,stbd,-(vector.y||0)];}
function cross3(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}
export class HydrostaticsAndWaves extends ForceModel{
 constructor(){super();this.lastFullWrench=[0,0,0,0,0,0];}
 computeWrench(ctx){const submergedState=ctx.env?.submergedState;if(!submergedState||!submergedState.perPrimitive?.length){const fallback=this.computeHullSampleFallback(ctx);if(fallback)return fallback;this.lastFullWrench=[0,0,0,0,0,0];return[0,0,0];}const params=ctx.params,rho=params.buoyancy?.rho||params.restoring?.waterDensity||1025,g=params.buoyancy?.g||params.restoring?.gravity||9.81,horizontalWaveScale=params.buoyancy?.horizontalWaveScale??1,mass=params.massProps.mass||0,yaw=ctx.state.eulerAngles.yaw||0,cg=params.massProps.cg||{x:0,y:0,z:0};let forceBody=[0,0,0],momentBody=[0,0,0];submergedState.perPrimitive.forEach((entry)=>{if(entry.volume<=0)return;const normal=entry.surfaceNormalWorld||{x:0,y:1,z:0},buoyWorld={x:normal.x*rho*g*entry.volume*horizontalWaveScale,y:normal.y*rho*g*entry.volume,z:normal.z*rho*g*entry.volume*horizontalWaveScale},buoyBody=appWorldVectorToBody3(buoyWorld,yaw),r=[entry.centroidBody[0]-(cg.x||0),entry.centroidBody[1]-(cg.y||0),entry.centroidBody[2]-(cg.z||0)],m=cross3(r,buoyBody);forceBody=forceBody.map((value,idx)=>value+buoyBody[idx]);momentBody=momentBody.map((value,idx)=>value+m[idx]);});const gravityBody=appWorldVectorToBody3({x:0,y:-mass*g,z:0},yaw);forceBody=forceBody.map((value,idx)=>value+gravityBody[idx]);this.lastFullWrench=[forceBody[0],forceBody[1],forceBody[2],momentBody[0],momentBody[1],momentBody[2]];return[forceBody[0],forceBody[1],momentBody[2]];}
 computeHullSampleFallback(ctx){const samples=ctx.env?.hullWaterSamples||[];if(!samples.length)return null;const params=ctx.params,rho=params.buoyancy?.rho||params.restoring?.waterDensity||1025,g=params.buoyancy?.g||params.restoring?.gravity||9.81,beam=Math.max(params.geometry.beam||1,0.001),length=Math.max(params.geometry.length||1,0.001),draft=Math.max(params.geometry.draft||0.001,0.001),panelArea=beam*length/samples.length,scale=params.buoyancy?.horizontalWaveScale??1;let surge=0,sway=0,yaw=0;samples.forEach((sample)=>{const depth=Math.max(sample.depth||0,0);if(depth<=0)return;const normal=sample.waterNormal||{x:0,y:1,z:0},forceScale=rho*g*panelArea*Math.min(depth,draft)*scale,surgeForce=forceScale*(normal.z||0),swayForce=forceScale*(normal.x||0);surge+=surgeForce;sway+=swayForce;const offsetNedX=sample.localOffset?sample.localOffset.z:0;yaw+=swayForce*offsetNedX;});this.lastFullWrench=[surge,sway,0,0,0,yaw];return[surge,sway,yaw];}
}
export class WaveExcitation extends ForceModel{constructor(){super();this.lastFullWrench=[0,0,0,0,0,0];}computeWrench(ctx){const resolved=ctx.params?.hydrodynamics?.wave_excitation;if(resolved){const hasStep=ctx.stepIndex!==undefined||ctx.step!==undefined,step=ctx.stepIndex??ctx.step??0,dt=ctx.dt??ctx.params?.integration?.dt??0,time=hasStep?step*dt:(ctx.t??0),phase=(ctx.env?.wavePhaseRad??0)+resolved.omega_rad_s*time,amplitude=ctx.env?.waveAmplitudeM??ctx.params?.environment?.regularWave?.amplitude??1;this.lastFullWrench=resolved.complex_force.map(([real,imag])=>amplitude*(real*Math.cos(phase)-imag*Math.sin(phase)));return[this.lastFullWrench[0],this.lastFullWrench[1],this.lastFullWrench[5]];}const samples=ctx.env?.hullWaterSamples||[];if(!samples.length){this.lastFullWrench=[0,0,0,0,0,0];return[0,0,0];}const params=ctx.params,rho=params.restoring.waterDensity||1025,g=params.restoring.gravity||9.81,beam=Math.max(params.geometry.beam||1,0.001),length=Math.max(params.geometry.length||1,0.001),panelArea=beam*length/samples.length;let sway=0,yaw=0;samples.forEach((sample)=>{const depth=Math.max(sample.depth||0,0);if(depth<=0)return;const normal=sample.waterNormal||{x:0,y:1,z:0},sideForce=rho*g*panelArea*Math.min(depth,params.geometry.draft||depth)*(normal.x||0)*0.04;sway+=sideForce;const offsetNedX=sample.localOffset?sample.localOffset.z:0;yaw+=sideForce*offsetNedX;});this.lastFullWrench=[0,sway,0,0,0,yaw];return[0,sway,yaw];}}
