export type ProvenanceKind="measured"|"manufacturer"|"mss"|"capytaine"|"geometry-derived"|"design-assumption"|"literature"|"empirical"|"estimated"|"identified";
import {SURVEYOR_PUBLIC_SPEC} from "./surveyor.ts";
export * from "./surveyor.ts";
export interface Provenance {kind:ProvenanceKind;source:string;checksum?:string;uncertainty?:string;notes?:string;operating_range?:string;fit_data?:string;limitations?:string[]}
export interface Parameter<T=number>{value:T;unit:string;provenance:Provenance}
export interface EffectorDefinition {id:string;kind:"fixed-thruster"|"azimuth-thruster"|"propeller"|"rudder";position_m:[number,number,number];orientation_rad:[number,number,number];command_range:[number,number];time_constant_s:number;rate_limit_per_s:number;dead_zone:number;max_power_w:number;failure_mode:"healthy"|"failed-off"|"stuck";provenance?:Provenance}
export interface EvidenceTier {id:string;status:"available-pending-execution"|"passed"|"failed"|"blocked-missing-primary-source"|"executed-comparison-no-acceptance-gate"|"experimental-trajectory-reference"|"experimental-trajectory-scored-fail"|"architecture-variant-reference";claim:string;target:string}
export interface ValidationScope {status:"validated"|"model-structure-only"|"model-structure-trajectory-reference"|"model-structure-trajectory-scored-fail"|"allocation-demonstrated-dynamics-unvalidated";references:string[];claim:string;limitations:string[];evidence_tiers?:EvidenceTier[]}
export interface VehicleDefinition {schema_version:1;id:string;name:string;plant:"planar3"|"coupled6";parametric_hull?:{form:"generalised-wigley";exponents:{a:Parameter;b:Parameter};demihull_separation?:Parameter;source:string};aerodynamics?:{frontal_area:Parameter;lateral_area:Parameter;centre_of_pressure_z:Parameter};maneuvering_model?:{type:"mmg";parameter_set_id:string;stage:"model-structure"|"usv-scale";selectable:boolean;production_path?:"integrated-coupled6"};geometry:{length:Parameter;width:Parameter;draft:Parameter};mass:Parameter;inertia:Parameter<[number,number,number]>;hydrostatics?:{gm_transverse:Parameter;gm_longitudinal:Parameter};potential_flow?:{artifact_path:string;status:"integration-complete-validation-blocked-bootstrap-mesh"|"analytic-parametric-solver-output"|"reviewed-solver-output";supplies:["added-mass","radiation-damping","wave-excitation","hydrostatic-stiffness"];provenance:{kind:"capytaine";source:string;mesh_status:"bootstrap"|"analytic-parametric"|"reviewed";limitations:string[]}};effectors:EffectorDefinition[];damping:{linear_viscous:Parameter<number[]>;quadratic_viscous:Parameter<number[]>;roll_viscous_decomposition?:{status:"ikeda-zero-speed-lower-bound";artifact_path:string;friction:Parameter;eddy_equivalent_quadratic:Parameter;bilge_keel:Parameter;lift:Parameter;limitations:string[]}};validation:ValidationScope}

export function validateVehicle(vehicle:VehicleDefinition):void{
  if(vehicle.schema_version!==1||!vehicle.id)throw new Error("Vehicle schema_version 1 and id are required.");
  if(vehicle.mass.value<=0||vehicle.geometry.length.value<=0||vehicle.geometry.width.value<=0||vehicle.geometry.draft.value<=0)throw new Error("Vehicle mass and dimensions must be positive.");
  if(vehicle.effectors.length===0)throw new Error("At least one effector is required.");
  for(const effector of vehicle.effectors){if(!effector.id||effector.command_range[0]>=effector.command_range[1]||effector.time_constant_s<0||effector.rate_limit_per_s<=0)throw new Error(`Invalid effector ${effector.id}.`);}
  if(vehicle.plant==="coupled6"){
    if(!vehicle.hydrostatics||vehicle.hydrostatics.gm_transverse.value<=0||vehicle.hydrostatics.gm_longitudinal.value<=0)throw new Error("coupled6 vehicles require positive GM_T and GM_L.");
    const magnitude=[...vehicle.damping.linear_viscous.value,...vehicle.damping.quadratic_viscous.value].reduce((s,v)=>s+Math.abs(v),0);
    if(magnitude===0)throw new Error("coupled6 vehicles require non-zero viscous damping.");
    if(vehicle.damping.linear_viscous.provenance.kind==="capytaine"||vehicle.damping.quadratic_viscous.provenance.kind==="capytaine")throw new Error("Capytaine cannot supply viscous damping provenance.");
  }
}

const p=(value:number,unit:string,kind:ProvenanceKind,source:string):Parameter=>({value,unit,provenance:{kind,source}});
const effector=(id:string,kind:EffectorDefinition["kind"],position_m:[number,number,number]):EffectorDefinition=>({id,kind,position_m,orientation_rad:[0,0,0],command_range:[-1,1],time_constant_s:0.35,rate_limit_per_s:3,dead_zone:0.02,max_power_w:4000,failure_mode:"healthy"});

export const VEHICLES:Record<string,VehicleDefinition>={
  "vehicle-a-otter":{schema_version:1,id:"vehicle-a-otter",name:"Otter differential-thrust USV",plant:"planar3",geometry:{length:p(2,"m","mss","MSS Otter"),width:p(1.08,"m","mss","MSS Otter"),draft:p(0.2,"m","mss","MSS Otter")},mass:p(55,"kg","mss","MSS Otter"),inertia:{value:[14,24,30],unit:"kg m^2",provenance:{kind:"mss",source:"MSS Otter"}},effectors:[effector("port","fixed-thruster",[-0.4,-0.395,0]),effector("starboard","fixed-thruster",[-0.4,0.395,0])],damping:{linear_viscous:{value:[24,33,2],unit:"SI diagonal",provenance:{kind:"mss",source:"MSS Otter"}},quadratic_viscous:{value:[2,8,1],unit:"SI diagonal",provenance:{kind:"mss",source:"MSS Otter"}}},validation:{status:"validated",references:["MSS c660120"],claim:"Planar maneuvering validated at pinned tolerances.",limitations:["MSS evidence applies only to planar3."]}},
  "vehicle-b-rudder":{schema_version:1,id:"vehicle-b-rudder",name:"USV propeller/rudder monohull",plant:"coupled6",geometry:{length:p(4.5,"m","estimated","ICRA bootstrap hull"),width:p(1.4,"m","estimated","ICRA bootstrap hull"),draft:p(0.45,"m","estimated","ICRA bootstrap hull")},mass:p(650,"kg","estimated","ICRA bootstrap hull"),inertia:{value:[120,900,950],unit:"kg m^2",provenance:{kind:"geometry-derived",source:"box bootstrap"}},effectors:[effector("propeller","propeller",[-1.8,0,0]),effector("rudder","rudder",[-2,0,0])],damping:{linear_viscous:{value:[80,210,320,180,410,520],unit:"SI diagonal",provenance:{kind:"empirical",source:"Vehicle B engineering bootstrap diagonal estimate",uncertainty:"Uncalibrated; replace with independent free-decay identification",operating_range:"zero-speed small-amplitude free decay; bootstrap only",fit_data:"none",limitations:["Not fitted to Vehicle B measurements.","Not a complete Ikeda-method calculation."]}},quadratic_viscous:{value:[45,300,380,240,500,650],unit:"SI diagonal",provenance:{kind:"empirical",source:"Vehicle B engineering bootstrap diagonal estimate",uncertainty:"Uncalibrated; replace with independent free-decay identification",operating_range:"zero-speed free decay up to 10 deg roll initial displacement; bootstrap only",fit_data:"none",limitations:["Ikeda et al. motivates component separation but these coefficients are not a full Ikeda-method result.","No bilge-keel or hull-section integration has been performed."]}}},validation:{status:"model-structure-only",references:["Yasukawa & Yoshimura 2015 KVLCC2 MMG calculation","MARIN L7 free-running indices published in Yasukawa & Yoshimura 2015","SIMMAN KVLCC2/KCS optional full-trajectory cross-check","Capytaine potential-flow coefficients"],claim:"The MARIN 620 rpm scalar-index comparison and L3 coefficient diagnostic execute reproducibly. Exact Yasukawa calculated-maneuver reproduction is blocked on missing primary operating-point inputs. None validates Vehicle B USV coefficients.",limitations:["Experimental targets are scalar maneuver indices for the 7.00 m L7 model at 1/45.7 scale, not full trajectories.","The MARIN resistance is an explicitly reported straight-ahead trim assumption until the measured resistance curve is available.","Restricted SIMMAN data is still required for full-trajectory validation.","Independent Vehicle B USV-scale maneuver data is required."],evidence_tiers:[{id:"kvlcc2-mmg-reference-reproduction",status:"blocked-missing-primary-source",claim:"Implementation comparison against the paper's Cal. column requires the exact L7 resistance and propeller operating point.",target:"Tables 4-5 Cal."},{id:"kvlcc2-experimental-maneuver-indices",status:"executed-comparison-no-acceptance-gate",claim:"Comparison against MARIN free-running L7 scalar indices at 620 rpm, not full trajectories.",target:"Tables 4-5 Exp.; L7 model, 7.00 m Lpp, 1/45.7 scale"}]}},
  "vehicle-c-azimuth":{schema_version:1,id:"vehicle-c-azimuth",name:"Dual-azimuth overactuated USV",plant:"coupled6",geometry:{length:p(3.5,"m","estimated","ICRA bootstrap hull"),width:p(1.8,"m","estimated","ICRA bootstrap hull"),draft:p(0.3,"m","estimated","ICRA bootstrap hull")},mass:p(420,"kg","estimated","ICRA bootstrap hull"),inertia:{value:[140,390,460],unit:"kg m^2",provenance:{kind:"geometry-derived",source:"catamaran bootstrap"}},effectors:[effector("azimuth-port","azimuth-thruster",[-1,-0.65,0]),effector("azimuth-starboard","azimuth-thruster",[-1,0.65,0])],damping:{linear_viscous:{value:[65,130,190,160,280,360],unit:"SI diagonal",provenance:{kind:"empirical",source:"Vehicle C engineering bootstrap diagonal estimate",uncertainty:"Uncalibrated; replace with independent free-decay identification",operating_range:"zero-speed small-amplitude free decay; bootstrap only",fit_data:"none",limitations:["Not fitted to Vehicle C measurements.","Not a complete Ikeda-method calculation."]}},quadratic_viscous:{value:[40,180,230,220,360,420],unit:"SI diagonal",provenance:{kind:"empirical",source:"Vehicle C engineering bootstrap diagonal estimate",uncertainty:"Uncalibrated; replace with independent free-decay identification",operating_range:"zero-speed free decay up to 10 deg roll initial displacement; bootstrap only",fit_data:"none",limitations:["No dual-hull viscous interaction or appendage calibration.","No bilge-keel or hull-section integration has been performed."]}}},validation:{status:"allocation-demonstrated-dynamics-unvalidated",references:["AERO4River applied-wrench 3-DOF projection through coupled6"],claim:"Control allocation and composability demonstrated; behavioral dynamics not independently validated.",limitations:["AERO4River does not validate dual water-azimuth propulsion or full six-axis behavior."]}}
};
VEHICLES["searobotics-surveyor-m1.8"]={schema_version:1,id:"searobotics-surveyor-m1.8",name:"SeaRobotics SR-Surveyor M1.8 (two-body common-task approximation)",plant:"planar3",geometry:{length:p(SURVEYOR_PUBLIC_SPEC.length_m,"m","manufacturer","SeaRobotics M1.8 specification sheet"),width:p(SURVEYOR_PUBLIC_SPEC.beam_m,"m","manufacturer","SeaRobotics M1.8 specification sheet"),draft:p(SURVEYOR_PUBLIC_SPEC.draft_m,"m","manufacturer","SeaRobotics M1.8 specification sheet")},mass:p(SURVEYOR_PUBLIC_SPEC.mass_kg,"kg","manufacturer","SeaRobotics M1.8 specification sheet"),inertia:{value:SURVEYOR_PUBLIC_SPEC.inertia_diagonal_kg_m2,unit:"kg m^2",provenance:{kind:"geometry-derived",source:"artifacts/rl-campaign/surveyor-vehicle-model.json; two-pontoon plus centered-deck approximation",uncertainty:"Not measured; sensitivity bounds and assumptions are recorded in the source artifact"}},effectors:SURVEYOR_PUBLIC_SPEC.effectors.map((x:any)=>({...effector(x.id,"fixed-thruster",x.position_body_m),command_range:SURVEYOR_PUBLIC_SPEC.dynamics.hardware_command_range,time_constant_s:SURVEYOR_PUBLIC_SPEC.dynamics.time_constant_s,rate_limit_per_s:SURVEYOR_PUBLIC_SPEC.dynamics.rate_limit_per_s??Number.MAX_VALUE,dead_zone:SURVEYOR_PUBLIC_SPEC.dynamics.deadband_command,max_power_w:1000,provenance:{kind:"design-assumption",source:"artifacts/rl-campaign/surveyor-vehicle-model.json"}})),damping:{linear_viscous:{value:SURVEYOR_PUBLIC_SPEC.damping.linear_planar,unit:"SI diagonal",provenance:{kind:"estimated",source:"Surveyor integration bootstrap retained in source model",uncertainty:"Uncalibrated; FIU free-decay/field data required"}},quadratic_viscous:{value:SURVEYOR_PUBLIC_SPEC.damping.quadratic_planar,unit:"SI diagonal",provenance:{kind:"estimated",source:"Surveyor integration bootstrap retained in source model",uncertainty:"Uncalibrated; FIU tow/field data required"}}},validation:{status:"model-structure-only",references:["SeaRobotics SR-Surveyor M1.8 specification sheet","FIU-MoRA-Lab searobotics_surveyor control API","artifacts/rl-campaign/surveyor-vehicle-model.json"],claim:"Node common-task resolution uses the versioned two-body model; geometry, actuator and damping assumptions remain unvalidated.",limitations:["Command-to-force mapping is assumed at 1 N per integer command.","Thruster positions and inertia are documented approximations, not measured values.","The 0.35 s lag is borrowed from the generic Vehicle A fallback, not independently estimated for Surveyor hardware.","FIU bollard-pull and maneuver data are required before physical claims."]}};
VEHICLES["vehicle-a-otter"].hydrostatics={gm_transverse:p(0.13,"m","mss","MSS Otter coefficient set"),gm_longitudinal:p(0.24,"m","mss","MSS Otter coefficient set")};
VEHICLES["vehicle-b-rudder"].hydrostatics={gm_transverse:p(0.168,"m","geometry-derived","0.12 × beam bootstrap; retain beside independent Capytaine value"),gm_longitudinal:p(0.54,"m","geometry-derived","0.12 × length bootstrap; retain beside independent Capytaine value")};
VEHICLES["vehicle-b-rudder"].potential_flow={artifact_path:"artifacts/capytaine/vehicle-b-resolved.json",status:"integration-complete-validation-blocked-bootstrap-mesh",supplies:["added-mass","radiation-damping","wave-excitation","hydrostatic-stiffness"],provenance:{kind:"capytaine",source:"Capytaine 2.3.1 parametric displaced-volume bootstrap",mesh_status:"bootstrap",limitations:["Not validation evidence until reviewed hull mesh and mesh convergence replace the bootstrap.","Radiation memory is omitted; coefficients are fixed at the resolved frequency.","Viscous damping remains independently empirical and uncalibrated."]}};
VEHICLES["vehicle-b-rudder"].maneuvering_model={type:"mmg",parameter_set_id:"vehicle-b-usv-bootstrap",stage:"usv-scale",selectable:true,production_path:"integrated-coupled6"};
VEHICLES["vehicle-b-rudder"].validation={status:"model-structure-trajectory-scored-fail",references:["Yasukawa & Yoshimura 2015 KVLCC2 MMG calculation","MARIN L7 experimental indices published by Yasukawa & Yoshimura 2015","SIMMAN 2008 MARIN raw free-running trajectories obtained through third-party redistribution","wPCC v4 twin-screw trajectory variant","Capytaine potential-flow coefficients"],claim:"The MMG simulator has been scored against six measured MARIN single-screw KVLCC2 trajectories using measured rudder and samplewise propeller RPM. The current literature-coefficient parameterization fails the precommitted trajectory/IMO tolerances. No evidence validates Vehicle B USV-scale coefficients.",limitations:["The MARIN reference describes a 7.00 m, 1/45.7 KVLCC2 model and is represented in full-scale-equivalent trajectory coordinates.","SIMMAN reuse rights are unconfirmed; raw data is cache-only and excluded from releases.","Measured inputs replay exactly, but current trajectory agreement fails; this is not a validation pass.","Independent Vehicle B USV-scale maneuver data is still required."],evidence_tiers:[{id:"kvlcc2-mmg-reference-reproduction",status:"blocked-missing-primary-source",claim:"Implementation comparison against the paper's Cal. column requires the exact L7 resistance input.",target:"Tables 4-5 Cal."},{id:"kvlcc2-experimental-maneuver-indices",status:"executed-comparison-no-acceptance-gate",claim:"Published MARIN scalar indices, retained separately from raw trajectories.",target:"Tables 4-5 Exp."},{id:"kvlcc2-marin-trajectory-comparison",status:"experimental-trajectory-scored-fail",claim:"Measured single-screw trajectories scored with measured rudder/RPM; current model fails fixed limits.",target:"SIMMAN 2008 MARIN FREE KVLCC2"},{id:"wpcc-trajectory-comparison",status:"architecture-variant-reference",claim:"Measured twin-screw motoring zig-zags; architecture-variant evidence only.",target:"wPCC v4"}]};
VEHICLES["vehicle-c-azimuth"].hydrostatics={gm_transverse:p(0.216,"m","geometry-derived","0.12 × beam bootstrap; retain beside independent Capytaine value"),gm_longitudinal:p(0.42,"m","geometry-derived","0.12 × length bootstrap; retain beside independent Capytaine value")};
VEHICLES["vehicle-c-azimuth"].potential_flow={artifact_path:"artifacts/capytaine/vehicle-c-resolved.json",status:"integration-complete-validation-blocked-bootstrap-mesh",supplies:["added-mass","radiation-damping","wave-excitation","hydrostatic-stiffness"],provenance:{kind:"capytaine",source:"Capytaine 2.3.1 parametric displaced-volume bootstrap",mesh_status:"bootstrap",limitations:["Not validation evidence until reviewed dual-hull mesh and mesh convergence replace the bootstrap.","Radiation memory is omitted; coefficients are fixed at the resolved frequency.","Viscous damping remains independently empirical and uncalibrated."]}};
const hullSource="Parametric Hull Specification — analytic generalised Wigley design";
Object.assign(VEHICLES["vehicle-b-rudder"],{
  geometry:{length:p(4,"m","design-assumption",hullSource),width:p(1.2,"m","design-assumption",hullSource),draft:p(.3,"m","design-assumption",hullSource)},
  mass:p(739.1,"kg","geometry-derived",hullSource),
  inertia:{value:[153.7,739.1,739.1],unit:"kg m^2",provenance:{kind:"design-assumption",source:`${hullSource}; empirical radii of gyration`}},
  parametric_hull:{form:"generalised-wigley",exponents:{a:p(.75,"1","design-assumption",hullSource),b:p(.85,"1","design-assumption",hullSource)},source:"validation/hulls/vehicle-hull-specification.md"},
  aerodynamics:{frontal_area:p(.60,"m^2","geometry-derived",hullSource),lateral_area:p(1.80,"m^2","geometry-derived",hullSource),centre_of_pressure_z:p(.38,"m","design-assumption",hullSource)},
  hydrostatics:{gm_transverse:p(.2716,"m","geometry-derived",`${hullSource}; analytic value retained beside Capytaine`),gm_longitudinal:p(4.117,"m","geometry-derived",`${hullSource}; analytic value retained beside Capytaine`)},
  potential_flow:{artifact_path:"artifacts/capytaine/vehicle-b-parametric.json",status:"analytic-parametric-solver-output",supplies:["added-mass","radiation-damping","wave-excitation","hydrostatic-stiffness"],provenance:{kind:"capytaine",source:"Capytaine analytic Wigley mesh convergence campaign",mesh_status:"analytic-parametric",limitations:["Representative design geometry is not physical validation.","Radiation memory is omitted; coefficients are fixed at the resolved frequency.","Viscous damping remains independently sourced."]}}
});
Object.assign(VEHICLES["vehicle-c-azimuth"],{
  geometry:{length:p(3.5,"m","design-assumption",hullSource),width:p(1.98,"m","design-assumption",hullSource),draft:p(.25,"m","design-assumption",hullSource)},
  mass:p(313.5,"kg","geometry-derived",hullSource),
  inertia:{value:[196.6,240.0,240.0],unit:"kg m^2",provenance:{kind:"design-assumption",source:`${hullSource}; empirical radii of gyration`}},
  parametric_hull:{form:"generalised-wigley",exponents:{a:p(.80,"1","design-assumption",hullSource),b:p(.90,"1","design-assumption",hullSource)},demihull_separation:p(1.62,"m","design-assumption",hullSource),source:"validation/hulls/vehicle-hull-specification.md"},
  aerodynamics:{frontal_area:p(.70,"m^2","geometry-derived",hullSource),lateral_area:p(1.60,"m^2","geometry-derived",hullSource),centre_of_pressure_z:p(.42,"m","design-assumption",hullSource)},
  hydrostatics:{gm_transverse:p(3.7232,"m","geometry-derived",`${hullSource}; separation term retained; analytic value not overwritten`),gm_longitudinal:p(3.735,"m","geometry-derived",`${hullSource}; analytic value retained beside Capytaine`)},
  potential_flow:{artifact_path:"artifacts/capytaine/vehicle-c-parametric.json",status:"analytic-parametric-solver-output",supplies:["added-mass","radiation-damping","wave-excitation","hydrostatic-stiffness"],provenance:{kind:"capytaine",source:"Capytaine full dual-demihull analytic Wigley mesh convergence campaign",mesh_status:"analytic-parametric",limitations:["Representative design geometry is not physical validation.","No port/starboard symmetry reduction was used.","Viscous damping remains independently sourced."]}}
});
const bProp=VEHICLES["vehicle-b-rudder"].effectors.find(({id})=>id==="propeller")!,bRudder=VEHICLES["vehicle-b-rudder"].effectors.find(({id})=>id==="rudder")!;
Object.assign(bProp,{position_m:[-1.85,0,-.20],provenance:{kind:"design-assumption",source:hullSource}});Object.assign(bRudder,{position_m:[-1.96,0,-.18],rate_limit_per_s:15*Math.PI/180,provenance:{kind:"design-assumption",source:hullSource}});
for(const effector of VEHICLES["vehicle-c-azimuth"].effectors){Object.assign(effector,{position_m:[-1.5,effector.id.includes("port")?-.81:.81,-.18],rate_limit_per_s:30*Math.PI/180,provenance:{kind:"design-assumption",source:hullSource}});}
VEHICLES["vehicle-b-rudder"].damping.linear_viscous.value[3]=1.1099326722941965;VEHICLES["vehicle-b-rudder"].damping.quadratic_viscous.value[3]=0.0013929381840742732;
VEHICLES["vehicle-b-rudder"].damping.roll_viscous_decomposition={status:"ikeda-zero-speed-lower-bound",artifact_path:"artifacts/ikeda/roll-damping-lower-bound.json",friction:p(1.1099326722941965,"N m s/rad","geometry-derived","Kato-Tamiya/Ikeda friction on analytic Wigley wetted area"),eddy_equivalent_quadratic:p(0.0013929381840742732,"N m s^2/rad^2","geometry-derived","Ikeda Lewis-form sectional integration"),bilge_keel:p(0,"N m s/rad","design-assumption","No bilge keel specified"),lift:p(0,"N m s/rad","geometry-derived","Zero-speed evaluation"),limitations:["Representative geometry is not measured.","Lower bound excludes appendages and bilge keels.","Not fitted to free-decay data."]};
VEHICLES["vehicle-c-azimuth"].damping.linear_viscous.value[3]=2.192923674034241;VEHICLES["vehicle-c-azimuth"].damping.quadratic_viscous.value[3]=0.006614752497696677;
VEHICLES["vehicle-c-azimuth"].damping.roll_viscous_decomposition={status:"ikeda-zero-speed-lower-bound",artifact_path:"artifacts/ikeda/roll-damping-lower-bound.json",friction:p(2.192923674034241,"N m s/rad","geometry-derived","Kato-Tamiya/Ikeda friction on both analytic Wigley demihulls"),eddy_equivalent_quadratic:p(0.006614752497696677,"N m s^2/rad^2","geometry-derived","Ikeda Lewis-form sectional integration over both demihulls"),bilge_keel:p(0,"N m s/rad","design-assumption","No bilge keel specified"),lift:p(0,"N m s/rad","geometry-derived","Zero-speed evaluation"),limitations:["Representative geometry is not measured.","Lower bound excludes appendages, tunnel interaction, and bilge keels.","Not fitted to free-decay data."]};
Object.values(VEHICLES).forEach(validateVehicle);
