import assert from "node:assert/strict";
import {ClearSkyOcclusionService,GpsPlugin,HullMotionPlatformStateService,ImuPlugin,SnapshotPlatformStateService} from "../src/index.ts";
const environment:any={wind_ned_mps:[0,0,0],current_ned_mps:[0,0,0],air_temperature_c:15,pressure_pa:101325,humidity_fraction:.5,rain_rate_mm_h:0,visibility_m:10000,fog_extinction_per_m:0,illumination_lux:10000,positioning:{sky_view_fraction:1,visible_satellites:12,hdop:1,vdop:1.5,pdop:1.8,multipath_factor:0,gnss_interference_factor:0}};
const truth=()=>({position_ned_m:[10,20,-1],velocity_body_mps:[2,0,0],acceleration_body_mps2:[.1,.2,.3],angular_rate_body_rad_s:[.01,.02,.03],attitude_rad:[0,0,.4]});let seed=.37;const random=()=>{seed=(seed*3.71+.17)%1;return seed;};
const gps=new GpsPlugin();gps.init({rate_hz:2,latency_s:.1,base_horizontal_std_m:.5},{seededRng:random,groundTruth:truth,environment:()=>environment,skyOcclusion:new ClearSkyOcclusionService()});assert.equal(gps.sample({stepIndex:0,simTimeS:0,lifecycleState:"ACTIVE"}),null);const fix=gps.sample({stepIndex:2,simTimeS:.1,lifecycleState:"ACTIVE"});assert.equal(fix?.valid,true);assert.equal(fix?.timestampS,0);assert.equal(fix?.payload?.visible_satellites,12);assert.notDeepEqual(fix?.payload?.position_ned_m,[10,20,-1]);
const denied=new GpsPlugin();denied.init({latency_s:0},{seededRng:()=>.5,groundTruth:truth,environment:()=>({...environment,positioning:{...environment.positioning,visible_satellites:2}}),skyOcclusion:new ClearSkyOcclusionService()});assert.equal(denied.sample({stepIndex:0,simTimeS:0,lifecycleState:"ACTIVE"})?.valid,false);
const platform=new SnapshotPlatformStateService(()=>({actuator_states:[],actuator_energy_j:0,propulsion_energy_j:0,actuator_power_w:0,vibration_rms_mps2:.1,component_temperature_c:{imu:35}})),imu=new ImuPlugin();imu.init({rate_hz:20,latency_s:0,accel_noise_std_mps2:0,gyro_noise_std_rad_s:0},{seededRng:random,groundTruth:truth,platformState:platform});const first=imu.sample({stepIndex:0,simTimeS:0,lifecycleState:"ACTIVE"})!,second=imu.sample({stepIndex:1,simTimeS:.05,lifecycleState:"ACTIVE"})!;assert.equal(first.valid,true);assert.notDeepEqual(first.payload.accel_bias_mps2,second.payload.accel_bias_mps2,"IMU bias must accumulate drift over time.");assert.deepEqual(second.payload.orientation_rad,[0,0,.4]);gps.dispose();denied.dispose();imu.dispose();

function conditioned(surface:any,sensitivities=true){let value=.271828;const rng=()=>{value=(value*3.71+.17)%1;return value;},base=new SnapshotPlatformStateService(()=>({actuator_states:[],actuator_energy_j:0,propulsion_energy_j:0,actuator_power_w:0})),service=new HullMotionPlatformStateService(base,()=>({surface}),truth),plugin=new ImuPlugin();plugin.init({rate_hz:20,latency_s:0,accel_bias_std_mps2:0,gyro_bias_std_rad_s:0,accel_drift_std_per_sqrt_s:0,gyro_drift_std_per_sqrt_s:0,...(sensitivities?{}:{accel_vibration_sensitivity:0,gyro_vibration_sensitivity:0})},{seededRng:rng,groundTruth:truth,platformState:service});return{plugin,sample:plugin.sample({stepIndex:0,simTimeS:0,lifecycleState:"ACTIVE"})!};}
const calm=conditioned({sea_state_beaufort:0,significant_wave_height_m:0}),rough=conditioned({sea_state_beaufort:6,significant_wave_height_m:4}),rigidBodyOnly=conditioned({sea_state_beaufort:6,significant_wave_height_m:4},false);
assert.equal(calm.sample.payload.vibration_rms_mps2,0);
assert.ok(rough.sample.payload.vibration_rms_mps2>0&&rough.sample.payload.accel_noise_std_mps2>calm.sample.payload.accel_noise_std_mps2&&rough.sample.payload.gyro_noise_std_rad_s>calm.sample.payload.gyro_noise_std_rad_s);
assert.deepEqual(rigidBodyOnly.sample.payload.acceleration_body_mps2.map((x,i)=>x-(truth().acceleration_body_mps2![i])),calm.sample.payload.acceleration_body_mps2.map((x,i)=>x-(truth().acceleration_body_mps2![i])),"The same rigid-body truth and random stream must produce the baseline noise independently of sea state.");
assert.notDeepEqual(rough.sample.payload.acceleration_body_mps2,rigidBodyOnly.sample.payload.acceleration_body_mps2,"Hull vibration must be an additive noise-floor effect distinct from rigid-body motion.");
const delta={vibration_rms_mps2:rough.sample.payload.vibration_rms_mps2,accel_noise_std_delta_mps2:rough.sample.payload.accel_noise_std_mps2-calm.sample.payload.accel_noise_std_mps2,gyro_noise_std_delta_rad_s:rough.sample.payload.gyro_noise_std_rad_s-calm.sample.payload.gyro_noise_std_rad_s,acceleration_output_delta_mps2:rough.sample.payload.acceleration_body_mps2.map((x,i)=>x-rigidBodyOnly.sample.payload.acceleration_body_mps2[i])};
for(const item of [calm,rough,rigidBodyOnly])item.plugin.dispose();
console.log("IMU sea-state vibration comparison passed.",JSON.stringify(delta));
console.log("GPS and IMU sensor contract tests passed.");
