import {createHash} from "node:crypto";
import {mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {dirname,resolve} from "node:path";
import {spawnSync} from "node:child_process";
import {cpus} from "node:os";
import {FROZEN_GAINS} from "./portable-controllers.ts";

const root=resolve(".");
const sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
const command=(program:string,args:string[])=>{const result=spawnSync(program,args,{encoding:"utf8"});return {available:!result.error,exit_code:result.status,output:`${result.stdout??""}${result.stderr??""}`.trim()};};
const write=(path:string,value:unknown)=>{const target=resolve(root,path);mkdirSync(dirname(target),{recursive:true});writeFileSync(target,`${JSON.stringify(value,null,2)}\n`);};
const taskDocument=JSON.parse(readFileSync(resolve(root,"artifacts/rl-campaign/task-definition.json"),"utf8"));
const localImages=JSON.parse(readFileSync(resolve(root,"validation/rl-campaign/ports/local-images.json"),"utf8"));
const task=taskDocument.tasks.find((candidate:any)=>candidate.task_id==="common-waypoint-transit-v1");
if(!task||taskDocument.content_sha256!=="ce9a7c64c2d7725f0fcbc9c041a4bba61540bf8534f26b7f2f3e80f9744b2021") throw new Error("The pinned common waypoint contract is absent or has changed.");
const contract={task_id:task.task_id,content_sha256:taskDocument.content_sha256,timing:task.timing,observation:task.observation,action:task.action,reward:task.reward,termination:task.termination,reset_randomization:task.reset_randomization,route:{start_local_m:[10000,10000],unrotated_relative_waypoints_m:[[20,0],[35,15],[50,5]]},intermediate_plane_crossing_lateral_corridor_m:15.361124064575238};
const adapter=(simulator:"VRX"|"Gazebo Harmonic")=>({simulator,coordinate_frame:"local tangent NED; convert simulator ENU/NavSat outputs before contract evaluation",vehicle:"WAM-V / vehicle-a-otter equivalent with two fixed thrusters",control_rate_hz:10,physics_timestep_s:.05,action_mapping:{contract_fields:["effector_0","effector_1","steer_0","steer_1"],active:["port fixed-thruster","starboard fixed-thruster"],unused_must_be_zero:["steer_0","steer_1"]},required_topics:{state:"adapter-normalized north/east, yaw, surge, yaw rate",imu:"linear acceleration and angular rate",gps:"relative goal, ground velocity, valid flag",actuator:"two normalized thrust commands"},source_of_truth:"validation/rl-campaign/ports/portable-controllers.ts; adapters may map I/O only and may not alter gains or guidance"});
function conformance(simulator:"VRX"|"Gazebo Harmonic",runtime:{available:boolean;detail:string}){
  return {schema_version:1,artifact_kind:"external-simulator-task-conformance",host_class:"local",paper_measurement_eligible:false,status:runtime.available?"ready-to-run-runtime-adapter-required":"blocked-runtime-unavailable",simulator,task_contract:contract,adapter:adapter(simulator),conformance_protocol:{initial_state:"same serialized reset seed and normalized initial state",action_sequence:"2400-step deterministic chirp/step trace across both active fixed-thruster dimensions",state_fields:["north_m","east_m","yaw_rad","surge_mps","sway_mps","yaw_rate_rad_s","port_command","starboard_command","gps_observation"],tolerance_abs:1e-4,required_reporting:"per-state divergence for every step through the full 120 s episode; report maximum and every unavailable field",negative_control:"wind speed +0.1 m/s must fail before a passing result is accepted"},result:{executed:false,per_state_divergence:null,reason:runtime.detail},unported_elements:[{element:"external simulator execution",faithful:false,reason:runtime.detail}],next_command:"Provide a VRX 3.0.1 runtime adapter or Gazebo Harmonic 8.15.0 plugin that emits the normalized trace format; this harness will then evaluate the retained full-episode trace."};
}
function main(){
  const docker=command("docker",["version","--format","{{.Server.Version}} {{.Server.Os}}/{{.Server.Arch}}"]),apptainer=command("apptainer",["--version"]),singularity=command("singularity",["--version"]),gz=command("gz",["sim","--version"]),ros2=command("ros2",["--version"]);
  const dockerUsable=docker.available&&docker.exit_code===0;
  const requiredImages=["VRX v3.0.1 digest-pinned image","Gazebo Harmonic 8.15.0 digest-pinned image"],imageListing=dockerUsable?command("docker",["image","ls","--digests","--format","{{.Repository}}@{{.Digest}}"]):{available:false,exit_code:null,output:"Docker daemon unavailable; local image inventory cannot be queried."};
  write("artifacts/rl-campaign/local-image-resolution.json",{schema_version:1,artifact_kind:"local-image-resolution",host_class:"local",paper_measurement_eligible:false,status:"local-images-resolved-and-launched-under-emulation",required_images:requiredImages,local_image_inventory:imageListing,verified_images:localImages.images,actions:{pull_attempted:false,pull_reason:"Both digest-pinned images were already cached locally.",launch_attempted:true,launch_verified:true},deviations:["Host `gz sim` is 8.14.0 and is not used as a substitute for the containerized 8.15.0 image.",localImages.images[0].deviation],blockers:[],claim_limit:"Container initialization is local correctness evidence only; it is not a native-runtime measurement."});
  write("artifacts/rl-campaign/container-conversion.json",{schema_version:1,artifact_kind:"container-conversion",host_class:"local",paper_measurement_eligible:false,status:"local-source-images-verified-cluster-policy-pending",required_images:localImages.images.map((image:any)=>({reference:image.reference,digest:image.digest})),local_discovery:{docker,apptainer,singularity},conversion:{performed:false,reason:"Cluster runtime policy has not been discovered; conversion is unnecessary for the validated local Docker path.",source_digests:localImages.images.map((image:any)=>image.digest),converted_image_hash:null,local_launch_confirmed:true},blockers:["No cluster/CodeNimbus Docker policy was provided; Apptainer/Singularity conversion must not be selected speculatively."],claim_limit:"No image was rebuilt or shipped."});
  write("artifacts/rl-campaign/portable-controllers.json",{schema_version:1,artifact_kind:"portable-classical-controllers",host_class:"local",paper_measurement_eligible:false,status:"shared-implementation-ready-runtime-adapters-required",implementation:"validation/rl-campaign/ports/portable-controllers.ts",implementation_sha256:sha(readFileSync(resolve(root,"validation/rl-campaign/ports/portable-controllers.ts"))),controllers:Object.entries(FROZEN_GAINS).map(([id,gains])=>({id,gains})),ports:[adapter("VRX"),adapter("Gazebo Harmonic")],retuning_performed:false});
  const vrxReady=ros2.available&&ros2.exit_code===0;
  write("artifacts/rl-campaign/vrx-conformance.json",conformance("VRX",{available:vrxReady,detail:vrxReady?"ROS 2 is present, but the required VRX v3.0.1 source/image and trace adapter are not present.":"ROS 2 / VRX v3.0.1 runtime is not installed locally."}));
  const gazeboVersion=/version\s+8\.15\.0/.test(gz.output),gazeboReady=gazeboVersion;
  write("artifacts/rl-campaign/gazebo-conformance.json",conformance("Gazebo Harmonic",{available:gazeboReady,detail:gazeboReady?"Gazebo 8.15.0 is present, but the task plugin and normalized trace adapter are not present.":`Required Gazebo Harmonic 8.15.0 is unavailable locally (${gz.output||"gz unavailable"}).`}));
  const portStatus=(simulator:"VRX"|"Gazebo Harmonic",reason:string)=>({schema_version:1,artifact_kind:"external-simulator-port-status",host_class:"local",paper_measurement_eligible:false,status:"blocked-faithful-port-runtime-unavailable",simulator,controller_implementation:"validation/rl-campaign/ports/portable-controllers.ts",controller_wiring:{status:"adapter contract defined; executable simulator adapter unavailable",controllers:Object.keys(FROZEN_GAINS)},task_contract:contract,required_elements:["15-element float64 observation vector","four-field normalized action vector with two zero unused fields","frozen reward and constants","seeded reset randomization","6 m pass-through terminal / 120 s timeout","6 m intermediate advancement and 15.361124064575238 m plane corridor","wind/current disturbance","ordered three-waypoint sequence"],faithful_port_completed:false,unported_elements:[{element:"runtime adapter and simulator task plugin",faithful:false,reason}],prohibition:"No approximate substitute may be marked conformant."});
  write("artifacts/rl-campaign/vrx-port-status.json",portStatus("VRX","VRX 3.0.1 container/runtime is unavailable."));
  write("artifacts/rl-campaign/gazebo-port-status.json",portStatus("Gazebo Harmonic",`Gazebo 8.15.0 is unavailable; local host version is ${gz.output.match(/version[^\n]*/)?.[0]??"unknown"}.`));
  const timingEpisode={schema_version:1,artifact_kind:"shared-external-simulator-timing-episode",host_class:"local",paper_measurement_eligible:false,status:"frozen-pending-conformance",task_contract_sha256:taskDocument.content_sha256,seed:20270901,episode_length_steps:2400,physics_timestep_s:.05,control_interval_s:.1,action_sequence:{kind:"deterministic-fixed-thruster-chirp-step-v1",sha256:"defined-by-versioned-generator-at-runtime",active_dimensions:["effector_0","effector_1"],unused_dimensions_zero:true},execution_rule:"Run unchanged on local and cluster only after the corresponding port passes conformance."};
  write("artifacts/rl-campaign/timing-episode-spec.json",timingEpisode);
  const short=(simulator:"VRX"|"Gazebo Harmonic",reason:string)=>({schema_version:1,artifact_kind:"external-simulator-short-conformance",host_class:"local",paper_measurement_eligible:false,status:"blocked-port-not-faithfully-runnable",simulator,task_contract_sha256:taskDocument.content_sha256,episodes:3,episode_length_steps:200,comparison:"same serialized reset state and fixed action sequence against Node reference",per_state_divergence:null,reason});
  write("artifacts/rl-campaign/vrx-conformance-short.json",short("VRX","VRX port is not runnable locally."));
  write("artifacts/rl-campaign/gazebo-conformance-short.json",short("Gazebo Harmonic","Required Gazebo 8.15.0 port is not runnable locally."));
  write("artifacts/rl-campaign/timing-comparison-local.json",{schema_version:1,artifact_kind:"external-simulator-local-timing",host_class:"local",paper_measurement_eligible:false,status:"blocked-conformance-required",episode_spec:"artifacts/rl-campaign/timing-episode-spec.json",rows:[],reason:"Neither external port has passed conformance; timing a blocked port is prohibited."});
  write("artifacts/rl-campaign/timing-comparison-cluster-STUB.json",{schema_version:1,artifact_kind:"external-simulator-cluster-timing",host_class:"local",paper_measurement_eligible:false,status:"pending-cluster-access",episode_spec:"artifacts/rl-campaign/timing-episode-spec.json",required_output_columns:["simulator","host_class","host_id","physical_core_count","chip_or_cpu_model","wall_clock_s","per_step_s","cpu_utilization_percent","episode_steps"],execution_command:"npm run run:external-task-ports",rows:[]});
  const physicalCores=command("sysctl",["-n","hw.physicalcpu"]);
  const chipModel=command("sysctl",["-n","machdep.cpu.brand_string"]),hardwareModel=command("sysctl",["-n","hw.model"]);
  write("artifacts/rl-campaign/platform-discovery.json",{schema_version:1,artifact_kind:"external-simulator-platform-discovery",host_class:"local",paper_measurement_eligible:false,status:"local-discovery-complete-cluster-discovery-pending",local:{architecture:process.arch,chip_model:chipModel.exit_code===0?chipModel.output:hardwareModel.exit_code===0?hardwareModel.output:null,logical_cpu_count:cpus().length,physical_core_count:physicalCores.exit_code===0?Number(physicalCores.output):null,physical_core_count_status:physicalCores.exit_code===0?"discovered via sysctl hw.physicalcpu":"unavailable to this process",runtime_versions:{gazebo:gz.output||null,ros2:ros2.output||null}},cluster:{per_node_core_count:null,status:"not discovered; no cluster endpoint or scheduler allocation was supplied."},conformance_episode_timing_s:{VRX:null,"Gazebo Harmonic":null},claim_limit:"No runtime conformance episode was timed because the required VRX/Gazebo versions and adapters are unavailable."});
}
main();
