#!/usr/bin/env python3
"""ROS 2 Jazzy runtime exporter for the VRX WAM-V bridge.

This process is intentionally observation-only: commands are generated by the
shared TypeScript actuator module before publication, while this node records
the simulator's actual topics and serializes a trace-schema-v2 compatible
sample stream.
"""
import json
import math
import pathlib
from rclpy.node import Node
import rclpy
from nav_msgs.msg import Odometry
from sensor_msgs.msg import Imu, NavSatFix
from std_msgs.msg import Float64

class VrxTraceExporter(Node):
    def __init__(self):
        super().__init__('vrx_trace_exporter')
        self.declare_parameter('output', '/tmp/vrx-trace-samples.jsonl')
        self.output = pathlib.Path(self.get_parameter('output').value)
        self.odom = None; self.imu = None; self.gps = None
        self.left = 0.; self.right = 0.
        self.create_subscription(Odometry, 'wamv/odometry', self.on_odom, 20)
        self.create_subscription(Imu, 'wamv/imu', self.on_imu, 20)
        self.create_subscription(NavSatFix, 'wamv/gps', self.on_gps, 20)
        self.create_subscription(Float64, 'wamv/thrusters/left/thrust', lambda m: setattr(self, 'left', m.data), 20)
        self.create_subscription(Float64, 'wamv/thrusters/right/thrust', lambda m: setattr(self, 'right', m.data), 20)
    def on_imu(self, msg): self.imu = msg
    def on_gps(self, msg): self.gps = msg
    def on_odom(self, msg):
        self.odom = msg
        q=msg.pose.pose.orientation
        yaw_enu=math.atan2(2*(q.w*q.z+q.x*q.y),1-2*(q.y*q.y+q.z*q.z))
        yaw=math.pi/2-yaw_enu; v=msg.twist.twist.linear
        # ENU world velocity -> NED world -> body velocity.
        u=math.cos(yaw)*v.y+math.sin(yaw)*v.x; sway=-math.sin(yaw)*v.y+math.cos(yaw)*v.x
        imu=self.imu
        row={'time_s':msg.header.stamp.sec+msg.header.stamp.nanosec*1e-9,
             'state':[msg.pose.pose.position.y,msg.pose.pose.position.x,yaw,u,sway,-msg.twist.twist.angular.z],
             'imu':([imu.linear_acceleration.x,imu.linear_acceleration.y,imu.linear_acceleration.z,imu.angular_velocity.x,imu.angular_velocity.y,imu.angular_velocity.z] if imu else None),
             'gps_fix_valid':int(self.gps is not None and self.gps.status.status>=0),
             'thruster_newtons':[self.left,self.right]}
        with self.output.open('a') as f: f.write(json.dumps(row,separators=(',',':'))+'\n')

def main():
    rclpy.init(); node=VrxTraceExporter()
    try: rclpy.spin(node)
    finally: node.destroy_node(); rclpy.shutdown()
if __name__=='__main__': main()
