import {execFileSync} from "node:child_process";import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";import {tmpdir} from "node:os";import path from "node:path";
const ROOT="artifacts/gazebo/vehicle-b/rudder-transient",CACHE="validation/datasets/raw/kvlcc2-simman2008-third-party/kvlcc2-marin",proto=JSON.parse(await readFile(`${ROOT}/candidate-separation-protocol.json`)),parse=t=>t.split(/\r?\n/).slice(3).filter(x=>x.trim()).map(x=>x.trim().split(/\s+/).map(Number)),mean=a=>a.reduce((s,x)=>s+x,0)/a.length,rms=a=>Math.sqrt(mean(a.map(x=>x*x))),corr=(a,b)=>{const x=mean(a),y=mean(b),n=a.reduce((s,v,i)=>s+(v-x)*(b[i]-y),0);return n/Math.sqrt(a.reduce((s,v)=>s+(v-x)**2,0)*b.reduce((s,v)=>s+(v-y)**2,0))},rad=x=>x*Math.PI/180;
if(proto.status!=="precommitted-before-results")throw Error("protocol missing");
function local(rows){const [x0,y0,h0]=[rows[0][1],rows[0][2],rad(rows[0][4])],c=Math.cos(h0),s=Math.sin(h0);return rows.map(r=>({along:(r[1]-x0)*c+(r[2]-y0)*s,cross:-(r[1]-x0)*s+(r[2]-y0)*c,heading:r[4]-rows[0][4],sway:r[6],yawRate:r[8],rudder:r[9],rpm:r[10]}))}
const sample=(a,n=1000)=>Array.from({length:n},(_,i)=>a[Math.round(i*(a.length-1)/(n-1))]),pairs=[];
for(const [kind,neg,pos] of [["turning-circle","tc_-35","tc_35"],["zig-zag-10","zz_-10","zz_10"],["zig-zag-20","zz_-20","zz_20"]]){const A=sample(local(parse(await readFile(`${CACHE}/MARIN_FREE_KVLCC2_${neg}_m.dat`,"utf8")))),B=sample(local(parse(await readFile(`${CACHE}/MARIN_FREE_KVLCC2_${pos}_m.dat`,"utf8")))),channels={along:[A.map(x=>x.along),B.map(x=>x.along)],cross:[A.map(x=>x.cross),B.map(x=>-x.cross)],heading:[A.map(x=>x.heading),B.map(x=>-x.heading)],sway:[A.map(x=>x.sway),B.map(x=>-x.sway)],yaw_rate:[A.map(x=>x.yawRate),B.map(x=>-x.yawRate)],rudder:[A.map(x=>x.rudder),B.map(x=>-x.rudder)],rpm:[A.map(x=>x.rpm),B.map(x=>x.rpm)]};pairs.push({pair:kind,channels:Object.fromEntries(Object.entries(channels).map(([k,[a,b]])=>[k,{reflected_correlation:corr(a,b),rmse:rms(a.map((v,i)=>v-b[i]))}]))});}
const base=JSON.parse(await readFile("validation/external-references/kvlcc2/kvlcc2-l7.json")),g=base.interaction_coefficients,source=await readFile("packages/core/src/mmg.js","utf8"),reference=JSON.parse(await readFile("validation/external-references/kvlcc2-marin/artifacts/kvlcc2-marin-trajectory-comparison.json")),kinematic=reference.runs.map(r=>({id:r.id,passed:r.mapping_evidence.passed,position_kinematic_rmse_mps:r.mapping_evidence.position_kinematic_rmse_mps,heading_rate_correlation:r.mapping_evidence.heading_rate_correlation})),representation={sign_dependent_rudder_flow:{present:g.gamma_R_beta_R_negative.value!==g.gamma_R_beta_R_positive.value,negative:g.gamma_R_beta_R_negative.value,positive:g.gamma_R_beta_R_positive.value,implementation:/betaR<0\?p\.interaction\.gamma_R_beta_R_negative:p\.interaction\.gamma_R_beta_R_positive/.test(source)},transverse_propeller_rotation_force:{present:false,evidence:"propeller wrench is [axial thrust, 0, 0]; no rotation-direction parameter or transverse propeller force exists"},conclusion:"The model can represent asymmetric rudder inflow through unequal gamma_R branches, but cannot represent propeller-walk force from screw rotation."};
const allPositive=pairs.every(p=>["heading","yaw_rate","rudder"].every(k=>p.channels[k].reflected_correlation>0)),strictMirror=pairs.every(p=>["heading","yaw_rate","rudder"].every(k=>p.channels[k].reflected_correlation>=proto.candidates.sign_or_frame.sign_correlation_min)),kinematicPass=kinematic.every(x=>x.passed);
await writeFile(`${ROOT}/candidate-1-2-report.json`,JSON.stringify({schema_version:1,status:"completed",protocol:`${ROOT}/candidate-separation-protocol.json`,mirror_pairs:pairs,kinematic_ingestion_checks:kinematic,sign_or_frame_assessment:{sign_inversion_indicated:!allPositive,kinematic_mapping_failure:!kinematicPass,strict_mirror_symmetry_passed:strictMirror,conclusion:allPositive&&kinematicPass?"No ingestion sign/frame error is indicated. Reflected signs agree and all six raw kinematic mapping checks pass, but strict mirror symmetry fails, especially for 20/20 zig-zags; timing and/or physical asymmetry remains.":"A sign or kinematic mapping problem is indicated."},asymmetry_representation:representation,claim_limit:"Phase-normalized mirror residuals can reveal sign failures and asymmetry but cannot distinguish hydrodynamic asymmetry from run-condition differences by themselves."},null,2)+"\n");
