#!/usr/bin/env python3
"""ROS 2 Jazzy runtime exporter for the VRX WAM-V bridge.

This process is intentionally observation-only: commands are generated by the
shared TypeScript actuator module before publication, while this node records
the simulator's actual topics and serializes a trace-schema-v2 compatible
sample stream.
"""
import json
import math
import pathlib
from rclpy.node import Node
import rclpy
from nav_msgs.msg import Odometry
from sensor_msgs.msg import Imu, NavSatFix
from std_msgs.msg import Float64
from external_sensor_model import ExternalGpsModel, flu_to_body_ned, quaternion_to_ned_yaw

class VrxTraceExporter(Node):
    def __init__(self):
        super().__init__('vrx_trace_exporter')
        self.declare_parameter('output', '/tmp/vrx-trace-samples.jsonl')
        self.declare_parameter('seed', 0)
        self.declare_parameter('initial_n_m', 10000.0)
        self.declare_parameter('initial_e_m', 10000.0)
        self.output = pathlib.Path(self.get_parameter('output').value)
        self.odom = None; self.imu = None; self.gps = None
        self.gps_model = ExternalGpsModel(self.get_parameter('seed').value,
            self.get_parameter('initial_n_m').value, self.get_parameter('initial_e_m').value)
        self.left = 0.; self.right = 0.
        # Names verified from a live VRX v3.0.1 ROS graph.  The old
        # wamv/{sensor} and wamv/thrusters/{left,right} names do not exist in
        # the Surveyor VRX runtime.
        self.create_subscription(Odometry, '/odometry', self.on_odom, 20)
        self.create_subscription(Imu, '/imu', self.on_imu, 20)
        self.create_subscription(NavSatFix, '/gps', self.on_gps, 20)
        self.create_subscription(Float64, '/surveyor/thrusters/port/thrust', lambda m: setattr(self, 'left', m.data), 20)
        self.create_subscription(Float64, '/surveyor/thrusters/starboard/thrust', lambda m: setattr(self, 'right', m.data), 20)
    def on_imu(self, msg): self.imu = msg
    def on_gps(self, msg):
        timestamp=msg.header.stamp.sec+msg.header.stamp.nanosec*1e-9
        self.gps_model.ingest(timestamp,msg.latitude,msg.longitude,msg.status.status>=0)
        self.gps = msg
    def on_odom(self, msg):
        self.odom = msg
        q=msg.pose.pose.orientation
        yaw_enu=math.atan2(2*(q.w*q.z+q.x*q.y),1-2*(q.y*q.y+q.z*q.z))
        yaw=math.pi/2-yaw_enu; v=msg.twist.twist.linear
        # ENU world velocity -> NED world -> body velocity.
        u=math.cos(yaw)*v.y+math.sin(yaw)*v.x; sway=-math.sin(yaw)*v.y+math.cos(yaw)*v.x
        imu=self.imu
        imu_sample=None
        if imu is not None:
            iq=imu.orientation; its=imu.header.stamp.sec+imu.header.stamp.nanosec*1e-9
            imu_sample={'timestamp_s':its,'valid':True,
                'linear_accel_body':flu_to_body_ned(imu.linear_acceleration.x,imu.linear_acceleration.y,imu.linear_acceleration.z),
                'angular_rate_body':flu_to_body_ned(imu.angular_velocity.x,imu.angular_velocity.y,imu.angular_velocity.z),
                'yaw_ned_rad':quaternion_to_ned_yaw(iq.w,iq.x,iq.y,iq.z)}
        now=msg.header.stamp.sec+msg.header.stamp.nanosec*1e-9
        row={'time_s':msg.header.stamp.sec+msg.header.stamp.nanosec*1e-9,
             'state':[msg.pose.pose.position.y,msg.pose.pose.position.x,yaw,u,sway,-msg.twist.twist.angular.z],
             'imu':imu_sample,
             'gps':self.gps_model.sample(now),
             'thruster_newtons':[self.left,self.right]}
        with self.output.open('a') as f: f.write(json.dumps(row,separators=(',',':'))+'\n')

def main():
    rclpy.init(); node=VrxTraceExporter()
    try: rclpy.spin(node)
    finally: node.destroy_node(); rclpy.shutdown()
if __name__=='__main__': main()
